// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ani/training/v1/training.proto

package trainingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CPU-P01 only supports these capabilities. UNSPECIFIED is never a default.
type ExecutionKind int32

const (
	ExecutionKind_EXECUTION_KIND_UNSPECIFIED      ExecutionKind = 0
	ExecutionKind_EXECUTION_KIND_GENERAL_TRAINING ExecutionKind = 1
)

// Enum value maps for ExecutionKind.
var (
	ExecutionKind_name = map[int32]string{
		0: "EXECUTION_KIND_UNSPECIFIED",
		1: "EXECUTION_KIND_GENERAL_TRAINING",
	}
	ExecutionKind_value = map[string]int32{
		"EXECUTION_KIND_UNSPECIFIED":      0,
		"EXECUTION_KIND_GENERAL_TRAINING": 1,
	}
)

func (x ExecutionKind) Enum() *ExecutionKind {
	p := new(ExecutionKind)
	*p = x
	return p
}

func (x ExecutionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ani_training_v1_training_proto_enumTypes[0].Descriptor()
}

func (ExecutionKind) Type() protoreflect.EnumType {
	return &file_ani_training_v1_training_proto_enumTypes[0]
}

func (x ExecutionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionKind.Descriptor instead.
func (ExecutionKind) EnumDescriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{0}
}

type DeliveryMode int32

const (
	DeliveryMode_DELIVERY_MODE_UNSPECIFIED    DeliveryMode = 0
	DeliveryMode_DELIVERY_MODE_SAVE_ARTIFACTS DeliveryMode = 1
)

// Enum value maps for DeliveryMode.
var (
	DeliveryMode_name = map[int32]string{
		0: "DELIVERY_MODE_UNSPECIFIED",
		1: "DELIVERY_MODE_SAVE_ARTIFACTS",
	}
	DeliveryMode_value = map[string]int32{
		"DELIVERY_MODE_UNSPECIFIED":    0,
		"DELIVERY_MODE_SAVE_ARTIFACTS": 1,
	}
)

func (x DeliveryMode) Enum() *DeliveryMode {
	p := new(DeliveryMode)
	*p = x
	return p
}

func (x DeliveryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ani_training_v1_training_proto_enumTypes[1].Descriptor()
}

func (DeliveryMode) Type() protoreflect.EnumType {
	return &file_ani_training_v1_training_proto_enumTypes[1]
}

func (x DeliveryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryMode.Descriptor instead.
func (DeliveryMode) EnumDescriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{1}
}

type OutputKind int32

const (
	OutputKind_OUTPUT_KIND_UNSPECIFIED OutputKind = 0
	OutputKind_OUTPUT_KIND_CHECKPOINT  OutputKind = 1
)

// Enum value maps for OutputKind.
var (
	OutputKind_name = map[int32]string{
		0: "OUTPUT_KIND_UNSPECIFIED",
		1: "OUTPUT_KIND_CHECKPOINT",
	}
	OutputKind_value = map[string]int32{
		"OUTPUT_KIND_UNSPECIFIED": 0,
		"OUTPUT_KIND_CHECKPOINT":  1,
	}
)

func (x OutputKind) Enum() *OutputKind {
	p := new(OutputKind)
	*p = x
	return p
}

func (x OutputKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ani_training_v1_training_proto_enumTypes[2].Descriptor()
}

func (OutputKind) Type() protoreflect.EnumType {
	return &file_ani_training_v1_training_proto_enumTypes[2]
}

func (x OutputKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputKind.Descriptor instead.
func (OutputKind) EnumDescriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{2}
}

type TrainingOutcome int32

const (
	TrainingOutcome_TRAINING_OUTCOME_UNSPECIFIED TrainingOutcome = 0
	TrainingOutcome_TRAINING_OUTCOME_SUCCEEDED   TrainingOutcome = 1
	TrainingOutcome_TRAINING_OUTCOME_FAILED      TrainingOutcome = 2
)

// Enum value maps for TrainingOutcome.
var (
	TrainingOutcome_name = map[int32]string{
		0: "TRAINING_OUTCOME_UNSPECIFIED",
		1: "TRAINING_OUTCOME_SUCCEEDED",
		2: "TRAINING_OUTCOME_FAILED",
	}
	TrainingOutcome_value = map[string]int32{
		"TRAINING_OUTCOME_UNSPECIFIED": 0,
		"TRAINING_OUTCOME_SUCCEEDED":   1,
		"TRAINING_OUTCOME_FAILED":      2,
	}
)

func (x TrainingOutcome) Enum() *TrainingOutcome {
	p := new(TrainingOutcome)
	*p = x
	return p
}

func (x TrainingOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrainingOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_ani_training_v1_training_proto_enumTypes[3].Descriptor()
}

func (TrainingOutcome) Type() protoreflect.EnumType {
	return &file_ani_training_v1_training_proto_enumTypes[3]
}

func (x TrainingOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrainingOutcome.Descriptor instead.
func (TrainingOutcome) EnumDescriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{3}
}

type CandidateStorageState int32

const (
	CandidateStorageState_CANDIDATE_STORAGE_STATE_UNSPECIFIED    CandidateStorageState = 0
	CandidateStorageState_CANDIDATE_STORAGE_STATE_WORKSPACE_ONLY CandidateStorageState = 1
)

// Enum value maps for CandidateStorageState.
var (
	CandidateStorageState_name = map[int32]string{
		0: "CANDIDATE_STORAGE_STATE_UNSPECIFIED",
		1: "CANDIDATE_STORAGE_STATE_WORKSPACE_ONLY",
	}
	CandidateStorageState_value = map[string]int32{
		"CANDIDATE_STORAGE_STATE_UNSPECIFIED":    0,
		"CANDIDATE_STORAGE_STATE_WORKSPACE_ONLY": 1,
	}
)

func (x CandidateStorageState) Enum() *CandidateStorageState {
	p := new(CandidateStorageState)
	*p = x
	return p
}

func (x CandidateStorageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CandidateStorageState) Descriptor() protoreflect.EnumDescriptor {
	return file_ani_training_v1_training_proto_enumTypes[4].Descriptor()
}

func (CandidateStorageState) Type() protoreflect.EnumType {
	return &file_ani_training_v1_training_proto_enumTypes[4]
}

func (x CandidateStorageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CandidateStorageState.Descriptor instead.
func (CandidateStorageState) EnumDescriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{4}
}

type WorkspaceMode int32

const (
	WorkspaceMode_WORKSPACE_MODE_UNSPECIFIED       WorkspaceMode = 0
	WorkspaceMode_WORKSPACE_MODE_KFP_RUN_WORKSPACE WorkspaceMode = 1
	WorkspaceMode_WORKSPACE_MODE_EXECUTION_PVC     WorkspaceMode = 2
)

// Enum value maps for WorkspaceMode.
var (
	WorkspaceMode_name = map[int32]string{
		0: "WORKSPACE_MODE_UNSPECIFIED",
		1: "WORKSPACE_MODE_KFP_RUN_WORKSPACE",
		2: "WORKSPACE_MODE_EXECUTION_PVC",
	}
	WorkspaceMode_value = map[string]int32{
		"WORKSPACE_MODE_UNSPECIFIED":       0,
		"WORKSPACE_MODE_KFP_RUN_WORKSPACE": 1,
		"WORKSPACE_MODE_EXECUTION_PVC":     2,
	}
)

func (x WorkspaceMode) Enum() *WorkspaceMode {
	p := new(WorkspaceMode)
	*p = x
	return p
}

func (x WorkspaceMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ani_training_v1_training_proto_enumTypes[5].Descriptor()
}

func (WorkspaceMode) Type() protoreflect.EnumType {
	return &file_ani_training_v1_training_proto_enumTypes[5]
}

func (x WorkspaceMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceMode.Descriptor instead.
func (WorkspaceMode) EnumDescriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{5}
}

type FileRole int32

const (
	FileRole_FILE_ROLE_UNSPECIFIED        FileRole = 0
	FileRole_FILE_ROLE_CHECKPOINT         FileRole = 1
	FileRole_FILE_ROLE_MODEL_CONFIG       FileRole = 2
	FileRole_FILE_ROLE_METRICS            FileRole = 3
	FileRole_FILE_ROLE_SUMMARY            FileRole = 4
	FileRole_FILE_ROLE_INPUT_MANIFEST     FileRole = 5
	FileRole_FILE_ROLE_EXECUTION_MANIFEST FileRole = 6
	FileRole_FILE_ROLE_LOG                FileRole = 7
)

// Enum value maps for FileRole.
var (
	FileRole_name = map[int32]string{
		0: "FILE_ROLE_UNSPECIFIED",
		1: "FILE_ROLE_CHECKPOINT",
		2: "FILE_ROLE_MODEL_CONFIG",
		3: "FILE_ROLE_METRICS",
		4: "FILE_ROLE_SUMMARY",
		5: "FILE_ROLE_INPUT_MANIFEST",
		6: "FILE_ROLE_EXECUTION_MANIFEST",
		7: "FILE_ROLE_LOG",
	}
	FileRole_value = map[string]int32{
		"FILE_ROLE_UNSPECIFIED":        0,
		"FILE_ROLE_CHECKPOINT":         1,
		"FILE_ROLE_MODEL_CONFIG":       2,
		"FILE_ROLE_METRICS":            3,
		"FILE_ROLE_SUMMARY":            4,
		"FILE_ROLE_INPUT_MANIFEST":     5,
		"FILE_ROLE_EXECUTION_MANIFEST": 6,
		"FILE_ROLE_LOG":                7,
	}
)

func (x FileRole) Enum() *FileRole {
	p := new(FileRole)
	*p = x
	return p
}

func (x FileRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileRole) Descriptor() protoreflect.EnumDescriptor {
	return file_ani_training_v1_training_proto_enumTypes[6].Descriptor()
}

func (FileRole) Type() protoreflect.EnumType {
	return &file_ani_training_v1_training_proto_enumTypes[6]
}

func (x FileRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileRole.Descriptor instead.
func (FileRole) EnumDescriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{6}
}

// Values are typed before canonical hashing. Decimal values use the contract's
// canonical decimal string, never binary floating point or shell fragments.
type Parameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Parameter_StringValue
	//	*Parameter_IntegerValue
	//	*Parameter_BooleanValue
	//	*Parameter_DecimalValue
	Value         isParameter_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_ani_training_v1_training_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{0}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetValue() isParameter_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Parameter) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Parameter_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Parameter) GetIntegerValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Parameter_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return 0
}

func (x *Parameter) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Parameter_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *Parameter) GetDecimalValue() string {
	if x != nil {
		if x, ok := x.Value.(*Parameter_DecimalValue); ok {
			return x.DecimalValue
		}
	}
	return ""
}

type isParameter_Value interface {
	isParameter_Value()
}

type Parameter_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Parameter_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,3,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type Parameter_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,4,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type Parameter_DecimalValue struct {
	DecimalValue string `protobuf:"bytes,5,opt,name=decimal_value,json=decimalValue,proto3,oneof"`
}

func (*Parameter_StringValue) isParameter_Value() {}

func (*Parameter_IntegerValue) isParameter_Value() {}

func (*Parameter_BooleanValue) isParameter_Value() {}

func (*Parameter_DecimalValue) isParameter_Value() {}

type ExecutionIdentity struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationId       string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionId       string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	ExecutionSpecHash string                 `protobuf:"bytes,3,opt,name=execution_spec_hash,json=executionSpecHash,proto3" json:"execution_spec_hash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutionIdentity) Reset() {
	*x = ExecutionIdentity{}
	mi := &file_ani_training_v1_training_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionIdentity) ProtoMessage() {}

func (x *ExecutionIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionIdentity.ProtoReflect.Descriptor instead.
func (*ExecutionIdentity) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionIdentity) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ExecutionIdentity) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionIdentity) GetExecutionSpecHash() string {
	if x != nil {
		return x.ExecutionSpecHash
	}
	return ""
}

// An approved connection reference, not a user-provided endpoint or credential.
// version_id fixes a backend version; immutable_copy means the managed object
// is write-protected instead. Exactly one immutability proof is required;
// selecting immutable_copy with value false is invalid.
type FixedObjectRef struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StorageConnectionId string                 `protobuf:"bytes,1,opt,name=storage_connection_id,json=storageConnectionId,proto3" json:"storage_connection_id,omitempty"`
	Bucket              string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key                 string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Immutability:
	//
	//	*FixedObjectRef_VersionId
	//	*FixedObjectRef_ImmutableCopy
	Immutability  isFixedObjectRef_Immutability `protobuf_oneof:"immutability"`
	SizeBytes     int64                         `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                        `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedObjectRef) Reset() {
	*x = FixedObjectRef{}
	mi := &file_ani_training_v1_training_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedObjectRef) ProtoMessage() {}

func (x *FixedObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedObjectRef.ProtoReflect.Descriptor instead.
func (*FixedObjectRef) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{2}
}

func (x *FixedObjectRef) GetStorageConnectionId() string {
	if x != nil {
		return x.StorageConnectionId
	}
	return ""
}

func (x *FixedObjectRef) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FixedObjectRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FixedObjectRef) GetImmutability() isFixedObjectRef_Immutability {
	if x != nil {
		return x.Immutability
	}
	return nil
}

func (x *FixedObjectRef) GetVersionId() string {
	if x != nil {
		if x, ok := x.Immutability.(*FixedObjectRef_VersionId); ok {
			return x.VersionId
		}
	}
	return ""
}

func (x *FixedObjectRef) GetImmutableCopy() bool {
	if x != nil {
		if x, ok := x.Immutability.(*FixedObjectRef_ImmutableCopy); ok {
			return x.ImmutableCopy
		}
	}
	return false
}

func (x *FixedObjectRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FixedObjectRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type isFixedObjectRef_Immutability interface {
	isFixedObjectRef_Immutability()
}

type FixedObjectRef_VersionId struct {
	VersionId string `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3,oneof"`
}

type FixedObjectRef_ImmutableCopy struct {
	ImmutableCopy bool `protobuf:"varint,5,opt,name=immutable_copy,json=immutableCopy,proto3,oneof"`
}

func (*FixedObjectRef_VersionId) isFixedObjectRef_Immutability() {}

func (*FixedObjectRef_ImmutableCopy) isFixedObjectRef_Immutability() {}

type InputRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InputVersionId string                 `protobuf:"bytes,1,opt,name=input_version_id,json=inputVersionId,proto3" json:"input_version_id,omitempty"`
	Object         *FixedObjectRef        `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Format         string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	SchemaVersion  string                 `protobuf:"bytes,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RowCount       uint32                 `protobuf:"varint,5,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	FeatureCount   uint32                 `protobuf:"varint,6,opt,name=feature_count,json=featureCount,proto3" json:"feature_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InputRef) Reset() {
	*x = InputRef{}
	mi := &file_ani_training_v1_training_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRef) ProtoMessage() {}

func (x *InputRef) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRef.ProtoReflect.Descriptor instead.
func (*InputRef) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{3}
}

func (x *InputRef) GetInputVersionId() string {
	if x != nil {
		return x.InputVersionId
	}
	return ""
}

func (x *InputRef) GetObject() *FixedObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *InputRef) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *InputRef) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *InputRef) GetRowCount() uint32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *InputRef) GetFeatureCount() uint32 {
	if x != nil {
		return x.FeatureCount
	}
	return 0
}

type RuntimeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiGroup      string                 `protobuf:"bytes,3,opt,name=api_group,json=apiGroup,proto3" json:"api_group,omitempty"`
	ContentSha256 string                 `protobuf:"bytes,4,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	// Actual Runtime target job names; never guessed from a controller default.
	TargetJobs    []string `protobuf:"bytes,5,rep,name=target_jobs,json=targetJobs,proto3" json:"target_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeRef) Reset() {
	*x = RuntimeRef{}
	mi := &file_ani_training_v1_training_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeRef) ProtoMessage() {}

func (x *RuntimeRef) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeRef.ProtoReflect.Descriptor instead.
func (*RuntimeRef) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RuntimeRef) GetApiGroup() string {
	if x != nil {
		return x.ApiGroup
	}
	return ""
}

func (x *RuntimeRef) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *RuntimeRef) GetTargetJobs() []string {
	if x != nil {
		return x.TargetJobs
	}
	return nil
}

type ProgramRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageVersionId string                 `protobuf:"bytes,1,opt,name=image_version_id,json=imageVersionId,proto3" json:"image_version_id,omitempty"`
	// Full immutable registry reference, including @sha256:<digest>.
	ImageDigest        string       `protobuf:"bytes,2,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	Command            []string     `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	ResolvedArgs       []string     `protobuf:"bytes,4,rep,name=resolved_args,json=resolvedArgs,proto3" json:"resolved_args,omitempty"`
	ResolvedParameters []*Parameter `protobuf:"bytes,5,rep,name=resolved_parameters,json=resolvedParameters,proto3" json:"resolved_parameters,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProgramRef) Reset() {
	*x = ProgramRef{}
	mi := &file_ani_training_v1_training_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramRef) ProtoMessage() {}

func (x *ProgramRef) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramRef.ProtoReflect.Descriptor instead.
func (*ProgramRef) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{5}
}

func (x *ProgramRef) GetImageVersionId() string {
	if x != nil {
		return x.ImageVersionId
	}
	return ""
}

func (x *ProgramRef) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *ProgramRef) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ProgramRef) GetResolvedArgs() []string {
	if x != nil {
		return x.ResolvedArgs
	}
	return nil
}

func (x *ProgramRef) GetResolvedParameters() []*Parameter {
	if x != nil {
		return x.ResolvedParameters
	}
	return nil
}

type CPUResources struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Nodes              uint32                 `protobuf:"varint,1,opt,name=nodes,proto3" json:"nodes,omitempty"`
	ProcessesPerNode   uint32                 `protobuf:"varint,2,opt,name=processes_per_node,json=processesPerNode,proto3" json:"processes_per_node,omitempty"`
	RequestMillicpu    int64                  `protobuf:"varint,3,opt,name=request_millicpu,json=requestMillicpu,proto3" json:"request_millicpu,omitempty"`
	LimitMillicpu      int64                  `protobuf:"varint,4,opt,name=limit_millicpu,json=limitMillicpu,proto3" json:"limit_millicpu,omitempty"`
	RequestMemoryBytes int64                  `protobuf:"varint,5,opt,name=request_memory_bytes,json=requestMemoryBytes,proto3" json:"request_memory_bytes,omitempty"`
	LimitMemoryBytes   int64                  `protobuf:"varint,6,opt,name=limit_memory_bytes,json=limitMemoryBytes,proto3" json:"limit_memory_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CPUResources) Reset() {
	*x = CPUResources{}
	mi := &file_ani_training_v1_training_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUResources) ProtoMessage() {}

func (x *CPUResources) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUResources.ProtoReflect.Descriptor instead.
func (*CPUResources) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{6}
}

func (x *CPUResources) GetNodes() uint32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *CPUResources) GetProcessesPerNode() uint32 {
	if x != nil {
		return x.ProcessesPerNode
	}
	return 0
}

func (x *CPUResources) GetRequestMillicpu() int64 {
	if x != nil {
		return x.RequestMillicpu
	}
	return 0
}

func (x *CPUResources) GetLimitMillicpu() int64 {
	if x != nil {
		return x.LimitMillicpu
	}
	return 0
}

func (x *CPUResources) GetRequestMemoryBytes() int64 {
	if x != nil {
		return x.RequestMemoryBytes
	}
	return 0
}

func (x *CPUResources) GetLimitMemoryBytes() int64 {
	if x != nil {
		return x.LimitMemoryBytes
	}
	return 0
}

// This immutable contract can be frozen before a workspace exists. It must
// never acquire a PVC UID or KFP Run ID after execution_spec_hash is calculated.
type WorkspaceContract struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Mode               WorkspaceMode          `protobuf:"varint,1,opt,name=mode,proto3,enum=ani.training.v1.WorkspaceMode" json:"mode,omitempty"`
	StorageClass       string                 `protobuf:"bytes,2,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	CapacityBytes      int64                  `protobuf:"varint,3,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	InputSubpath       string                 `protobuf:"bytes,4,opt,name=input_subpath,json=inputSubpath,proto3" json:"input_subpath,omitempty"`
	TrainingSubpath    string                 `protobuf:"bytes,5,opt,name=training_subpath,json=trainingSubpath,proto3" json:"training_subpath,omitempty"`
	ReportsSubpath     string                 `protobuf:"bytes,6,opt,name=reports_subpath,json=reportsSubpath,proto3" json:"reports_subpath,omitempty"`
	PublicationSubpath string                 `protobuf:"bytes,7,opt,name=publication_subpath,json=publicationSubpath,proto3" json:"publication_subpath,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkspaceContract) Reset() {
	*x = WorkspaceContract{}
	mi := &file_ani_training_v1_training_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceContract) ProtoMessage() {}

func (x *WorkspaceContract) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceContract.ProtoReflect.Descriptor instead.
func (*WorkspaceContract) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{7}
}

func (x *WorkspaceContract) GetMode() WorkspaceMode {
	if x != nil {
		return x.Mode
	}
	return WorkspaceMode_WORKSPACE_MODE_UNSPECIFIED
}

func (x *WorkspaceContract) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *WorkspaceContract) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *WorkspaceContract) GetInputSubpath() string {
	if x != nil {
		return x.InputSubpath
	}
	return ""
}

func (x *WorkspaceContract) GetTrainingSubpath() string {
	if x != nil {
		return x.TrainingSubpath
	}
	return ""
}

func (x *WorkspaceContract) GetReportsSubpath() string {
	if x != nil {
		return x.ReportsSubpath
	}
	return ""
}

func (x *WorkspaceContract) GetPublicationSubpath() string {
	if x != nil {
		return x.PublicationSubpath
	}
	return ""
}

// Runtime binding is separate from the immutable admission snapshot.
// Namespace and PVC UID must match actual objects, including on every reuse.
type WorkspaceRef struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Mode               WorkspaceMode          `protobuf:"varint,1,opt,name=mode,proto3,enum=ani.training.v1.WorkspaceMode" json:"mode,omitempty"`
	NamespaceName      string                 `protobuf:"bytes,2,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	NamespaceUid       string                 `protobuf:"bytes,3,opt,name=namespace_uid,json=namespaceUid,proto3" json:"namespace_uid,omitempty"`
	PvcName            string                 `protobuf:"bytes,4,opt,name=pvc_name,json=pvcName,proto3" json:"pvc_name,omitempty"`
	PvcUid             string                 `protobuf:"bytes,5,opt,name=pvc_uid,json=pvcUid,proto3" json:"pvc_uid,omitempty"`
	InputSubpath       string                 `protobuf:"bytes,6,opt,name=input_subpath,json=inputSubpath,proto3" json:"input_subpath,omitempty"`
	TrainingSubpath    string                 `protobuf:"bytes,7,opt,name=training_subpath,json=trainingSubpath,proto3" json:"training_subpath,omitempty"`
	ReportsSubpath     string                 `protobuf:"bytes,8,opt,name=reports_subpath,json=reportsSubpath,proto3" json:"reports_subpath,omitempty"`
	PublicationSubpath string                 `protobuf:"bytes,9,opt,name=publication_subpath,json=publicationSubpath,proto3" json:"publication_subpath,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkspaceRef) Reset() {
	*x = WorkspaceRef{}
	mi := &file_ani_training_v1_training_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceRef) ProtoMessage() {}

func (x *WorkspaceRef) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceRef.ProtoReflect.Descriptor instead.
func (*WorkspaceRef) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{8}
}

func (x *WorkspaceRef) GetMode() WorkspaceMode {
	if x != nil {
		return x.Mode
	}
	return WorkspaceMode_WORKSPACE_MODE_UNSPECIFIED
}

func (x *WorkspaceRef) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *WorkspaceRef) GetNamespaceUid() string {
	if x != nil {
		return x.NamespaceUid
	}
	return ""
}

func (x *WorkspaceRef) GetPvcName() string {
	if x != nil {
		return x.PvcName
	}
	return ""
}

func (x *WorkspaceRef) GetPvcUid() string {
	if x != nil {
		return x.PvcUid
	}
	return ""
}

func (x *WorkspaceRef) GetInputSubpath() string {
	if x != nil {
		return x.InputSubpath
	}
	return ""
}

func (x *WorkspaceRef) GetTrainingSubpath() string {
	if x != nil {
		return x.TrainingSubpath
	}
	return ""
}

func (x *WorkspaceRef) GetReportsSubpath() string {
	if x != nil {
		return x.ReportsSubpath
	}
	return ""
}

func (x *WorkspaceRef) GetPublicationSubpath() string {
	if x != nil {
		return x.PublicationSubpath
	}
	return ""
}

type RequiredOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          FileRole               `protobuf:"varint,1,opt,name=role,proto3,enum=ani.training.v1.FileRole" json:"role,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	MaxSizeBytes  int64                  `protobuf:"varint,3,opt,name=max_size_bytes,json=maxSizeBytes,proto3" json:"max_size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiredOutput) Reset() {
	*x = RequiredOutput{}
	mi := &file_ani_training_v1_training_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredOutput) ProtoMessage() {}

func (x *RequiredOutput) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredOutput.ProtoReflect.Descriptor instead.
func (*RequiredOutput) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{9}
}

func (x *RequiredOutput) GetRole() FileRole {
	if x != nil {
		return x.Role
	}
	return FileRole_FILE_ROLE_UNSPECIFIED
}

func (x *RequiredOutput) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *RequiredOutput) GetMaxSizeBytes() int64 {
	if x != nil {
		return x.MaxSizeBytes
	}
	return 0
}

type OutputContract struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion   string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OutputKind      OutputKind             `protobuf:"varint,2,opt,name=output_kind,json=outputKind,proto3,enum=ani.training.v1.OutputKind" json:"output_kind,omitempty"`
	DeliveryMode    DeliveryMode           `protobuf:"varint,3,opt,name=delivery_mode,json=deliveryMode,proto3,enum=ani.training.v1.DeliveryMode" json:"delivery_mode,omitempty"`
	RequiredFiles   []*RequiredOutput      `protobuf:"bytes,4,rep,name=required_files,json=requiredFiles,proto3" json:"required_files,omitempty"`
	MaxFileCount    uint32                 `protobuf:"varint,5,opt,name=max_file_count,json=maxFileCount,proto3" json:"max_file_count,omitempty"`
	MaxTotalBytes   int64                  `protobuf:"varint,6,opt,name=max_total_bytes,json=maxTotalBytes,proto3" json:"max_total_bytes,omitempty"`
	CreateTarBundle bool                   `protobuf:"varint,7,opt,name=create_tar_bundle,json=createTarBundle,proto3" json:"create_tar_bundle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OutputContract) Reset() {
	*x = OutputContract{}
	mi := &file_ani_training_v1_training_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputContract) ProtoMessage() {}

func (x *OutputContract) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputContract.ProtoReflect.Descriptor instead.
func (*OutputContract) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{10}
}

func (x *OutputContract) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *OutputContract) GetOutputKind() OutputKind {
	if x != nil {
		return x.OutputKind
	}
	return OutputKind_OUTPUT_KIND_UNSPECIFIED
}

func (x *OutputContract) GetDeliveryMode() DeliveryMode {
	if x != nil {
		return x.DeliveryMode
	}
	return DeliveryMode_DELIVERY_MODE_UNSPECIFIED
}

func (x *OutputContract) GetRequiredFiles() []*RequiredOutput {
	if x != nil {
		return x.RequiredFiles
	}
	return nil
}

func (x *OutputContract) GetMaxFileCount() uint32 {
	if x != nil {
		return x.MaxFileCount
	}
	return 0
}

func (x *OutputContract) GetMaxTotalBytes() int64 {
	if x != nil {
		return x.MaxTotalBytes
	}
	return 0
}

func (x *OutputContract) GetCreateTarBundle() bool {
	if x != nil {
		return x.CreateTarBundle
	}
	return false
}

// A hash always describes actual file bytes, not an object-store ETag.
// Paths are normalized relative POSIX paths: no absolute/traversal paths,
// duplicate entries, symlinks, hardlinks, or special files are accepted.
type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelativePath  string                 `protobuf:"bytes,1,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	Role          FileRole               `protobuf:"varint,2,opt,name=role,proto3,enum=ani.training.v1.FileRole" json:"role,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_ani_training_v1_training_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{11}
}

func (x *FileEntry) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *FileEntry) GetRole() FileRole {
	if x != nil {
		return x.Role
	}
	return FileRole_FILE_ROLE_UNSPECIFIED
}

func (x *FileEntry) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileEntry) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ManifestRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelativePath  string                 `protobuf:"bytes,1,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRef) Reset() {
	*x = ManifestRef{}
	mi := &file_ani_training_v1_training_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRef) ProtoMessage() {}

func (x *ManifestRef) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRef.ProtoReflect.Descriptor instead.
func (*ManifestRef) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{12}
}

func (x *ManifestRef) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *ManifestRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ManifestRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DecimalValue  string                 `protobuf:"bytes,2,opt,name=decimal_value,json=decimalValue,proto3" json:"decimal_value,omitempty"`
	Step          *int64                 `protobuf:"varint,3,opt,name=step,proto3,oneof" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_ani_training_v1_training_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{13}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetDecimalValue() string {
	if x != nil {
		return x.DecimalValue
	}
	return ""
}

func (x *Metric) GetStep() int64 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

type LogRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owner-issued reference to the original execution's actual training logs.
	LogId         string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ResourceUid   string `protobuf:"bytes,2,opt,name=resource_uid,json=resourceUid,proto3" json:"resource_uid,omitempty"`
	ContainerName string `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRef) Reset() {
	*x = LogRef{}
	mi := &file_ani_training_v1_training_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRef) ProtoMessage() {}

func (x *LogRef) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRef.ProtoReflect.Descriptor instead.
func (*LogRef) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{14}
}

func (x *LogRef) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *LogRef) GetResourceUid() string {
	if x != nil {
		return x.ResourceUid
	}
	return ""
}

func (x *LogRef) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type TrainingInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion    string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Identity         *ExecutionIdentity     `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Input            *InputRef              `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	PreparedManifest *ManifestRef           `protobuf:"bytes,4,opt,name=prepared_manifest,json=preparedManifest,proto3" json:"prepared_manifest,omitempty"`
	Program          *ProgramRef            `protobuf:"bytes,5,opt,name=program,proto3" json:"program,omitempty"`
	Runtime          *RuntimeRef            `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Resources        *CPUResources          `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
	Workspace        *WorkspaceRef          `protobuf:"bytes,8,opt,name=workspace,proto3" json:"workspace,omitempty"`
	OutputContract   *OutputContract        `protobuf:"bytes,9,opt,name=output_contract,json=outputContract,proto3" json:"output_contract,omitempty"`
	DeadlineAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deadline_at,json=deadlineAt,proto3" json:"deadline_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrainingInput) Reset() {
	*x = TrainingInput{}
	mi := &file_ani_training_v1_training_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingInput) ProtoMessage() {}

func (x *TrainingInput) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingInput.ProtoReflect.Descriptor instead.
func (*TrainingInput) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{15}
}

func (x *TrainingInput) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *TrainingInput) GetIdentity() *ExecutionIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *TrainingInput) GetInput() *InputRef {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TrainingInput) GetPreparedManifest() *ManifestRef {
	if x != nil {
		return x.PreparedManifest
	}
	return nil
}

func (x *TrainingInput) GetProgram() *ProgramRef {
	if x != nil {
		return x.Program
	}
	return nil
}

func (x *TrainingInput) GetRuntime() *RuntimeRef {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *TrainingInput) GetResources() *CPUResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *TrainingInput) GetWorkspace() *WorkspaceRef {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *TrainingInput) GetOutputContract() *OutputContract {
	if x != nil {
		return x.OutputContract
	}
	return nil
}

func (x *TrainingInput) GetDeadlineAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeadlineAt
	}
	return nil
}

// A candidate from training/collection. This message never proves publication
// and is never sufficient by itself to issue a download authorization.
type TrainingResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion      string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Identity           *ExecutionIdentity     `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Outcome            TrainingOutcome        `protobuf:"varint,3,opt,name=outcome,proto3,enum=ani.training.v1.TrainingOutcome" json:"outcome,omitempty"`
	CompletedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	OutputKind         OutputKind             `protobuf:"varint,5,opt,name=output_kind,json=outputKind,proto3,enum=ani.training.v1.OutputKind" json:"output_kind,omitempty"`
	StorageState       CandidateStorageState  `protobuf:"varint,6,opt,name=storage_state,json=storageState,proto3,enum=ani.training.v1.CandidateStorageState" json:"storage_state,omitempty"`
	Workspace          *WorkspaceRef          `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`
	RelativeOutputPath string                 `protobuf:"bytes,8,opt,name=relative_output_path,json=relativeOutputPath,proto3" json:"relative_output_path,omitempty"`
	Files              []*FileEntry           `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`
	Manifest           *ManifestRef           `protobuf:"bytes,10,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Metrics            []*Metric              `protobuf:"bytes,11,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Logs               []*LogRef              `protobuf:"bytes,12,rep,name=logs,proto3" json:"logs,omitempty"`
	FailureReason      string                 `protobuf:"bytes,13,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TrainingResult) Reset() {
	*x = TrainingResult{}
	mi := &file_ani_training_v1_training_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingResult) ProtoMessage() {}

func (x *TrainingResult) ProtoReflect() protoreflect.Message {
	mi := &file_ani_training_v1_training_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingResult.ProtoReflect.Descriptor instead.
func (*TrainingResult) Descriptor() ([]byte, []int) {
	return file_ani_training_v1_training_proto_rawDescGZIP(), []int{16}
}

func (x *TrainingResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *TrainingResult) GetIdentity() *ExecutionIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *TrainingResult) GetOutcome() TrainingOutcome {
	if x != nil {
		return x.Outcome
	}
	return TrainingOutcome_TRAINING_OUTCOME_UNSPECIFIED
}

func (x *TrainingResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TrainingResult) GetOutputKind() OutputKind {
	if x != nil {
		return x.OutputKind
	}
	return OutputKind_OUTPUT_KIND_UNSPECIFIED
}

func (x *TrainingResult) GetStorageState() CandidateStorageState {
	if x != nil {
		return x.StorageState
	}
	return CandidateStorageState_CANDIDATE_STORAGE_STATE_UNSPECIFIED
}

func (x *TrainingResult) GetWorkspace() *WorkspaceRef {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *TrainingResult) GetRelativeOutputPath() string {
	if x != nil {
		return x.RelativeOutputPath
	}
	return ""
}

func (x *TrainingResult) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *TrainingResult) GetManifest() *ManifestRef {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *TrainingResult) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TrainingResult) GetLogs() []*LogRef {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *TrainingResult) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

var File_ani_training_v1_training_proto protoreflect.FileDescriptor

const file_ani_training_v1_training_proto_rawDesc = "" +
	"\n" +
	"\x1eani/training/v1/training.proto\x12\x0fani.training.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12%\n" +
	"\rinteger_value\x18\x03 \x01(\x03H\x00R\fintegerValue\x12%\n" +
	"\rboolean_value\x18\x04 \x01(\bH\x00R\fbooleanValue\x12%\n" +
	"\rdecimal_value\x18\x05 \x01(\tH\x00R\fdecimalValueB\a\n" +
	"\x05value\"\x89\x01\n" +
	"\x11ExecutionIdentity\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12.\n" +
	"\x13execution_spec_hash\x18\x03 \x01(\tR\x11executionSpecHash\"\xff\x01\n" +
	"\x0eFixedObjectRef\x122\n" +
	"\x15storage_connection_id\x18\x01 \x01(\tR\x13storageConnectionId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x1f\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tH\x00R\tversionId\x12'\n" +
	"\x0eimmutable_copy\x18\x05 \x01(\bH\x00R\rimmutableCopy\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256B\x0e\n" +
	"\fimmutability\"\xee\x01\n" +
	"\bInputRef\x12(\n" +
	"\x10input_version_id\x18\x01 \x01(\tR\x0einputVersionId\x127\n" +
	"\x06object\x18\x02 \x01(\v2\x1f.ani.training.v1.FixedObjectRefR\x06object\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\tR\rschemaVersion\x12\x1b\n" +
	"\trow_count\x18\x05 \x01(\rR\browCount\x12#\n" +
	"\rfeature_count\x18\x06 \x01(\rR\ffeatureCount\"\x99\x01\n" +
	"\n" +
	"RuntimeRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1b\n" +
	"\tapi_group\x18\x03 \x01(\tR\bapiGroup\x12%\n" +
	"\x0econtent_sha256\x18\x04 \x01(\tR\rcontentSha256\x12\x1f\n" +
	"\vtarget_jobs\x18\x05 \x03(\tR\n" +
	"targetJobs\"\xe5\x01\n" +
	"\n" +
	"ProgramRef\x12(\n" +
	"\x10image_version_id\x18\x01 \x01(\tR\x0eimageVersionId\x12!\n" +
	"\fimage_digest\x18\x02 \x01(\tR\vimageDigest\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12#\n" +
	"\rresolved_args\x18\x04 \x03(\tR\fresolvedArgs\x12K\n" +
	"\x13resolved_parameters\x18\x05 \x03(\v2\x1a.ani.training.v1.ParameterR\x12resolvedParameters\"\x84\x02\n" +
	"\fCPUResources\x12\x14\n" +
	"\x05nodes\x18\x01 \x01(\rR\x05nodes\x12,\n" +
	"\x12processes_per_node\x18\x02 \x01(\rR\x10processesPerNode\x12)\n" +
	"\x10request_millicpu\x18\x03 \x01(\x03R\x0frequestMillicpu\x12%\n" +
	"\x0elimit_millicpu\x18\x04 \x01(\x03R\rlimitMillicpu\x120\n" +
	"\x14request_memory_bytes\x18\x05 \x01(\x03R\x12requestMemoryBytes\x12,\n" +
	"\x12limit_memory_bytes\x18\x06 \x01(\x03R\x10limitMemoryBytes\"\xbd\x02\n" +
	"\x11WorkspaceContract\x122\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1e.ani.training.v1.WorkspaceModeR\x04mode\x12#\n" +
	"\rstorage_class\x18\x02 \x01(\tR\fstorageClass\x12%\n" +
	"\x0ecapacity_bytes\x18\x03 \x01(\x03R\rcapacityBytes\x12#\n" +
	"\rinput_subpath\x18\x04 \x01(\tR\finputSubpath\x12)\n" +
	"\x10training_subpath\x18\x05 \x01(\tR\x0ftrainingSubpath\x12'\n" +
	"\x0freports_subpath\x18\x06 \x01(\tR\x0ereportsSubpath\x12/\n" +
	"\x13publication_subpath\x18\a \x01(\tR\x12publicationSubpath\"\xec\x02\n" +
	"\fWorkspaceRef\x122\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1e.ani.training.v1.WorkspaceModeR\x04mode\x12%\n" +
	"\x0enamespace_name\x18\x02 \x01(\tR\rnamespaceName\x12#\n" +
	"\rnamespace_uid\x18\x03 \x01(\tR\fnamespaceUid\x12\x19\n" +
	"\bpvc_name\x18\x04 \x01(\tR\apvcName\x12\x17\n" +
	"\apvc_uid\x18\x05 \x01(\tR\x06pvcUid\x12#\n" +
	"\rinput_subpath\x18\x06 \x01(\tR\finputSubpath\x12)\n" +
	"\x10training_subpath\x18\a \x01(\tR\x0ftrainingSubpath\x12'\n" +
	"\x0freports_subpath\x18\b \x01(\tR\x0ereportsSubpath\x12/\n" +
	"\x13publication_subpath\x18\t \x01(\tR\x12publicationSubpath\"\x8a\x01\n" +
	"\x0eRequiredOutput\x12-\n" +
	"\x04role\x18\x01 \x01(\x0e2\x19.ani.training.v1.FileRoleR\x04role\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\x12$\n" +
	"\x0emax_size_bytes\x18\x03 \x01(\x03R\fmaxSizeBytes\"\xfb\x02\n" +
	"\x0eOutputContract\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12<\n" +
	"\voutput_kind\x18\x02 \x01(\x0e2\x1b.ani.training.v1.OutputKindR\n" +
	"outputKind\x12B\n" +
	"\rdelivery_mode\x18\x03 \x01(\x0e2\x1d.ani.training.v1.DeliveryModeR\fdeliveryMode\x12F\n" +
	"\x0erequired_files\x18\x04 \x03(\v2\x1f.ani.training.v1.RequiredOutputR\rrequiredFiles\x12$\n" +
	"\x0emax_file_count\x18\x05 \x01(\rR\fmaxFileCount\x12&\n" +
	"\x0fmax_total_bytes\x18\x06 \x01(\x03R\rmaxTotalBytes\x12*\n" +
	"\x11create_tar_bundle\x18\a \x01(\bR\x0fcreateTarBundle\"\x96\x01\n" +
	"\tFileEntry\x12#\n" +
	"\rrelative_path\x18\x01 \x01(\tR\frelativePath\x12-\n" +
	"\x04role\x18\x02 \x01(\x0e2\x19.ani.training.v1.FileRoleR\x04role\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"i\n" +
	"\vManifestRef\x12#\n" +
	"\rrelative_path\x18\x01 \x01(\tR\frelativePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"c\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rdecimal_value\x18\x02 \x01(\tR\fdecimalValue\x12\x17\n" +
	"\x04step\x18\x03 \x01(\x03H\x00R\x04step\x88\x01\x01B\a\n" +
	"\x05_step\"i\n" +
	"\x06LogRef\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\tR\x05logId\x12!\n" +
	"\fresource_uid\x18\x02 \x01(\tR\vresourceUid\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\"\xe1\x04\n" +
	"\rTrainingInput\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12>\n" +
	"\bidentity\x18\x02 \x01(\v2\".ani.training.v1.ExecutionIdentityR\bidentity\x12/\n" +
	"\x05input\x18\x03 \x01(\v2\x19.ani.training.v1.InputRefR\x05input\x12I\n" +
	"\x11prepared_manifest\x18\x04 \x01(\v2\x1c.ani.training.v1.ManifestRefR\x10preparedManifest\x125\n" +
	"\aprogram\x18\x05 \x01(\v2\x1b.ani.training.v1.ProgramRefR\aprogram\x125\n" +
	"\aruntime\x18\x06 \x01(\v2\x1b.ani.training.v1.RuntimeRefR\aruntime\x12;\n" +
	"\tresources\x18\a \x01(\v2\x1d.ani.training.v1.CPUResourcesR\tresources\x12;\n" +
	"\tworkspace\x18\b \x01(\v2\x1d.ani.training.v1.WorkspaceRefR\tworkspace\x12H\n" +
	"\x0foutput_contract\x18\t \x01(\v2\x1f.ani.training.v1.OutputContractR\x0eoutputContract\x12;\n" +
	"\vdeadline_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deadlineAt\"\xdf\x05\n" +
	"\x0eTrainingResult\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12>\n" +
	"\bidentity\x18\x02 \x01(\v2\".ani.training.v1.ExecutionIdentityR\bidentity\x12:\n" +
	"\aoutcome\x18\x03 \x01(\x0e2 .ani.training.v1.TrainingOutcomeR\aoutcome\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12<\n" +
	"\voutput_kind\x18\x05 \x01(\x0e2\x1b.ani.training.v1.OutputKindR\n" +
	"outputKind\x12K\n" +
	"\rstorage_state\x18\x06 \x01(\x0e2&.ani.training.v1.CandidateStorageStateR\fstorageState\x12;\n" +
	"\tworkspace\x18\a \x01(\v2\x1d.ani.training.v1.WorkspaceRefR\tworkspace\x120\n" +
	"\x14relative_output_path\x18\b \x01(\tR\x12relativeOutputPath\x120\n" +
	"\x05files\x18\t \x03(\v2\x1a.ani.training.v1.FileEntryR\x05files\x128\n" +
	"\bmanifest\x18\n" +
	" \x01(\v2\x1c.ani.training.v1.ManifestRefR\bmanifest\x121\n" +
	"\ametrics\x18\v \x03(\v2\x17.ani.training.v1.MetricR\ametrics\x12+\n" +
	"\x04logs\x18\f \x03(\v2\x17.ani.training.v1.LogRefR\x04logs\x12%\n" +
	"\x0efailure_reason\x18\r \x01(\tR\rfailureReason*T\n" +
	"\rExecutionKind\x12\x1e\n" +
	"\x1aEXECUTION_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fEXECUTION_KIND_GENERAL_TRAINING\x10\x01*O\n" +
	"\fDeliveryMode\x12\x1d\n" +
	"\x19DELIVERY_MODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cDELIVERY_MODE_SAVE_ARTIFACTS\x10\x01*E\n" +
	"\n" +
	"OutputKind\x12\x1b\n" +
	"\x17OUTPUT_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16OUTPUT_KIND_CHECKPOINT\x10\x01*p\n" +
	"\x0fTrainingOutcome\x12 \n" +
	"\x1cTRAINING_OUTCOME_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRAINING_OUTCOME_SUCCEEDED\x10\x01\x12\x1b\n" +
	"\x17TRAINING_OUTCOME_FAILED\x10\x02*l\n" +
	"\x15CandidateStorageState\x12'\n" +
	"#CANDIDATE_STORAGE_STATE_UNSPECIFIED\x10\x00\x12*\n" +
	"&CANDIDATE_STORAGE_STATE_WORKSPACE_ONLY\x10\x01*w\n" +
	"\rWorkspaceMode\x12\x1e\n" +
	"\x1aWORKSPACE_MODE_UNSPECIFIED\x10\x00\x12$\n" +
	" WORKSPACE_MODE_KFP_RUN_WORKSPACE\x10\x01\x12 \n" +
	"\x1cWORKSPACE_MODE_EXECUTION_PVC\x10\x02*\xdc\x01\n" +
	"\bFileRole\x12\x19\n" +
	"\x15FILE_ROLE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FILE_ROLE_CHECKPOINT\x10\x01\x12\x1a\n" +
	"\x16FILE_ROLE_MODEL_CONFIG\x10\x02\x12\x15\n" +
	"\x11FILE_ROLE_METRICS\x10\x03\x12\x15\n" +
	"\x11FILE_ROLE_SUMMARY\x10\x04\x12\x1c\n" +
	"\x18FILE_ROLE_INPUT_MANIFEST\x10\x05\x12 \n" +
	"\x1cFILE_ROLE_EXECUTION_MANIFEST\x10\x06\x12\x11\n" +
	"\rFILE_ROLE_LOG\x10\aBNZLgithub.com/zhangzhe-ctrl/ani-modeldev-service/api/ani/training/v1;trainingv1b\x06proto3"

var (
	file_ani_training_v1_training_proto_rawDescOnce sync.Once
	file_ani_training_v1_training_proto_rawDescData []byte
)

func file_ani_training_v1_training_proto_rawDescGZIP() []byte {
	file_ani_training_v1_training_proto_rawDescOnce.Do(func() {
		file_ani_training_v1_training_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ani_training_v1_training_proto_rawDesc), len(file_ani_training_v1_training_proto_rawDesc)))
	})
	return file_ani_training_v1_training_proto_rawDescData
}

var file_ani_training_v1_training_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_ani_training_v1_training_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ani_training_v1_training_proto_goTypes = []any{
	(ExecutionKind)(0),            // 0: ani.training.v1.ExecutionKind
	(DeliveryMode)(0),             // 1: ani.training.v1.DeliveryMode
	(OutputKind)(0),               // 2: ani.training.v1.OutputKind
	(TrainingOutcome)(0),          // 3: ani.training.v1.TrainingOutcome
	(CandidateStorageState)(0),    // 4: ani.training.v1.CandidateStorageState
	(WorkspaceMode)(0),            // 5: ani.training.v1.WorkspaceMode
	(FileRole)(0),                 // 6: ani.training.v1.FileRole
	(*Parameter)(nil),             // 7: ani.training.v1.Parameter
	(*ExecutionIdentity)(nil),     // 8: ani.training.v1.ExecutionIdentity
	(*FixedObjectRef)(nil),        // 9: ani.training.v1.FixedObjectRef
	(*InputRef)(nil),              // 10: ani.training.v1.InputRef
	(*RuntimeRef)(nil),            // 11: ani.training.v1.RuntimeRef
	(*ProgramRef)(nil),            // 12: ani.training.v1.ProgramRef
	(*CPUResources)(nil),          // 13: ani.training.v1.CPUResources
	(*WorkspaceContract)(nil),     // 14: ani.training.v1.WorkspaceContract
	(*WorkspaceRef)(nil),          // 15: ani.training.v1.WorkspaceRef
	(*RequiredOutput)(nil),        // 16: ani.training.v1.RequiredOutput
	(*OutputContract)(nil),        // 17: ani.training.v1.OutputContract
	(*FileEntry)(nil),             // 18: ani.training.v1.FileEntry
	(*ManifestRef)(nil),           // 19: ani.training.v1.ManifestRef
	(*Metric)(nil),                // 20: ani.training.v1.Metric
	(*LogRef)(nil),                // 21: ani.training.v1.LogRef
	(*TrainingInput)(nil),         // 22: ani.training.v1.TrainingInput
	(*TrainingResult)(nil),        // 23: ani.training.v1.TrainingResult
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_ani_training_v1_training_proto_depIdxs = []int32{
	9,  // 0: ani.training.v1.InputRef.object:type_name -> ani.training.v1.FixedObjectRef
	7,  // 1: ani.training.v1.ProgramRef.resolved_parameters:type_name -> ani.training.v1.Parameter
	5,  // 2: ani.training.v1.WorkspaceContract.mode:type_name -> ani.training.v1.WorkspaceMode
	5,  // 3: ani.training.v1.WorkspaceRef.mode:type_name -> ani.training.v1.WorkspaceMode
	6,  // 4: ani.training.v1.RequiredOutput.role:type_name -> ani.training.v1.FileRole
	2,  // 5: ani.training.v1.OutputContract.output_kind:type_name -> ani.training.v1.OutputKind
	1,  // 6: ani.training.v1.OutputContract.delivery_mode:type_name -> ani.training.v1.DeliveryMode
	16, // 7: ani.training.v1.OutputContract.required_files:type_name -> ani.training.v1.RequiredOutput
	6,  // 8: ani.training.v1.FileEntry.role:type_name -> ani.training.v1.FileRole
	8,  // 9: ani.training.v1.TrainingInput.identity:type_name -> ani.training.v1.ExecutionIdentity
	10, // 10: ani.training.v1.TrainingInput.input:type_name -> ani.training.v1.InputRef
	19, // 11: ani.training.v1.TrainingInput.prepared_manifest:type_name -> ani.training.v1.ManifestRef
	12, // 12: ani.training.v1.TrainingInput.program:type_name -> ani.training.v1.ProgramRef
	11, // 13: ani.training.v1.TrainingInput.runtime:type_name -> ani.training.v1.RuntimeRef
	13, // 14: ani.training.v1.TrainingInput.resources:type_name -> ani.training.v1.CPUResources
	15, // 15: ani.training.v1.TrainingInput.workspace:type_name -> ani.training.v1.WorkspaceRef
	17, // 16: ani.training.v1.TrainingInput.output_contract:type_name -> ani.training.v1.OutputContract
	24, // 17: ani.training.v1.TrainingInput.deadline_at:type_name -> google.protobuf.Timestamp
	8,  // 18: ani.training.v1.TrainingResult.identity:type_name -> ani.training.v1.ExecutionIdentity
	3,  // 19: ani.training.v1.TrainingResult.outcome:type_name -> ani.training.v1.TrainingOutcome
	24, // 20: ani.training.v1.TrainingResult.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 21: ani.training.v1.TrainingResult.output_kind:type_name -> ani.training.v1.OutputKind
	4,  // 22: ani.training.v1.TrainingResult.storage_state:type_name -> ani.training.v1.CandidateStorageState
	15, // 23: ani.training.v1.TrainingResult.workspace:type_name -> ani.training.v1.WorkspaceRef
	18, // 24: ani.training.v1.TrainingResult.files:type_name -> ani.training.v1.FileEntry
	19, // 25: ani.training.v1.TrainingResult.manifest:type_name -> ani.training.v1.ManifestRef
	20, // 26: ani.training.v1.TrainingResult.metrics:type_name -> ani.training.v1.Metric
	21, // 27: ani.training.v1.TrainingResult.logs:type_name -> ani.training.v1.LogRef
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_ani_training_v1_training_proto_init() }
func file_ani_training_v1_training_proto_init() {
	if File_ani_training_v1_training_proto != nil {
		return
	}
	file_ani_training_v1_training_proto_msgTypes[0].OneofWrappers = []any{
		(*Parameter_StringValue)(nil),
		(*Parameter_IntegerValue)(nil),
		(*Parameter_BooleanValue)(nil),
		(*Parameter_DecimalValue)(nil),
	}
	file_ani_training_v1_training_proto_msgTypes[2].OneofWrappers = []any{
		(*FixedObjectRef_VersionId)(nil),
		(*FixedObjectRef_ImmutableCopy)(nil),
	}
	file_ani_training_v1_training_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ani_training_v1_training_proto_rawDesc), len(file_ani_training_v1_training_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ani_training_v1_training_proto_goTypes,
		DependencyIndexes: file_ani_training_v1_training_proto_depIdxs,
		EnumInfos:         file_ani_training_v1_training_proto_enumTypes,
		MessageInfos:      file_ani_training_v1_training_proto_msgTypes,
	}.Build()
	File_ani_training_v1_training_proto = out.File
	file_ani_training_v1_training_proto_goTypes = nil
	file_ani_training_v1_training_proto_depIdxs = nil
}
