// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package inputsql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ModeldevInputVersion struct {
	TenantID              pgtype.UUID
	InputVersionID        pgtype.UUID
	RequestID             pgtype.UUID
	Actor                 string
	RequestedAt           pgtype.Timestamptz
	StorageConnectionID   string
	Bucket                string
	ApprovedPrefix        string
	ObjectKey             string
	ObjectVersionID       string
	SizeBytes             int64
	Sha256                string
	State                 string
	CredentialReference   string
	VerifiedAt            pgtype.Timestamptz
	VerifiedSchemaVersion pgtype.Text
	VerifiedRowCount      pgtype.Int4
	VerifiedFeatureCount  pgtype.Int4
	FailureCode           pgtype.Text
	FailureObservedAt     pgtype.Timestamptz
}
