// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package inputsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInputVersion = `-- name: GetInputVersion :one
SELECT tenant_id, input_version_id, request_id, actor, requested_at, storage_connection_id, bucket, approved_prefix, object_key, object_version_id, size_bytes, sha256, state, credential_reference, verified_at, verified_schema_version, verified_row_count, verified_feature_count FROM modeldev_input_versions
WHERE tenant_id = $1::uuid
  AND input_version_id = $2::uuid
`

type GetInputVersionParams struct {
	TenantID       pgtype.UUID
	InputVersionID pgtype.UUID
}

func (q *Queries) GetInputVersion(ctx context.Context, arg GetInputVersionParams) (ModeldevInputVersion, error) {
	row := q.db.QueryRow(ctx, getInputVersion, arg.TenantID, arg.InputVersionID)
	var i ModeldevInputVersion
	err := row.Scan(
		&i.TenantID,
		&i.InputVersionID,
		&i.RequestID,
		&i.Actor,
		&i.RequestedAt,
		&i.StorageConnectionID,
		&i.Bucket,
		&i.ApprovedPrefix,
		&i.ObjectKey,
		&i.ObjectVersionID,
		&i.SizeBytes,
		&i.Sha256,
		&i.State,
		&i.CredentialReference,
		&i.VerifiedAt,
		&i.VerifiedSchemaVersion,
		&i.VerifiedRowCount,
		&i.VerifiedFeatureCount,
	)
	return i, err
}

const insertFrozenImport = `-- name: InsertFrozenImport :one
INSERT INTO modeldev_input_versions (
    tenant_id, input_version_id, request_id, actor, requested_at,
    storage_connection_id, bucket, approved_prefix, credential_reference, object_key,
    object_version_id, size_bytes, sha256
) VALUES (
    $1::uuid, $2::uuid,
    $3::uuid, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13
)
ON CONFLICT DO NOTHING
RETURNING tenant_id, input_version_id, request_id, actor, requested_at, storage_connection_id, bucket, approved_prefix, object_key, object_version_id, size_bytes, sha256, state, credential_reference, verified_at, verified_schema_version, verified_row_count, verified_feature_count
`

type InsertFrozenImportParams struct {
	TenantID            pgtype.UUID
	InputVersionID      pgtype.UUID
	RequestID           pgtype.UUID
	Actor               string
	RequestedAt         pgtype.Timestamptz
	StorageConnectionID string
	Bucket              string
	ApprovedPrefix      string
	CredentialReference string
	ObjectKey           string
	ObjectVersionID     string
	SizeBytes           int64
	Sha256              string
}

func (q *Queries) InsertFrozenImport(ctx context.Context, arg InsertFrozenImportParams) (ModeldevInputVersion, error) {
	row := q.db.QueryRow(ctx, insertFrozenImport,
		arg.TenantID,
		arg.InputVersionID,
		arg.RequestID,
		arg.Actor,
		arg.RequestedAt,
		arg.StorageConnectionID,
		arg.Bucket,
		arg.ApprovedPrefix,
		arg.CredentialReference,
		arg.ObjectKey,
		arg.ObjectVersionID,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i ModeldevInputVersion
	err := row.Scan(
		&i.TenantID,
		&i.InputVersionID,
		&i.RequestID,
		&i.Actor,
		&i.RequestedAt,
		&i.StorageConnectionID,
		&i.Bucket,
		&i.ApprovedPrefix,
		&i.ObjectKey,
		&i.ObjectVersionID,
		&i.SizeBytes,
		&i.Sha256,
		&i.State,
		&i.CredentialReference,
		&i.VerifiedAt,
		&i.VerifiedSchemaVersion,
		&i.VerifiedRowCount,
		&i.VerifiedFeatureCount,
	)
	return i, err
}

const lockInputVersion = `-- name: LockInputVersion :one
SELECT tenant_id, input_version_id, request_id, actor, requested_at, storage_connection_id, bucket, approved_prefix, object_key, object_version_id, size_bytes, sha256, state, credential_reference, verified_at, verified_schema_version, verified_row_count, verified_feature_count FROM modeldev_input_versions
WHERE tenant_id = $1::uuid
  AND input_version_id = $2::uuid
FOR UPDATE
`

type LockInputVersionParams struct {
	TenantID       pgtype.UUID
	InputVersionID pgtype.UUID
}

func (q *Queries) LockInputVersion(ctx context.Context, arg LockInputVersionParams) (ModeldevInputVersion, error) {
	row := q.db.QueryRow(ctx, lockInputVersion, arg.TenantID, arg.InputVersionID)
	var i ModeldevInputVersion
	err := row.Scan(
		&i.TenantID,
		&i.InputVersionID,
		&i.RequestID,
		&i.Actor,
		&i.RequestedAt,
		&i.StorageConnectionID,
		&i.Bucket,
		&i.ApprovedPrefix,
		&i.ObjectKey,
		&i.ObjectVersionID,
		&i.SizeBytes,
		&i.Sha256,
		&i.State,
		&i.CredentialReference,
		&i.VerifiedAt,
		&i.VerifiedSchemaVersion,
		&i.VerifiedRowCount,
		&i.VerifiedFeatureCount,
	)
	return i, err
}

const recordVerifiedCSV = `-- name: RecordVerifiedCSV :one
UPDATE modeldev_input_versions
SET state = 'READY',
    verified_at = $1,
    verified_schema_version = $2,
    verified_row_count = $3,
    verified_feature_count = $4
WHERE tenant_id = $5::uuid
  AND input_version_id = $6::uuid
  AND request_id = $7::uuid
  AND state = 'VALIDATING'
RETURNING tenant_id, input_version_id, request_id, actor, requested_at, storage_connection_id, bucket, approved_prefix, object_key, object_version_id, size_bytes, sha256, state, credential_reference, verified_at, verified_schema_version, verified_row_count, verified_feature_count
`

type RecordVerifiedCSVParams struct {
	VerifiedAt            pgtype.Timestamptz
	VerifiedSchemaVersion pgtype.Text
	VerifiedRowCount      pgtype.Int4
	VerifiedFeatureCount  pgtype.Int4
	TenantID              pgtype.UUID
	InputVersionID        pgtype.UUID
	RequestID             pgtype.UUID
}

func (q *Queries) RecordVerifiedCSV(ctx context.Context, arg RecordVerifiedCSVParams) (ModeldevInputVersion, error) {
	row := q.db.QueryRow(ctx, recordVerifiedCSV,
		arg.VerifiedAt,
		arg.VerifiedSchemaVersion,
		arg.VerifiedRowCount,
		arg.VerifiedFeatureCount,
		arg.TenantID,
		arg.InputVersionID,
		arg.RequestID,
	)
	var i ModeldevInputVersion
	err := row.Scan(
		&i.TenantID,
		&i.InputVersionID,
		&i.RequestID,
		&i.Actor,
		&i.RequestedAt,
		&i.StorageConnectionID,
		&i.Bucket,
		&i.ApprovedPrefix,
		&i.ObjectKey,
		&i.ObjectVersionID,
		&i.SizeBytes,
		&i.Sha256,
		&i.State,
		&i.CredentialReference,
		&i.VerifiedAt,
		&i.VerifiedSchemaVersion,
		&i.VerifiedRowCount,
		&i.VerifiedFeatureCount,
	)
	return i, err
}
