// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package inputsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInputVersion = `-- name: GetInputVersion :one
SELECT tenant_id, input_version_id, request_id, actor, requested_at, storage_connection_id, bucket, approved_prefix, object_key, object_version_id, size_bytes, sha256, state FROM modeldev_input_versions
WHERE tenant_id = $1::uuid
  AND input_version_id = $2::uuid
`

type GetInputVersionParams struct {
	TenantID       pgtype.UUID
	InputVersionID pgtype.UUID
}

func (q *Queries) GetInputVersion(ctx context.Context, arg GetInputVersionParams) (ModeldevInputVersion, error) {
	row := q.db.QueryRow(ctx, getInputVersion, arg.TenantID, arg.InputVersionID)
	var i ModeldevInputVersion
	err := row.Scan(
		&i.TenantID,
		&i.InputVersionID,
		&i.RequestID,
		&i.Actor,
		&i.RequestedAt,
		&i.StorageConnectionID,
		&i.Bucket,
		&i.ApprovedPrefix,
		&i.ObjectKey,
		&i.ObjectVersionID,
		&i.SizeBytes,
		&i.Sha256,
		&i.State,
	)
	return i, err
}

const insertFrozenImport = `-- name: InsertFrozenImport :one
INSERT INTO modeldev_input_versions (
    tenant_id, input_version_id, request_id, actor, requested_at,
    storage_connection_id, bucket, approved_prefix, object_key,
    object_version_id, size_bytes, sha256
) VALUES (
    $1::uuid, $2::uuid,
    $3::uuid, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12
)
ON CONFLICT DO NOTHING
RETURNING tenant_id, input_version_id, request_id, actor, requested_at, storage_connection_id, bucket, approved_prefix, object_key, object_version_id, size_bytes, sha256, state
`

type InsertFrozenImportParams struct {
	TenantID            pgtype.UUID
	InputVersionID      pgtype.UUID
	RequestID           pgtype.UUID
	Actor               string
	RequestedAt         pgtype.Timestamptz
	StorageConnectionID string
	Bucket              string
	ApprovedPrefix      string
	ObjectKey           string
	ObjectVersionID     string
	SizeBytes           int64
	Sha256              string
}

func (q *Queries) InsertFrozenImport(ctx context.Context, arg InsertFrozenImportParams) (ModeldevInputVersion, error) {
	row := q.db.QueryRow(ctx, insertFrozenImport,
		arg.TenantID,
		arg.InputVersionID,
		arg.RequestID,
		arg.Actor,
		arg.RequestedAt,
		arg.StorageConnectionID,
		arg.Bucket,
		arg.ApprovedPrefix,
		arg.ObjectKey,
		arg.ObjectVersionID,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i ModeldevInputVersion
	err := row.Scan(
		&i.TenantID,
		&i.InputVersionID,
		&i.RequestID,
		&i.Actor,
		&i.RequestedAt,
		&i.StorageConnectionID,
		&i.Bucket,
		&i.ApprovedPrefix,
		&i.ObjectKey,
		&i.ObjectVersionID,
		&i.SizeBytes,
		&i.Sha256,
		&i.State,
	)
	return i, err
}
