// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package lifecyclesql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceRuntimeClose = `-- name: AdvanceRuntimeClose :one
UPDATE modeldev_execution_identities SET close_generation = close_generation + 1
WHERE tenant_id = $1::uuid AND execution_id = $2::uuid
    AND close_generation < 18446744073709551615
RETURNING close_generation::text
`

type AdvanceRuntimeCloseParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) AdvanceRuntimeClose(ctx context.Context, arg AdvanceRuntimeCloseParams) (string, error) {
	row := q.db.QueryRow(ctx, advanceRuntimeClose, arg.TenantID, arg.ExecutionID)
	var close_generation string
	err := row.Scan(&close_generation)
	return close_generation, err
}

const advanceRuntimeRevision = `-- name: AdvanceRuntimeRevision :one
UPDATE modeldev_execution_identities SET owner_revision = owner_revision + 1
WHERE tenant_id = $1::uuid AND execution_id = $2::uuid
    AND owner_revision < 18446744073709551615
RETURNING owner_revision::text
`

type AdvanceRuntimeRevisionParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) AdvanceRuntimeRevision(ctx context.Context, arg AdvanceRuntimeRevisionParams) (string, error) {
	row := q.db.QueryRow(ctx, advanceRuntimeRevision, arg.TenantID, arg.ExecutionID)
	var owner_revision string
	err := row.Scan(&owner_revision)
	return owner_revision, err
}

const getRuntimeFacts = `-- name: GetRuntimeFacts :one
SELECT facts FROM modeldev_execution_runtimes
WHERE tenant_id = $1::uuid AND execution_id = $2::uuid
`

type GetRuntimeFactsParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) GetRuntimeFacts(ctx context.Context, arg GetRuntimeFactsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRuntimeFacts, arg.TenantID, arg.ExecutionID)
	var facts []byte
	err := row.Scan(&facts)
	return facts, err
}

const getRuntimeIdentity = `-- name: GetRuntimeIdentity :one
SELECT close_generation::text AS close_generation, owner_revision::text AS owner_revision,
    clock_timestamp()::timestamptz AS database_now
FROM modeldev_execution_identities
WHERE tenant_id = $1::uuid AND execution_id = $2::uuid
`

type GetRuntimeIdentityParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

type GetRuntimeIdentityRow struct {
	CloseGeneration string
	OwnerRevision   string
	DatabaseNow     pgtype.Timestamptz
}

// Called after the shared lock for writers, or in a repeatable-read snapshot.
func (q *Queries) GetRuntimeIdentity(ctx context.Context, arg GetRuntimeIdentityParams) (GetRuntimeIdentityRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeIdentity, arg.TenantID, arg.ExecutionID)
	var i GetRuntimeIdentityRow
	err := row.Scan(&i.CloseGeneration, &i.OwnerRevision, &i.DatabaseNow)
	return i, err
}

const lockRuntimeIdentity = `-- name: LockRuntimeIdentity :one
SELECT tenant_id, execution_id
FROM modeldev_execution_identities
WHERE tenant_id = $1::uuid AND execution_id = $2::uuid
FOR UPDATE
`

type LockRuntimeIdentityParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

type LockRuntimeIdentityRow struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) LockRuntimeIdentity(ctx context.Context, arg LockRuntimeIdentityParams) (LockRuntimeIdentityRow, error) {
	row := q.db.QueryRow(ctx, lockRuntimeIdentity, arg.TenantID, arg.ExecutionID)
	var i LockRuntimeIdentityRow
	err := row.Scan(&i.TenantID, &i.ExecutionID)
	return i, err
}

const runtimeSchemaAvailable = `-- name: RuntimeSchemaAvailable :one
SELECT to_regclass('modeldev_execution_runtimes') IS NOT NULL AS available
`

// The fixed 0012 migration reader predates the runtime schema. Check before
// querying it; an undefined-table error would abort the aggregate transaction.
func (q *Queries) RuntimeSchemaAvailable(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, runtimeSchemaAvailable)
	var available interface{}
	err := row.Scan(&available)
	return available, err
}

const saveRuntimeFacts = `-- name: SaveRuntimeFacts :execrows
INSERT INTO modeldev_execution_runtimes (
    tenant_id, execution_id, operation_id, spec_hash, facts,
    training_name, training_request_sha256, training_uid, publication_id,
    close_generation, close_reason, close_requested_at, closed_at
)
SELECT i.tenant_id, i.execution_id, i.operation_id, i.spec_hash, $1::jsonb,
    $2::text, $3::text,
    $4::text, $5::uuid,
    $6::numeric, $7::text,
    $8::timestamptz, $9::timestamptz
FROM modeldev_execution_identities AS i
WHERE i.tenant_id = $10::uuid AND i.execution_id = $11::uuid
  AND (NOT $12::boolean OR
       (i.close_generation = 0 AND clock_timestamp() < $13::timestamptz))
ON CONFLICT (tenant_id, execution_id) DO UPDATE SET
    facts = EXCLUDED.facts,
    training_name = EXCLUDED.training_name,
    training_request_sha256 = EXCLUDED.training_request_sha256,
    training_uid = EXCLUDED.training_uid,
    publication_id = EXCLUDED.publication_id,
    close_generation = EXCLUDED.close_generation,
    close_reason = EXCLUDED.close_reason,
    close_requested_at = EXCLUDED.close_requested_at,
    closed_at = EXCLUDED.closed_at
`

type SaveRuntimeFactsParams struct {
	Facts                 []byte
	TrainingName          pgtype.Text
	TrainingRequestSha256 pgtype.Text
	TrainingUid           pgtype.Text
	PublicationID         pgtype.UUID
	CloseGeneration       pgtype.Numeric
	CloseReason           pgtype.Text
	CloseRequestedAt      pgtype.Timestamptz
	ClosedAt              pgtype.Timestamptz
	TenantID              pgtype.UUID
	ExecutionID           pgtype.UUID
	RequireCreationOpen   bool
	DeadlineAt            pgtype.Timestamptz
}

// The shared close fence and DB deadline are checked again in the statement
// that persists a new workspace or training creation intent.
func (q *Queries) SaveRuntimeFacts(ctx context.Context, arg SaveRuntimeFactsParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveRuntimeFacts,
		arg.Facts,
		arg.TrainingName,
		arg.TrainingRequestSha256,
		arg.TrainingUid,
		arg.PublicationID,
		arg.CloseGeneration,
		arg.CloseReason,
		arg.CloseRequestedAt,
		arg.ClosedAt,
		arg.TenantID,
		arg.ExecutionID,
		arg.RequireCreationOpen,
		arg.DeadlineAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
