// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/v1/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Server *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Absent keeps the unready runtime shell. Presence requires every input and
	// assembles the real Governance command listener without plaintext fallback.
	Command       *GovernanceCommand `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_v1_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetCommand() *GovernanceCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type GovernanceCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A mounted secret file containing the restricted runtime PostgreSQL URL.
	// Connection values and private keys are never stored in ordinary YAML.
	DatabaseUrlFile   string `protobuf:"bytes,1,opt,name=database_url_file,json=databaseUrlFile,proto3" json:"database_url_file,omitempty"`
	ClientCaFile      string `protobuf:"bytes,2,opt,name=client_ca_file,json=clientCaFile,proto3" json:"client_ca_file,omitempty"`
	CertificateFile   string `protobuf:"bytes,3,opt,name=certificate_file,json=certificateFile,proto3" json:"certificate_file,omitempty"`
	PrivateKeyFile    string `protobuf:"bytes,4,opt,name=private_key_file,json=privateKeyFile,proto3" json:"private_key_file,omitempty"`
	GovernanceDnsName string `protobuf:"bytes,5,opt,name=governance_dns_name,json=governanceDnsName,proto3" json:"governance_dns_name,omitempty"`
	// Presence enables candidate resolution from explicitly pinned mounted
	// materials. It does not establish environment or business readiness.
	AdmissionResolution *AdmissionResolution `protobuf:"bytes,6,opt,name=admission_resolution,json=admissionResolution,proto3" json:"admission_resolution,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GovernanceCommand) Reset() {
	*x = GovernanceCommand{}
	mi := &file_conf_v1_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernanceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceCommand) ProtoMessage() {}

func (x *GovernanceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceCommand.ProtoReflect.Descriptor instead.
func (*GovernanceCommand) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{1}
}

func (x *GovernanceCommand) GetDatabaseUrlFile() string {
	if x != nil {
		return x.DatabaseUrlFile
	}
	return ""
}

func (x *GovernanceCommand) GetClientCaFile() string {
	if x != nil {
		return x.ClientCaFile
	}
	return ""
}

func (x *GovernanceCommand) GetCertificateFile() string {
	if x != nil {
		return x.CertificateFile
	}
	return ""
}

func (x *GovernanceCommand) GetPrivateKeyFile() string {
	if x != nil {
		return x.PrivateKeyFile
	}
	return ""
}

func (x *GovernanceCommand) GetGovernanceDnsName() string {
	if x != nil {
		return x.GovernanceDnsName
	}
	return ""
}

func (x *GovernanceCommand) GetAdmissionResolution() *AdmissionResolution {
	if x != nil {
		return x.AdmissionResolution
	}
	return nil
}

type AdmissionResolution struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CatalogueDirectory string                 `protobuf:"bytes,1,opt,name=catalogue_directory,json=catalogueDirectory,proto3" json:"catalogue_directory,omitempty"`
	FactsFiles         []*AdmissionFactsFile  `protobuf:"bytes,2,rep,name=facts_files,json=factsFiles,proto3" json:"facts_files,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdmissionResolution) Reset() {
	*x = AdmissionResolution{}
	mi := &file_conf_v1_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionResolution) ProtoMessage() {}

func (x *AdmissionResolution) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionResolution.ProtoReflect.Descriptor instead.
func (*AdmissionResolution) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{2}
}

func (x *AdmissionResolution) GetCatalogueDirectory() string {
	if x != nil {
		return x.CatalogueDirectory
	}
	return ""
}

func (x *AdmissionResolution) GetFactsFiles() []*AdmissionFactsFile {
	if x != nil {
		return x.FactsFiles
	}
	return nil
}

type AdmissionFactsFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmissionFactsFile) Reset() {
	*x = AdmissionFactsFile{}
	mi := &file_conf_v1_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionFactsFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionFactsFile) ProtoMessage() {}

func (x *AdmissionFactsFile) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionFactsFile.ProtoReflect.Descriptor instead.
func (*AdmissionFactsFile) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{3}
}

func (x *AdmissionFactsFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AdmissionFactsFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type Server struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Grpc            *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Admin           *Server_Admin          `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	ShutdownTimeout *durationpb.Duration   `protobuf:"bytes,3,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_v1_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetAdmin() *Server_Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *Server) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_v1_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_Admin) Reset() {
	*x = Server_Admin{}
	mi := &file_conf_v1_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Admin) ProtoMessage() {}

func (x *Server_Admin) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Admin.ProtoReflect.Descriptor instead.
func (*Server_Admin) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Server_Admin) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_Admin) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_Admin) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_conf_v1_conf_proto protoreflect.FileDescriptor

const file_conf_v1_conf_proto_rawDesc = "" +
	"\n" +
	"\x12conf/v1/conf.proto\x12\aconf.v1\x1a\x1egoogle/protobuf/duration.proto\"j\n" +
	"\tBootstrap\x12'\n" +
	"\x06server\x18\x01 \x01(\v2\x0f.conf.v1.ServerR\x06server\x124\n" +
	"\acommand\x18\x02 \x01(\v2\x1a.conf.v1.GovernanceCommandR\acommand\"\xbb\x02\n" +
	"\x11GovernanceCommand\x12*\n" +
	"\x11database_url_file\x18\x01 \x01(\tR\x0fdatabaseUrlFile\x12$\n" +
	"\x0eclient_ca_file\x18\x02 \x01(\tR\fclientCaFile\x12)\n" +
	"\x10certificate_file\x18\x03 \x01(\tR\x0fcertificateFile\x12(\n" +
	"\x10private_key_file\x18\x04 \x01(\tR\x0eprivateKeyFile\x12.\n" +
	"\x13governance_dns_name\x18\x05 \x01(\tR\x11governanceDnsName\x12O\n" +
	"\x14admission_resolution\x18\x06 \x01(\v2\x1c.conf.v1.AdmissionResolutionR\x13admissionResolution\"\x84\x01\n" +
	"\x13AdmissionResolution\x12/\n" +
	"\x13catalogue_directory\x18\x01 \x01(\tR\x12catalogueDirectory\x12<\n" +
	"\vfacts_files\x18\x02 \x03(\v2\x1b.conf.v1.AdmissionFactsFileR\n" +
	"factsFiles\"@\n" +
	"\x12AdmissionFactsFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"\xfc\x02\n" +
	"\x06Server\x12(\n" +
	"\x04grpc\x18\x01 \x01(\v2\x14.conf.v1.Server.GRPCR\x04grpc\x12+\n" +
	"\x05admin\x18\x02 \x01(\v2\x15.conf.v1.Server.AdminR\x05admin\x12D\n" +
	"\x10shutdown_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1aj\n" +
	"\x05Admin\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeoutBEZCgithub.com/zhangzhe-ctrl/ani-modeldev-service/internal/conf/v1;confb\x06proto3"

var (
	file_conf_v1_conf_proto_rawDescOnce sync.Once
	file_conf_v1_conf_proto_rawDescData []byte
)

func file_conf_v1_conf_proto_rawDescGZIP() []byte {
	file_conf_v1_conf_proto_rawDescOnce.Do(func() {
		file_conf_v1_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_v1_conf_proto_rawDesc), len(file_conf_v1_conf_proto_rawDesc)))
	})
	return file_conf_v1_conf_proto_rawDescData
}

var file_conf_v1_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_conf_v1_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: conf.v1.Bootstrap
	(*GovernanceCommand)(nil),   // 1: conf.v1.GovernanceCommand
	(*AdmissionResolution)(nil), // 2: conf.v1.AdmissionResolution
	(*AdmissionFactsFile)(nil),  // 3: conf.v1.AdmissionFactsFile
	(*Server)(nil),              // 4: conf.v1.Server
	(*Server_GRPC)(nil),         // 5: conf.v1.Server.GRPC
	(*Server_Admin)(nil),        // 6: conf.v1.Server.Admin
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
}
var file_conf_v1_conf_proto_depIdxs = []int32{
	4, // 0: conf.v1.Bootstrap.server:type_name -> conf.v1.Server
	1, // 1: conf.v1.Bootstrap.command:type_name -> conf.v1.GovernanceCommand
	2, // 2: conf.v1.GovernanceCommand.admission_resolution:type_name -> conf.v1.AdmissionResolution
	3, // 3: conf.v1.AdmissionResolution.facts_files:type_name -> conf.v1.AdmissionFactsFile
	5, // 4: conf.v1.Server.grpc:type_name -> conf.v1.Server.GRPC
	6, // 5: conf.v1.Server.admin:type_name -> conf.v1.Server.Admin
	7, // 6: conf.v1.Server.shutdown_timeout:type_name -> google.protobuf.Duration
	7, // 7: conf.v1.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	7, // 8: conf.v1.Server.Admin.timeout:type_name -> google.protobuf.Duration
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_conf_v1_conf_proto_init() }
func file_conf_v1_conf_proto_init() {
	if File_conf_v1_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_v1_conf_proto_rawDesc), len(file_conf_v1_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_v1_conf_proto_goTypes,
		DependencyIndexes: file_conf_v1_conf_proto_depIdxs,
		MessageInfos:      file_conf_v1_conf_proto_msgTypes,
	}.Build()
	File_conf_v1_conf_proto = out.File
	file_conf_v1_conf_proto_goTypes = nil
	file_conf_v1_conf_proto_depIdxs = nil
}
