// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/v1/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Server *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Absent keeps the unready runtime shell. Presence requires every input and
	// assembles the real Governance command listener without plaintext fallback.
	Command *GovernanceCommand `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// Presence assembles the managed execution main flow alongside command.
	Runtime       *ManagedRuntime `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_v1_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetCommand() *GovernanceCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Bootstrap) GetRuntime() *ManagedRuntime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type ManagedRuntime struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Step            *Server_GRPC             `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	CertificateFile string                   `protobuf:"bytes,2,opt,name=certificate_file,json=certificateFile,proto3" json:"certificate_file,omitempty"`
	PrivateKeyFile  string                   `protobuf:"bytes,3,opt,name=private_key_file,json=privateKeyFile,proto3" json:"private_key_file,omitempty"`
	Kubernetes      *HTTPSWorkloadConnection `protobuf:"bytes,4,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	Pipeline        *HTTPSWorkloadConnection `protobuf:"bytes,5,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	ObjectStorage   *ObjectStorageConnection `protobuf:"bytes,6,opt,name=object_storage,json=objectStorage,proto3" json:"object_storage,omitempty"`
	// JSON PipelineDispatchBinding with the tenant, complete frozen environment
	// and owner configuration. It contains no credentials and is SHA256 pinned.
	BindingFile       string               `protobuf:"bytes,7,opt,name=binding_file,json=bindingFile,proto3" json:"binding_file,omitempty"`
	BindingSha256     string               `protobuf:"bytes,8,opt,name=binding_sha256,json=bindingSha256,proto3" json:"binding_sha256,omitempty"`
	TokenAudience     string               `protobuf:"bytes,9,opt,name=token_audience,json=tokenAudience,proto3" json:"token_audience,omitempty"`
	ApiTimeout        *durationpb.Duration `protobuf:"bytes,10,opt,name=api_timeout,json=apiTimeout,proto3" json:"api_timeout,omitempty"`
	DispatchInterval  *durationpb.Duration `protobuf:"bytes,11,opt,name=dispatch_interval,json=dispatchInterval,proto3" json:"dispatch_interval,omitempty"`
	DispatchBatchSize uint32               `protobuf:"varint,12,opt,name=dispatch_batch_size,json=dispatchBatchSize,proto3" json:"dispatch_batch_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ManagedRuntime) Reset() {
	*x = ManagedRuntime{}
	mi := &file_conf_v1_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedRuntime) ProtoMessage() {}

func (x *ManagedRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedRuntime.ProtoReflect.Descriptor instead.
func (*ManagedRuntime) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{1}
}

func (x *ManagedRuntime) GetStep() *Server_GRPC {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *ManagedRuntime) GetCertificateFile() string {
	if x != nil {
		return x.CertificateFile
	}
	return ""
}

func (x *ManagedRuntime) GetPrivateKeyFile() string {
	if x != nil {
		return x.PrivateKeyFile
	}
	return ""
}

func (x *ManagedRuntime) GetKubernetes() *HTTPSWorkloadConnection {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

func (x *ManagedRuntime) GetPipeline() *HTTPSWorkloadConnection {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *ManagedRuntime) GetObjectStorage() *ObjectStorageConnection {
	if x != nil {
		return x.ObjectStorage
	}
	return nil
}

func (x *ManagedRuntime) GetBindingFile() string {
	if x != nil {
		return x.BindingFile
	}
	return ""
}

func (x *ManagedRuntime) GetBindingSha256() string {
	if x != nil {
		return x.BindingSha256
	}
	return ""
}

func (x *ManagedRuntime) GetTokenAudience() string {
	if x != nil {
		return x.TokenAudience
	}
	return ""
}

func (x *ManagedRuntime) GetApiTimeout() *durationpb.Duration {
	if x != nil {
		return x.ApiTimeout
	}
	return nil
}

func (x *ManagedRuntime) GetDispatchInterval() *durationpb.Duration {
	if x != nil {
		return x.DispatchInterval
	}
	return nil
}

func (x *ManagedRuntime) GetDispatchBatchSize() uint32 {
	if x != nil {
		return x.DispatchBatchSize
	}
	return 0
}

type HTTPSWorkloadConnection struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Endpoint string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CaFile   string                 `protobuf:"bytes,2,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	// Mounted current workload credential, never a forwarded user token.
	TokenFile     string `protobuf:"bytes,3,opt,name=token_file,json=tokenFile,proto3" json:"token_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPSWorkloadConnection) Reset() {
	*x = HTTPSWorkloadConnection{}
	mi := &file_conf_v1_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPSWorkloadConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPSWorkloadConnection) ProtoMessage() {}

func (x *HTTPSWorkloadConnection) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPSWorkloadConnection.ProtoReflect.Descriptor instead.
func (*HTTPSWorkloadConnection) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPSWorkloadConnection) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HTTPSWorkloadConnection) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *HTTPSWorkloadConnection) GetTokenFile() string {
	if x != nil {
		return x.TokenFile
	}
	return ""
}

type ObjectStorageConnection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CaFile          string                 `protobuf:"bytes,2,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	Region          string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	CredentialsFile string                 `protobuf:"bytes,4,opt,name=credentials_file,json=credentialsFile,proto3" json:"credentials_file,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	MaxObjectBytes  int64                  `protobuf:"varint,6,opt,name=max_object_bytes,json=maxObjectBytes,proto3" json:"max_object_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ObjectStorageConnection) Reset() {
	*x = ObjectStorageConnection{}
	mi := &file_conf_v1_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectStorageConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStorageConnection) ProtoMessage() {}

func (x *ObjectStorageConnection) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStorageConnection.ProtoReflect.Descriptor instead.
func (*ObjectStorageConnection) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectStorageConnection) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ObjectStorageConnection) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *ObjectStorageConnection) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ObjectStorageConnection) GetCredentialsFile() string {
	if x != nil {
		return x.CredentialsFile
	}
	return ""
}

func (x *ObjectStorageConnection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ObjectStorageConnection) GetMaxObjectBytes() int64 {
	if x != nil {
		return x.MaxObjectBytes
	}
	return 0
}

type GovernanceCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A mounted secret file containing the restricted runtime PostgreSQL URL.
	// Connection values and private keys are never stored in ordinary YAML.
	DatabaseUrlFile   string `protobuf:"bytes,1,opt,name=database_url_file,json=databaseUrlFile,proto3" json:"database_url_file,omitempty"`
	ClientCaFile      string `protobuf:"bytes,2,opt,name=client_ca_file,json=clientCaFile,proto3" json:"client_ca_file,omitempty"`
	CertificateFile   string `protobuf:"bytes,3,opt,name=certificate_file,json=certificateFile,proto3" json:"certificate_file,omitempty"`
	PrivateKeyFile    string `protobuf:"bytes,4,opt,name=private_key_file,json=privateKeyFile,proto3" json:"private_key_file,omitempty"`
	GovernanceDnsName string `protobuf:"bytes,5,opt,name=governance_dns_name,json=governanceDnsName,proto3" json:"governance_dns_name,omitempty"`
	// Presence enables candidate resolution from explicitly pinned mounted
	// materials. It does not establish environment or business readiness.
	AdmissionResolution *AdmissionResolution `protobuf:"bytes,6,opt,name=admission_resolution,json=admissionResolution,proto3" json:"admission_resolution,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GovernanceCommand) Reset() {
	*x = GovernanceCommand{}
	mi := &file_conf_v1_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernanceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceCommand) ProtoMessage() {}

func (x *GovernanceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceCommand.ProtoReflect.Descriptor instead.
func (*GovernanceCommand) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{4}
}

func (x *GovernanceCommand) GetDatabaseUrlFile() string {
	if x != nil {
		return x.DatabaseUrlFile
	}
	return ""
}

func (x *GovernanceCommand) GetClientCaFile() string {
	if x != nil {
		return x.ClientCaFile
	}
	return ""
}

func (x *GovernanceCommand) GetCertificateFile() string {
	if x != nil {
		return x.CertificateFile
	}
	return ""
}

func (x *GovernanceCommand) GetPrivateKeyFile() string {
	if x != nil {
		return x.PrivateKeyFile
	}
	return ""
}

func (x *GovernanceCommand) GetGovernanceDnsName() string {
	if x != nil {
		return x.GovernanceDnsName
	}
	return ""
}

func (x *GovernanceCommand) GetAdmissionResolution() *AdmissionResolution {
	if x != nil {
		return x.AdmissionResolution
	}
	return nil
}

type AdmissionResolution struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CatalogueDirectory string                 `protobuf:"bytes,1,opt,name=catalogue_directory,json=catalogueDirectory,proto3" json:"catalogue_directory,omitempty"`
	FactsFiles         []*AdmissionFactsFile  `protobuf:"bytes,2,rep,name=facts_files,json=factsFiles,proto3" json:"facts_files,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdmissionResolution) Reset() {
	*x = AdmissionResolution{}
	mi := &file_conf_v1_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionResolution) ProtoMessage() {}

func (x *AdmissionResolution) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionResolution.ProtoReflect.Descriptor instead.
func (*AdmissionResolution) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{5}
}

func (x *AdmissionResolution) GetCatalogueDirectory() string {
	if x != nil {
		return x.CatalogueDirectory
	}
	return ""
}

func (x *AdmissionResolution) GetFactsFiles() []*AdmissionFactsFile {
	if x != nil {
		return x.FactsFiles
	}
	return nil
}

type AdmissionFactsFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmissionFactsFile) Reset() {
	*x = AdmissionFactsFile{}
	mi := &file_conf_v1_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionFactsFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionFactsFile) ProtoMessage() {}

func (x *AdmissionFactsFile) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionFactsFile.ProtoReflect.Descriptor instead.
func (*AdmissionFactsFile) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{6}
}

func (x *AdmissionFactsFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AdmissionFactsFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type Server struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Grpc            *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Admin           *Server_Admin          `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	ShutdownTimeout *durationpb.Duration   `protobuf:"bytes,3,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_v1_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetAdmin() *Server_Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *Server) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_v1_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_Admin) Reset() {
	*x = Server_Admin{}
	mi := &file_conf_v1_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Admin) ProtoMessage() {}

func (x *Server_Admin) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Admin.ProtoReflect.Descriptor instead.
func (*Server_Admin) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{7, 1}
}

func (x *Server_Admin) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_Admin) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_Admin) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_conf_v1_conf_proto protoreflect.FileDescriptor

const file_conf_v1_conf_proto_rawDesc = "" +
	"\n" +
	"\x12conf/v1/conf.proto\x12\aconf.v1\x1a\x1egoogle/protobuf/duration.proto\"\x9d\x01\n" +
	"\tBootstrap\x12'\n" +
	"\x06server\x18\x01 \x01(\v2\x0f.conf.v1.ServerR\x06server\x124\n" +
	"\acommand\x18\x02 \x01(\v2\x1a.conf.v1.GovernanceCommandR\acommand\x121\n" +
	"\aruntime\x18\x03 \x01(\v2\x17.conf.v1.ManagedRuntimeR\aruntime\"\xfd\x04\n" +
	"\x0eManagedRuntime\x12(\n" +
	"\x04step\x18\x01 \x01(\v2\x14.conf.v1.Server.GRPCR\x04step\x12)\n" +
	"\x10certificate_file\x18\x02 \x01(\tR\x0fcertificateFile\x12(\n" +
	"\x10private_key_file\x18\x03 \x01(\tR\x0eprivateKeyFile\x12@\n" +
	"\n" +
	"kubernetes\x18\x04 \x01(\v2 .conf.v1.HTTPSWorkloadConnectionR\n" +
	"kubernetes\x12<\n" +
	"\bpipeline\x18\x05 \x01(\v2 .conf.v1.HTTPSWorkloadConnectionR\bpipeline\x12G\n" +
	"\x0eobject_storage\x18\x06 \x01(\v2 .conf.v1.ObjectStorageConnectionR\robjectStorage\x12!\n" +
	"\fbinding_file\x18\a \x01(\tR\vbindingFile\x12%\n" +
	"\x0ebinding_sha256\x18\b \x01(\tR\rbindingSha256\x12%\n" +
	"\x0etoken_audience\x18\t \x01(\tR\rtokenAudience\x12:\n" +
	"\vapi_timeout\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\n" +
	"apiTimeout\x12F\n" +
	"\x11dispatch_interval\x18\v \x01(\v2\x19.google.protobuf.DurationR\x10dispatchInterval\x12.\n" +
	"\x13dispatch_batch_size\x18\f \x01(\rR\x11dispatchBatchSize\"m\n" +
	"\x17HTTPSWorkloadConnection\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x17\n" +
	"\aca_file\x18\x02 \x01(\tR\x06caFile\x12\x1d\n" +
	"\n" +
	"token_file\x18\x03 \x01(\tR\ttokenFile\"\xe0\x01\n" +
	"\x17ObjectStorageConnection\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x17\n" +
	"\aca_file\x18\x02 \x01(\tR\x06caFile\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12)\n" +
	"\x10credentials_file\x18\x04 \x01(\tR\x0fcredentialsFile\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12(\n" +
	"\x10max_object_bytes\x18\x06 \x01(\x03R\x0emaxObjectBytes\"\xbb\x02\n" +
	"\x11GovernanceCommand\x12*\n" +
	"\x11database_url_file\x18\x01 \x01(\tR\x0fdatabaseUrlFile\x12$\n" +
	"\x0eclient_ca_file\x18\x02 \x01(\tR\fclientCaFile\x12)\n" +
	"\x10certificate_file\x18\x03 \x01(\tR\x0fcertificateFile\x12(\n" +
	"\x10private_key_file\x18\x04 \x01(\tR\x0eprivateKeyFile\x12.\n" +
	"\x13governance_dns_name\x18\x05 \x01(\tR\x11governanceDnsName\x12O\n" +
	"\x14admission_resolution\x18\x06 \x01(\v2\x1c.conf.v1.AdmissionResolutionR\x13admissionResolution\"\x84\x01\n" +
	"\x13AdmissionResolution\x12/\n" +
	"\x13catalogue_directory\x18\x01 \x01(\tR\x12catalogueDirectory\x12<\n" +
	"\vfacts_files\x18\x02 \x03(\v2\x1b.conf.v1.AdmissionFactsFileR\n" +
	"factsFiles\"@\n" +
	"\x12AdmissionFactsFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"\xfc\x02\n" +
	"\x06Server\x12(\n" +
	"\x04grpc\x18\x01 \x01(\v2\x14.conf.v1.Server.GRPCR\x04grpc\x12+\n" +
	"\x05admin\x18\x02 \x01(\v2\x15.conf.v1.Server.AdminR\x05admin\x12D\n" +
	"\x10shutdown_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1aj\n" +
	"\x05Admin\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeoutBEZCgithub.com/zhangzhe-ctrl/ani-modeldev-service/internal/conf/v1;confb\x06proto3"

var (
	file_conf_v1_conf_proto_rawDescOnce sync.Once
	file_conf_v1_conf_proto_rawDescData []byte
)

func file_conf_v1_conf_proto_rawDescGZIP() []byte {
	file_conf_v1_conf_proto_rawDescOnce.Do(func() {
		file_conf_v1_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_v1_conf_proto_rawDesc), len(file_conf_v1_conf_proto_rawDesc)))
	})
	return file_conf_v1_conf_proto_rawDescData
}

var file_conf_v1_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_conf_v1_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),               // 0: conf.v1.Bootstrap
	(*ManagedRuntime)(nil),          // 1: conf.v1.ManagedRuntime
	(*HTTPSWorkloadConnection)(nil), // 2: conf.v1.HTTPSWorkloadConnection
	(*ObjectStorageConnection)(nil), // 3: conf.v1.ObjectStorageConnection
	(*GovernanceCommand)(nil),       // 4: conf.v1.GovernanceCommand
	(*AdmissionResolution)(nil),     // 5: conf.v1.AdmissionResolution
	(*AdmissionFactsFile)(nil),      // 6: conf.v1.AdmissionFactsFile
	(*Server)(nil),                  // 7: conf.v1.Server
	(*Server_GRPC)(nil),             // 8: conf.v1.Server.GRPC
	(*Server_Admin)(nil),            // 9: conf.v1.Server.Admin
	(*durationpb.Duration)(nil),     // 10: google.protobuf.Duration
}
var file_conf_v1_conf_proto_depIdxs = []int32{
	7,  // 0: conf.v1.Bootstrap.server:type_name -> conf.v1.Server
	4,  // 1: conf.v1.Bootstrap.command:type_name -> conf.v1.GovernanceCommand
	1,  // 2: conf.v1.Bootstrap.runtime:type_name -> conf.v1.ManagedRuntime
	8,  // 3: conf.v1.ManagedRuntime.step:type_name -> conf.v1.Server.GRPC
	2,  // 4: conf.v1.ManagedRuntime.kubernetes:type_name -> conf.v1.HTTPSWorkloadConnection
	2,  // 5: conf.v1.ManagedRuntime.pipeline:type_name -> conf.v1.HTTPSWorkloadConnection
	3,  // 6: conf.v1.ManagedRuntime.object_storage:type_name -> conf.v1.ObjectStorageConnection
	10, // 7: conf.v1.ManagedRuntime.api_timeout:type_name -> google.protobuf.Duration
	10, // 8: conf.v1.ManagedRuntime.dispatch_interval:type_name -> google.protobuf.Duration
	5,  // 9: conf.v1.GovernanceCommand.admission_resolution:type_name -> conf.v1.AdmissionResolution
	6,  // 10: conf.v1.AdmissionResolution.facts_files:type_name -> conf.v1.AdmissionFactsFile
	8,  // 11: conf.v1.Server.grpc:type_name -> conf.v1.Server.GRPC
	9,  // 12: conf.v1.Server.admin:type_name -> conf.v1.Server.Admin
	10, // 13: conf.v1.Server.shutdown_timeout:type_name -> google.protobuf.Duration
	10, // 14: conf.v1.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	10, // 15: conf.v1.Server.Admin.timeout:type_name -> google.protobuf.Duration
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_conf_v1_conf_proto_init() }
func file_conf_v1_conf_proto_init() {
	if File_conf_v1_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_v1_conf_proto_rawDesc), len(file_conf_v1_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_v1_conf_proto_goTypes,
		DependencyIndexes: file_conf_v1_conf_proto_depIdxs,
		MessageInfos:      file_conf_v1_conf_proto_msgTypes,
	}.Build()
	File_conf_v1_conf_proto = out.File
	file_conf_v1_conf_proto_goTypes = nil
	file_conf_v1_conf_proto_depIdxs = nil
}
