// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package executionsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceCloseGeneration = `-- name: AdvanceCloseGeneration :one
UPDATE modeldev_execution_identities
SET close_generation = close_generation + 1
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
RETURNING close_generation
`

type AdvanceCloseGenerationParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) AdvanceCloseGeneration(ctx context.Context, arg AdvanceCloseGenerationParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, advanceCloseGeneration, arg.TenantID, arg.ExecutionID)
	var close_generation pgtype.Numeric
	err := row.Scan(&close_generation)
	return close_generation, err
}

const advanceOwnerRevision = `-- name: AdvanceOwnerRevision :one
UPDATE modeldev_execution_identities
SET owner_revision = owner_revision + 1
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
  AND owner_revision < 18446744073709551615
RETURNING owner_revision
`

type AdvanceOwnerRevisionParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

// Only a new fact advances the version. Saturation rejects the entire writer
// transaction; a replay uses GetOwnerRevision and remains readable at Max.
func (q *Queries) AdvanceOwnerRevision(ctx context.Context, arg AdvanceOwnerRevisionParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, advanceOwnerRevision, arg.TenantID, arg.ExecutionID)
	var owner_revision pgtype.Numeric
	err := row.Scan(&owner_revision)
	return owner_revision, err
}

const findPublishedArtifactExecution = `-- name: FindPublishedArtifactExecution :many
SELECT execution_id
FROM modeldev_execution_runtimes
WHERE tenant_id = $1::uuid
  AND publication_id IS NOT NULL
  AND (facts->'Publication'->'Files') @>
      jsonb_build_array(jsonb_build_object('ArtifactID', $2::text))
LIMIT 2
`

type FindPublishedArtifactExecutionParams struct {
	TenantID   pgtype.UUID
	ArtifactID string
}

// The tenant filter precedes returning any artifact association. Two matches
// reject a duplicated artifact identity instead of choosing an arbitrary Run.
func (q *Queries) FindPublishedArtifactExecution(ctx context.Context, arg FindPublishedArtifactExecutionParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, findPublishedArtifactExecution, arg.TenantID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var execution_id pgtype.UUID
		if err := rows.Scan(&execution_id); err != nil {
			return nil, err
		}
		items = append(items, execution_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCloseIntent = `-- name: GetCloseIntent :one
SELECT tenant_id, execution_id, operation_id, spec_hash, source_kind,
    source_generation, owner_generation, reason, requested_at, requested_actor, close_state
FROM modeldev_close_intents
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
ORDER BY owner_generation DESC
LIMIT 1
`

type GetCloseIntentParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) GetCloseIntent(ctx context.Context, arg GetCloseIntentParams) (ModeldevCloseIntent, error) {
	row := q.db.QueryRow(ctx, getCloseIntent, arg.TenantID, arg.ExecutionID)
	var i ModeldevCloseIntent
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.SourceKind,
		&i.SourceGeneration,
		&i.OwnerGeneration,
		&i.Reason,
		&i.RequestedAt,
		&i.RequestedActor,
		&i.CloseState,
	)
	return i, err
}

const getCloseIntentBySource = `-- name: GetCloseIntentBySource :one
SELECT tenant_id, execution_id, operation_id, spec_hash, source_kind,
    source_generation, owner_generation, reason, requested_at, requested_actor, close_state
FROM modeldev_close_intents
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
  AND source_kind = 'GOVERNANCE'
  AND source_generation = $3
`

type GetCloseIntentBySourceParams struct {
	TenantID         pgtype.UUID
	ExecutionID      pgtype.UUID
	SourceGeneration pgtype.Numeric
}

func (q *Queries) GetCloseIntentBySource(ctx context.Context, arg GetCloseIntentBySourceParams) (ModeldevCloseIntent, error) {
	row := q.db.QueryRow(ctx, getCloseIntentBySource, arg.TenantID, arg.ExecutionID, arg.SourceGeneration)
	var i ModeldevCloseIntent
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.SourceKind,
		&i.SourceGeneration,
		&i.OwnerGeneration,
		&i.Reason,
		&i.RequestedAt,
		&i.RequestedActor,
		&i.CloseState,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT tenant_id, execution_id, operation_id, actor,
    intent_canonical, intent_hash, snapshot_canonical, spec_hash, accepted_at
FROM modeldev_executions
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
`

type GetExecutionParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) GetExecution(ctx context.Context, arg GetExecutionParams) (ModeldevExecution, error) {
	row := q.db.QueryRow(ctx, getExecution, arg.TenantID, arg.ExecutionID)
	var i ModeldevExecution
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.Actor,
		&i.IntentCanonical,
		&i.IntentHash,
		&i.SnapshotCanonical,
		&i.SpecHash,
		&i.AcceptedAt,
	)
	return i, err
}

const getOwnerRevision = `-- name: GetOwnerRevision :one
SELECT owner_revision
FROM modeldev_execution_identities
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
`

type GetOwnerRevisionParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

// Read in the identity-locked writer or the aggregate's read-only snapshot.
func (q *Queries) GetOwnerRevision(ctx context.Context, arg GetOwnerRevisionParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getOwnerRevision, arg.TenantID, arg.ExecutionID)
	var owner_revision pgtype.Numeric
	err := row.Scan(&owner_revision)
	return owner_revision, err
}

const insertCloseIntent = `-- name: InsertCloseIntent :one
INSERT INTO modeldev_close_intents (
    tenant_id, execution_id, operation_id, spec_hash, source_kind,
    source_generation, owner_generation, reason, requested_at, requested_actor, close_state
) VALUES (
    $1::uuid, $2::uuid,
    $3::uuid, $4, 'GOVERNANCE',
    $5, $6, 'USER_STOP',
    $7, $8, 'CLOSING'
)
RETURNING tenant_id, execution_id, operation_id, spec_hash, source_kind,
    source_generation, owner_generation, reason, requested_at, requested_actor, close_state
`

type InsertCloseIntentParams struct {
	TenantID         pgtype.UUID
	ExecutionID      pgtype.UUID
	OperationID      pgtype.UUID
	SpecHash         string
	SourceGeneration pgtype.Numeric
	OwnerGeneration  pgtype.Numeric
	RequestedAt      pgtype.Timestamptz
	RequestedActor   string
}

func (q *Queries) InsertCloseIntent(ctx context.Context, arg InsertCloseIntentParams) (ModeldevCloseIntent, error) {
	row := q.db.QueryRow(ctx, insertCloseIntent,
		arg.TenantID,
		arg.ExecutionID,
		arg.OperationID,
		arg.SpecHash,
		arg.SourceGeneration,
		arg.OwnerGeneration,
		arg.RequestedAt,
		arg.RequestedActor,
	)
	var i ModeldevCloseIntent
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.SourceKind,
		&i.SourceGeneration,
		&i.OwnerGeneration,
		&i.Reason,
		&i.RequestedAt,
		&i.RequestedActor,
		&i.CloseState,
	)
	return i, err
}

const insertExecution = `-- name: InsertExecution :one
INSERT INTO modeldev_executions (
    tenant_id, execution_id, operation_id, actor,
    intent_canonical, intent_hash, snapshot_canonical, spec_hash, accepted_at
) VALUES (
    $1::uuid, $2::uuid,
    $3::uuid, $4,
    $5, $6,
    $7, $8, $9
)
ON CONFLICT DO NOTHING
RETURNING tenant_id, execution_id, operation_id, actor,
    intent_canonical, intent_hash, snapshot_canonical, spec_hash, accepted_at
`

type InsertExecutionParams struct {
	TenantID          pgtype.UUID
	ExecutionID       pgtype.UUID
	OperationID       pgtype.UUID
	Actor             string
	IntentCanonical   []byte
	IntentHash        string
	SnapshotCanonical []byte
	SpecHash          string
	AcceptedAt        pgtype.Timestamptz
}

func (q *Queries) InsertExecution(ctx context.Context, arg InsertExecutionParams) (ModeldevExecution, error) {
	row := q.db.QueryRow(ctx, insertExecution,
		arg.TenantID,
		arg.ExecutionID,
		arg.OperationID,
		arg.Actor,
		arg.IntentCanonical,
		arg.IntentHash,
		arg.SnapshotCanonical,
		arg.SpecHash,
		arg.AcceptedAt,
	)
	var i ModeldevExecution
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.Actor,
		&i.IntentCanonical,
		&i.IntentHash,
		&i.SnapshotCanonical,
		&i.SpecHash,
		&i.AcceptedAt,
	)
	return i, err
}

const insertExecutionIdentity = `-- name: InsertExecutionIdentity :exec
INSERT INTO modeldev_execution_identities (tenant_id, execution_id, operation_id, spec_hash)
VALUES (
    $1::uuid, $2::uuid,
    $3::uuid, $4
)
ON CONFLICT DO NOTHING
`

type InsertExecutionIdentityParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
	OperationID pgtype.UUID
	SpecHash    string
}

func (q *Queries) InsertExecutionIdentity(ctx context.Context, arg InsertExecutionIdentityParams) error {
	_, err := q.db.Exec(ctx, insertExecutionIdentity,
		arg.TenantID,
		arg.ExecutionID,
		arg.OperationID,
		arg.SpecHash,
	)
	return err
}

const lockExecutionIdentity = `-- name: LockExecutionIdentity :one
SELECT tenant_id, execution_id, operation_id, spec_hash, close_generation, owner_revision
FROM modeldev_execution_identities
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
FOR UPDATE
`

type LockExecutionIdentityParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) LockExecutionIdentity(ctx context.Context, arg LockExecutionIdentityParams) (ModeldevExecutionIdentity, error) {
	row := q.db.QueryRow(ctx, lockExecutionIdentity, arg.TenantID, arg.ExecutionID)
	var i ModeldevExecutionIdentity
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.CloseGeneration,
		&i.OwnerRevision,
	)
	return i, err
}
