// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package executionsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExecution = `-- name: GetExecution :one
SELECT tenant_id, execution_id, operation_id, actor,
    intent_canonical, intent_hash, snapshot_canonical, spec_hash, accepted_at
FROM modeldev_executions
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
`

type GetExecutionParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) GetExecution(ctx context.Context, arg GetExecutionParams) (ModeldevExecution, error) {
	row := q.db.QueryRow(ctx, getExecution, arg.TenantID, arg.ExecutionID)
	var i ModeldevExecution
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.Actor,
		&i.IntentCanonical,
		&i.IntentHash,
		&i.SnapshotCanonical,
		&i.SpecHash,
		&i.AcceptedAt,
	)
	return i, err
}

const insertExecution = `-- name: InsertExecution :one
INSERT INTO modeldev_executions (
    tenant_id, execution_id, operation_id, actor,
    intent_canonical, intent_hash, snapshot_canonical, spec_hash, accepted_at
) VALUES (
    $1::uuid, $2::uuid,
    $3::uuid, $4,
    $5, $6,
    $7, $8, $9
)
RETURNING tenant_id, execution_id, operation_id, actor,
    intent_canonical, intent_hash, snapshot_canonical, spec_hash, accepted_at
`

type InsertExecutionParams struct {
	TenantID          pgtype.UUID
	ExecutionID       pgtype.UUID
	OperationID       pgtype.UUID
	Actor             string
	IntentCanonical   []byte
	IntentHash        string
	SnapshotCanonical []byte
	SpecHash          string
	AcceptedAt        pgtype.Timestamptz
}

func (q *Queries) InsertExecution(ctx context.Context, arg InsertExecutionParams) (ModeldevExecution, error) {
	row := q.db.QueryRow(ctx, insertExecution,
		arg.TenantID,
		arg.ExecutionID,
		arg.OperationID,
		arg.Actor,
		arg.IntentCanonical,
		arg.IntentHash,
		arg.SnapshotCanonical,
		arg.SpecHash,
		arg.AcceptedAt,
	)
	var i ModeldevExecution
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.Actor,
		&i.IntentCanonical,
		&i.IntentHash,
		&i.SnapshotCanonical,
		&i.SpecHash,
		&i.AcceptedAt,
	)
	return i, err
}
