// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ani/modeldev/v1/management.proto

package modeldevv1

import (
	v1 "github.com/zhangzhe-ctrl/ani-modeldev-service/api/ani/training/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportReleaseRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PresetId         string                 `protobuf:"bytes,1,opt,name=preset_id,json=presetId,proto3" json:"preset_id,omitempty"`
	ReleaseId        string                 `protobuf:"bytes,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ReleaseDigest    string                 `protobuf:"bytes,3,opt,name=release_digest,json=releaseDigest,proto3" json:"release_digest,omitempty"`
	CanonicalRelease []byte                 `protobuf:"bytes,4,opt,name=canonical_release,json=canonicalRelease,proto3" json:"canonical_release,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImportReleaseRequest) Reset() {
	*x = ImportReleaseRequest{}
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportReleaseRequest) ProtoMessage() {}

func (x *ImportReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportReleaseRequest.ProtoReflect.Descriptor instead.
func (*ImportReleaseRequest) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_management_proto_rawDescGZIP(), []int{0}
}

func (x *ImportReleaseRequest) GetPresetId() string {
	if x != nil {
		return x.PresetId
	}
	return ""
}

func (x *ImportReleaseRequest) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *ImportReleaseRequest) GetReleaseDigest() string {
	if x != nil {
		return x.ReleaseDigest
	}
	return ""
}

func (x *ImportReleaseRequest) GetCanonicalRelease() []byte {
	if x != nil {
		return x.CanonicalRelease
	}
	return nil
}

type ImportReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PresetId      string                 `protobuf:"bytes,1,opt,name=preset_id,json=presetId,proto3" json:"preset_id,omitempty"`
	ReleaseId     string                 `protobuf:"bytes,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ReleaseDigest string                 `protobuf:"bytes,3,opt,name=release_digest,json=releaseDigest,proto3" json:"release_digest,omitempty"`
	Created       bool                   `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportReleaseResponse) Reset() {
	*x = ImportReleaseResponse{}
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportReleaseResponse) ProtoMessage() {}

func (x *ImportReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportReleaseResponse.ProtoReflect.Descriptor instead.
func (*ImportReleaseResponse) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_management_proto_rawDescGZIP(), []int{1}
}

func (x *ImportReleaseResponse) GetPresetId() string {
	if x != nil {
		return x.PresetId
	}
	return ""
}

func (x *ImportReleaseResponse) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *ImportReleaseResponse) GetReleaseDigest() string {
	if x != nil {
		return x.ReleaseDigest
	}
	return ""
}

func (x *ImportReleaseResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ValidateReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PresetId      string                 `protobuf:"bytes,1,opt,name=preset_id,json=presetId,proto3" json:"preset_id,omitempty"`
	ReleaseId     string                 `protobuf:"bytes,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ReleaseDigest string                 `protobuf:"bytes,3,opt,name=release_digest,json=releaseDigest,proto3" json:"release_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateReleaseRequest) Reset() {
	*x = ValidateReleaseRequest{}
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateReleaseRequest) ProtoMessage() {}

func (x *ValidateReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateReleaseRequest.ProtoReflect.Descriptor instead.
func (*ValidateReleaseRequest) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_management_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateReleaseRequest) GetPresetId() string {
	if x != nil {
		return x.PresetId
	}
	return ""
}

func (x *ValidateReleaseRequest) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *ValidateReleaseRequest) GetReleaseDigest() string {
	if x != nil {
		return x.ReleaseDigest
	}
	return ""
}

type ValidateReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PresetId      string                 `protobuf:"bytes,1,opt,name=preset_id,json=presetId,proto3" json:"preset_id,omitempty"`
	ReleaseId     string                 `protobuf:"bytes,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ReleaseDigest string                 `protobuf:"bytes,3,opt,name=release_digest,json=releaseDigest,proto3" json:"release_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateReleaseResponse) Reset() {
	*x = ValidateReleaseResponse{}
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateReleaseResponse) ProtoMessage() {}

func (x *ValidateReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateReleaseResponse.ProtoReflect.Descriptor instead.
func (*ValidateReleaseResponse) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_management_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateReleaseResponse) GetPresetId() string {
	if x != nil {
		return x.PresetId
	}
	return ""
}

func (x *ValidateReleaseResponse) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *ValidateReleaseResponse) GetReleaseDigest() string {
	if x != nil {
		return x.ReleaseDigest
	}
	return ""
}

type ImportCSVRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InputVersionId string                 `protobuf:"bytes,1,opt,name=input_version_id,json=inputVersionId,proto3" json:"input_version_id,omitempty"`
	// Selects owner-approved input scope, never an arbitrary bucket prefix.
	ReleaseId     string             `protobuf:"bytes,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ReleaseDigest string             `protobuf:"bytes,3,opt,name=release_digest,json=releaseDigest,proto3" json:"release_digest,omitempty"`
	Object        *v1.FixedObjectRef `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	// Immutable import fact; retries keep the original time and request identity.
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportCSVRequest) Reset() {
	*x = ImportCSVRequest{}
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCSVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCSVRequest) ProtoMessage() {}

func (x *ImportCSVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCSVRequest.ProtoReflect.Descriptor instead.
func (*ImportCSVRequest) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_management_proto_rawDescGZIP(), []int{4}
}

func (x *ImportCSVRequest) GetInputVersionId() string {
	if x != nil {
		return x.InputVersionId
	}
	return ""
}

func (x *ImportCSVRequest) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *ImportCSVRequest) GetReleaseDigest() string {
	if x != nil {
		return x.ReleaseDigest
	}
	return ""
}

func (x *ImportCSVRequest) GetObject() *v1.FixedObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *ImportCSVRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type ImportCSVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputVersion  *InputVersionView      `protobuf:"bytes,1,opt,name=input_version,json=inputVersion,proto3" json:"input_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportCSVResponse) Reset() {
	*x = ImportCSVResponse{}
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCSVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCSVResponse) ProtoMessage() {}

func (x *ImportCSVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCSVResponse.ProtoReflect.Descriptor instead.
func (*ImportCSVResponse) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_management_proto_rawDescGZIP(), []int{5}
}

func (x *ImportCSVResponse) GetInputVersion() *InputVersionView {
	if x != nil {
		return x.InputVersion
	}
	return nil
}

var File_ani_modeldev_v1_management_proto protoreflect.FileDescriptor

const file_ani_modeldev_v1_management_proto_rawDesc = "" +
	"\n" +
	" ani/modeldev/v1/management.proto\x12\x0fani.modeldev.v1\x1a\x1eani/modeldev/v1/modeldev.proto\x1a\x1eani/training/v1/training.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x01\n" +
	"\x14ImportReleaseRequest\x12\x1b\n" +
	"\tpreset_id\x18\x01 \x01(\tR\bpresetId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\tR\treleaseId\x12%\n" +
	"\x0erelease_digest\x18\x03 \x01(\tR\rreleaseDigest\x12+\n" +
	"\x11canonical_release\x18\x04 \x01(\fR\x10canonicalRelease\"\x94\x01\n" +
	"\x15ImportReleaseResponse\x12\x1b\n" +
	"\tpreset_id\x18\x01 \x01(\tR\bpresetId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\tR\treleaseId\x12%\n" +
	"\x0erelease_digest\x18\x03 \x01(\tR\rreleaseDigest\x12\x18\n" +
	"\acreated\x18\x04 \x01(\bR\acreated\"{\n" +
	"\x16ValidateReleaseRequest\x12\x1b\n" +
	"\tpreset_id\x18\x01 \x01(\tR\bpresetId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\tR\treleaseId\x12%\n" +
	"\x0erelease_digest\x18\x03 \x01(\tR\rreleaseDigest\"|\n" +
	"\x17ValidateReleaseResponse\x12\x1b\n" +
	"\tpreset_id\x18\x01 \x01(\tR\bpresetId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\tR\treleaseId\x12%\n" +
	"\x0erelease_digest\x18\x03 \x01(\tR\rreleaseDigest\"\xfa\x01\n" +
	"\x10ImportCSVRequest\x12(\n" +
	"\x10input_version_id\x18\x01 \x01(\tR\x0einputVersionId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\tR\treleaseId\x12%\n" +
	"\x0erelease_digest\x18\x03 \x01(\tR\rreleaseDigest\x127\n" +
	"\x06object\x18\x04 \x01(\v2\x1f.ani.training.v1.FixedObjectRefR\x06object\x12=\n" +
	"\frequested_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"[\n" +
	"\x11ImportCSVResponse\x12F\n" +
	"\rinput_version\x18\x01 \x01(\v2!.ani.modeldev.v1.InputVersionViewR\finputVersion2\xb5\x02\n" +
	"\x19ModelDevManagementService\x12^\n" +
	"\rImportRelease\x12%.ani.modeldev.v1.ImportReleaseRequest\x1a&.ani.modeldev.v1.ImportReleaseResponse\x12d\n" +
	"\x0fValidateRelease\x12'.ani.modeldev.v1.ValidateReleaseRequest\x1a(.ani.modeldev.v1.ValidateReleaseResponse\x12R\n" +
	"\tImportCSV\x12!.ani.modeldev.v1.ImportCSVRequest\x1a\".ani.modeldev.v1.ImportCSVResponseBNZLgithub.com/zhangzhe-ctrl/ani-modeldev-service/api/ani/modeldev/v1;modeldevv1b\x06proto3"

var (
	file_ani_modeldev_v1_management_proto_rawDescOnce sync.Once
	file_ani_modeldev_v1_management_proto_rawDescData []byte
)

func file_ani_modeldev_v1_management_proto_rawDescGZIP() []byte {
	file_ani_modeldev_v1_management_proto_rawDescOnce.Do(func() {
		file_ani_modeldev_v1_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ani_modeldev_v1_management_proto_rawDesc), len(file_ani_modeldev_v1_management_proto_rawDesc)))
	})
	return file_ani_modeldev_v1_management_proto_rawDescData
}

var file_ani_modeldev_v1_management_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ani_modeldev_v1_management_proto_goTypes = []any{
	(*ImportReleaseRequest)(nil),    // 0: ani.modeldev.v1.ImportReleaseRequest
	(*ImportReleaseResponse)(nil),   // 1: ani.modeldev.v1.ImportReleaseResponse
	(*ValidateReleaseRequest)(nil),  // 2: ani.modeldev.v1.ValidateReleaseRequest
	(*ValidateReleaseResponse)(nil), // 3: ani.modeldev.v1.ValidateReleaseResponse
	(*ImportCSVRequest)(nil),        // 4: ani.modeldev.v1.ImportCSVRequest
	(*ImportCSVResponse)(nil),       // 5: ani.modeldev.v1.ImportCSVResponse
	(*v1.FixedObjectRef)(nil),       // 6: ani.training.v1.FixedObjectRef
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
	(*InputVersionView)(nil),        // 8: ani.modeldev.v1.InputVersionView
}
var file_ani_modeldev_v1_management_proto_depIdxs = []int32{
	6, // 0: ani.modeldev.v1.ImportCSVRequest.object:type_name -> ani.training.v1.FixedObjectRef
	7, // 1: ani.modeldev.v1.ImportCSVRequest.requested_at:type_name -> google.protobuf.Timestamp
	8, // 2: ani.modeldev.v1.ImportCSVResponse.input_version:type_name -> ani.modeldev.v1.InputVersionView
	0, // 3: ani.modeldev.v1.ModelDevManagementService.ImportRelease:input_type -> ani.modeldev.v1.ImportReleaseRequest
	2, // 4: ani.modeldev.v1.ModelDevManagementService.ValidateRelease:input_type -> ani.modeldev.v1.ValidateReleaseRequest
	4, // 5: ani.modeldev.v1.ModelDevManagementService.ImportCSV:input_type -> ani.modeldev.v1.ImportCSVRequest
	1, // 6: ani.modeldev.v1.ModelDevManagementService.ImportRelease:output_type -> ani.modeldev.v1.ImportReleaseResponse
	3, // 7: ani.modeldev.v1.ModelDevManagementService.ValidateRelease:output_type -> ani.modeldev.v1.ValidateReleaseResponse
	5, // 8: ani.modeldev.v1.ModelDevManagementService.ImportCSV:output_type -> ani.modeldev.v1.ImportCSVResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ani_modeldev_v1_management_proto_init() }
func file_ani_modeldev_v1_management_proto_init() {
	if File_ani_modeldev_v1_management_proto != nil {
		return
	}
	file_ani_modeldev_v1_modeldev_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ani_modeldev_v1_management_proto_rawDesc), len(file_ani_modeldev_v1_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ani_modeldev_v1_management_proto_goTypes,
		DependencyIndexes: file_ani_modeldev_v1_management_proto_depIdxs,
		MessageInfos:      file_ani_modeldev_v1_management_proto_msgTypes,
	}.Build()
	File_ani_modeldev_v1_management_proto = out.File
	file_ani_modeldev_v1_management_proto_goTypes = nil
	file_ani_modeldev_v1_management_proto_depIdxs = nil
}
