// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ani/modeldev/v1/management.proto

package modeldevv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelDevManagementService_ImportRelease_FullMethodName   = "/ani.modeldev.v1.ModelDevManagementService/ImportRelease"
	ModelDevManagementService_ValidateRelease_FullMethodName = "/ani.modeldev.v1.ModelDevManagementService/ValidateRelease"
	ModelDevManagementService_ImportCSV_FullMethodName       = "/ani.modeldev.v1.ModelDevManagementService/ImportCSV"
)

// ModelDevManagementServiceClient is the client API for ModelDevManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Governance checks the current management permission and delegates this exact
// method over its authenticated mTLS connection. No user identity is in a body.
type ModelDevManagementServiceClient interface {
	ImportRelease(ctx context.Context, in *ImportReleaseRequest, opts ...grpc.CallOption) (*ImportReleaseResponse, error)
	ValidateRelease(ctx context.Context, in *ValidateReleaseRequest, opts ...grpc.CallOption) (*ValidateReleaseResponse, error)
	ImportCSV(ctx context.Context, in *ImportCSVRequest, opts ...grpc.CallOption) (*ImportCSVResponse, error)
}

type modelDevManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelDevManagementServiceClient(cc grpc.ClientConnInterface) ModelDevManagementServiceClient {
	return &modelDevManagementServiceClient{cc}
}

func (c *modelDevManagementServiceClient) ImportRelease(ctx context.Context, in *ImportReleaseRequest, opts ...grpc.CallOption) (*ImportReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportReleaseResponse)
	err := c.cc.Invoke(ctx, ModelDevManagementService_ImportRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevManagementServiceClient) ValidateRelease(ctx context.Context, in *ValidateReleaseRequest, opts ...grpc.CallOption) (*ValidateReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateReleaseResponse)
	err := c.cc.Invoke(ctx, ModelDevManagementService_ValidateRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevManagementServiceClient) ImportCSV(ctx context.Context, in *ImportCSVRequest, opts ...grpc.CallOption) (*ImportCSVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportCSVResponse)
	err := c.cc.Invoke(ctx, ModelDevManagementService_ImportCSV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelDevManagementServiceServer is the server API for ModelDevManagementService service.
// All implementations must embed UnimplementedModelDevManagementServiceServer
// for forward compatibility.
//
// Governance checks the current management permission and delegates this exact
// method over its authenticated mTLS connection. No user identity is in a body.
type ModelDevManagementServiceServer interface {
	ImportRelease(context.Context, *ImportReleaseRequest) (*ImportReleaseResponse, error)
	ValidateRelease(context.Context, *ValidateReleaseRequest) (*ValidateReleaseResponse, error)
	ImportCSV(context.Context, *ImportCSVRequest) (*ImportCSVResponse, error)
	mustEmbedUnimplementedModelDevManagementServiceServer()
}

// UnimplementedModelDevManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelDevManagementServiceServer struct{}

func (UnimplementedModelDevManagementServiceServer) ImportRelease(context.Context, *ImportReleaseRequest) (*ImportReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportRelease not implemented")
}
func (UnimplementedModelDevManagementServiceServer) ValidateRelease(context.Context, *ValidateReleaseRequest) (*ValidateReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateRelease not implemented")
}
func (UnimplementedModelDevManagementServiceServer) ImportCSV(context.Context, *ImportCSVRequest) (*ImportCSVResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportCSV not implemented")
}
func (UnimplementedModelDevManagementServiceServer) mustEmbedUnimplementedModelDevManagementServiceServer() {
}
func (UnimplementedModelDevManagementServiceServer) testEmbeddedByValue() {}

// UnsafeModelDevManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelDevManagementServiceServer will
// result in compilation errors.
type UnsafeModelDevManagementServiceServer interface {
	mustEmbedUnimplementedModelDevManagementServiceServer()
}

func RegisterModelDevManagementServiceServer(s grpc.ServiceRegistrar, srv ModelDevManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedModelDevManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelDevManagementService_ServiceDesc, srv)
}

func _ModelDevManagementService_ImportRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevManagementServiceServer).ImportRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevManagementService_ImportRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevManagementServiceServer).ImportRelease(ctx, req.(*ImportReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevManagementService_ValidateRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevManagementServiceServer).ValidateRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevManagementService_ValidateRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevManagementServiceServer).ValidateRelease(ctx, req.(*ValidateReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevManagementService_ImportCSV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportCSVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevManagementServiceServer).ImportCSV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevManagementService_ImportCSV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevManagementServiceServer).ImportCSV(ctx, req.(*ImportCSVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelDevManagementService_ServiceDesc is the grpc.ServiceDesc for ModelDevManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelDevManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ani.modeldev.v1.ModelDevManagementService",
	HandlerType: (*ModelDevManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImportRelease",
			Handler:    _ModelDevManagementService_ImportRelease_Handler,
		},
		{
			MethodName: "ValidateRelease",
			Handler:    _ModelDevManagementService_ValidateRelease_Handler,
		},
		{
			MethodName: "ImportCSV",
			Handler:    _ModelDevManagementService_ImportCSV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ani/modeldev/v1/management.proto",
}
