// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ani/modeldev/v1/modeldev.proto

package modeldevv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelDevQueryService_ListPresets_FullMethodName               = "/ani.modeldev.v1.ModelDevQueryService/ListPresets"
	ModelDevQueryService_GetInputVersion_FullMethodName           = "/ani.modeldev.v1.ModelDevQueryService/GetInputVersion"
	ModelDevQueryService_ListInputVersions_FullMethodName         = "/ani.modeldev.v1.ModelDevQueryService/ListInputVersions"
	ModelDevQueryService_GetExecution_FullMethodName              = "/ani.modeldev.v1.ModelDevQueryService/GetExecution"
	ModelDevQueryService_ListExecutions_FullMethodName            = "/ani.modeldev.v1.ModelDevQueryService/ListExecutions"
	ModelDevQueryService_GetExecutionLogs_FullMethodName          = "/ani.modeldev.v1.ModelDevQueryService/GetExecutionLogs"
	ModelDevQueryService_ListExecutionArtifacts_FullMethodName    = "/ani.modeldev.v1.ModelDevQueryService/ListExecutionArtifacts"
	ModelDevQueryService_AuthorizeArtifactDownload_FullMethodName = "/ani.modeldev.v1.ModelDevQueryService/AuthorizeArtifactDownload"
)

// ModelDevQueryServiceClient is the client API for ModelDevQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BFF-facing internal RPCs. Each call requires current actor authorization;
// the actor saved at admission is audit data, not permanent access permission.
type ModelDevQueryServiceClient interface {
	ListPresets(ctx context.Context, in *ListPresetsRequest, opts ...grpc.CallOption) (*ListPresetsResponse, error)
	GetInputVersion(ctx context.Context, in *GetInputVersionRequest, opts ...grpc.CallOption) (*GetInputVersionResponse, error)
	ListInputVersions(ctx context.Context, in *ListInputVersionsRequest, opts ...grpc.CallOption) (*ListInputVersionsResponse, error)
	GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*GetExecutionResponse, error)
	ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error)
	GetExecutionLogs(ctx context.Context, in *GetExecutionLogsRequest, opts ...grpc.CallOption) (*GetExecutionLogsResponse, error)
	ListExecutionArtifacts(ctx context.Context, in *ListExecutionArtifactsRequest, opts ...grpc.CallOption) (*ListExecutionArtifactsResponse, error)
	AuthorizeArtifactDownload(ctx context.Context, in *AuthorizeArtifactDownloadRequest, opts ...grpc.CallOption) (*AuthorizeArtifactDownloadResponse, error)
}

type modelDevQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelDevQueryServiceClient(cc grpc.ClientConnInterface) ModelDevQueryServiceClient {
	return &modelDevQueryServiceClient{cc}
}

func (c *modelDevQueryServiceClient) ListPresets(ctx context.Context, in *ListPresetsRequest, opts ...grpc.CallOption) (*ListPresetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPresetsResponse)
	err := c.cc.Invoke(ctx, ModelDevQueryService_ListPresets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevQueryServiceClient) GetInputVersion(ctx context.Context, in *GetInputVersionRequest, opts ...grpc.CallOption) (*GetInputVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInputVersionResponse)
	err := c.cc.Invoke(ctx, ModelDevQueryService_GetInputVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevQueryServiceClient) ListInputVersions(ctx context.Context, in *ListInputVersionsRequest, opts ...grpc.CallOption) (*ListInputVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInputVersionsResponse)
	err := c.cc.Invoke(ctx, ModelDevQueryService_ListInputVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevQueryServiceClient) GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*GetExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExecutionResponse)
	err := c.cc.Invoke(ctx, ModelDevQueryService_GetExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevQueryServiceClient) ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionsResponse)
	err := c.cc.Invoke(ctx, ModelDevQueryService_ListExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevQueryServiceClient) GetExecutionLogs(ctx context.Context, in *GetExecutionLogsRequest, opts ...grpc.CallOption) (*GetExecutionLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExecutionLogsResponse)
	err := c.cc.Invoke(ctx, ModelDevQueryService_GetExecutionLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevQueryServiceClient) ListExecutionArtifacts(ctx context.Context, in *ListExecutionArtifactsRequest, opts ...grpc.CallOption) (*ListExecutionArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionArtifactsResponse)
	err := c.cc.Invoke(ctx, ModelDevQueryService_ListExecutionArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevQueryServiceClient) AuthorizeArtifactDownload(ctx context.Context, in *AuthorizeArtifactDownloadRequest, opts ...grpc.CallOption) (*AuthorizeArtifactDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeArtifactDownloadResponse)
	err := c.cc.Invoke(ctx, ModelDevQueryService_AuthorizeArtifactDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelDevQueryServiceServer is the server API for ModelDevQueryService service.
// All implementations must embed UnimplementedModelDevQueryServiceServer
// for forward compatibility.
//
// BFF-facing internal RPCs. Each call requires current actor authorization;
// the actor saved at admission is audit data, not permanent access permission.
type ModelDevQueryServiceServer interface {
	ListPresets(context.Context, *ListPresetsRequest) (*ListPresetsResponse, error)
	GetInputVersion(context.Context, *GetInputVersionRequest) (*GetInputVersionResponse, error)
	ListInputVersions(context.Context, *ListInputVersionsRequest) (*ListInputVersionsResponse, error)
	GetExecution(context.Context, *GetExecutionRequest) (*GetExecutionResponse, error)
	ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error)
	GetExecutionLogs(context.Context, *GetExecutionLogsRequest) (*GetExecutionLogsResponse, error)
	ListExecutionArtifacts(context.Context, *ListExecutionArtifactsRequest) (*ListExecutionArtifactsResponse, error)
	AuthorizeArtifactDownload(context.Context, *AuthorizeArtifactDownloadRequest) (*AuthorizeArtifactDownloadResponse, error)
	mustEmbedUnimplementedModelDevQueryServiceServer()
}

// UnimplementedModelDevQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelDevQueryServiceServer struct{}

func (UnimplementedModelDevQueryServiceServer) ListPresets(context.Context, *ListPresetsRequest) (*ListPresetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPresets not implemented")
}
func (UnimplementedModelDevQueryServiceServer) GetInputVersion(context.Context, *GetInputVersionRequest) (*GetInputVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInputVersion not implemented")
}
func (UnimplementedModelDevQueryServiceServer) ListInputVersions(context.Context, *ListInputVersionsRequest) (*ListInputVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInputVersions not implemented")
}
func (UnimplementedModelDevQueryServiceServer) GetExecution(context.Context, *GetExecutionRequest) (*GetExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecution not implemented")
}
func (UnimplementedModelDevQueryServiceServer) ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExecutions not implemented")
}
func (UnimplementedModelDevQueryServiceServer) GetExecutionLogs(context.Context, *GetExecutionLogsRequest) (*GetExecutionLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecutionLogs not implemented")
}
func (UnimplementedModelDevQueryServiceServer) ListExecutionArtifacts(context.Context, *ListExecutionArtifactsRequest) (*ListExecutionArtifactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExecutionArtifacts not implemented")
}
func (UnimplementedModelDevQueryServiceServer) AuthorizeArtifactDownload(context.Context, *AuthorizeArtifactDownloadRequest) (*AuthorizeArtifactDownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizeArtifactDownload not implemented")
}
func (UnimplementedModelDevQueryServiceServer) mustEmbedUnimplementedModelDevQueryServiceServer() {}
func (UnimplementedModelDevQueryServiceServer) testEmbeddedByValue()                              {}

// UnsafeModelDevQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelDevQueryServiceServer will
// result in compilation errors.
type UnsafeModelDevQueryServiceServer interface {
	mustEmbedUnimplementedModelDevQueryServiceServer()
}

func RegisterModelDevQueryServiceServer(s grpc.ServiceRegistrar, srv ModelDevQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedModelDevQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelDevQueryService_ServiceDesc, srv)
}

func _ModelDevQueryService_ListPresets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPresetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevQueryServiceServer).ListPresets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevQueryService_ListPresets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevQueryServiceServer).ListPresets(ctx, req.(*ListPresetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevQueryService_GetInputVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInputVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevQueryServiceServer).GetInputVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevQueryService_GetInputVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevQueryServiceServer).GetInputVersion(ctx, req.(*GetInputVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevQueryService_ListInputVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInputVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevQueryServiceServer).ListInputVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevQueryService_ListInputVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevQueryServiceServer).ListInputVersions(ctx, req.(*ListInputVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevQueryService_GetExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevQueryServiceServer).GetExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevQueryService_GetExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevQueryServiceServer).GetExecution(ctx, req.(*GetExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevQueryService_ListExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevQueryServiceServer).ListExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevQueryService_ListExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevQueryServiceServer).ListExecutions(ctx, req.(*ListExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevQueryService_GetExecutionLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevQueryServiceServer).GetExecutionLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevQueryService_GetExecutionLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevQueryServiceServer).GetExecutionLogs(ctx, req.(*GetExecutionLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevQueryService_ListExecutionArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevQueryServiceServer).ListExecutionArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevQueryService_ListExecutionArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevQueryServiceServer).ListExecutionArtifacts(ctx, req.(*ListExecutionArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevQueryService_AuthorizeArtifactDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeArtifactDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevQueryServiceServer).AuthorizeArtifactDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevQueryService_AuthorizeArtifactDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevQueryServiceServer).AuthorizeArtifactDownload(ctx, req.(*AuthorizeArtifactDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelDevQueryService_ServiceDesc is the grpc.ServiceDesc for ModelDevQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelDevQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ani.modeldev.v1.ModelDevQueryService",
	HandlerType: (*ModelDevQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPresets",
			Handler:    _ModelDevQueryService_ListPresets_Handler,
		},
		{
			MethodName: "GetInputVersion",
			Handler:    _ModelDevQueryService_GetInputVersion_Handler,
		},
		{
			MethodName: "ListInputVersions",
			Handler:    _ModelDevQueryService_ListInputVersions_Handler,
		},
		{
			MethodName: "GetExecution",
			Handler:    _ModelDevQueryService_GetExecution_Handler,
		},
		{
			MethodName: "ListExecutions",
			Handler:    _ModelDevQueryService_ListExecutions_Handler,
		},
		{
			MethodName: "GetExecutionLogs",
			Handler:    _ModelDevQueryService_GetExecutionLogs_Handler,
		},
		{
			MethodName: "ListExecutionArtifacts",
			Handler:    _ModelDevQueryService_ListExecutionArtifacts_Handler,
		},
		{
			MethodName: "AuthorizeArtifactDownload",
			Handler:    _ModelDevQueryService_AuthorizeArtifactDownload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ani/modeldev/v1/modeldev.proto",
}

const (
	ModelDevAdmissionService_ResolveAdmission_FullMethodName = "/ani.modeldev.v1.ModelDevAdmissionService/ResolveAdmission"
)

// ModelDevAdmissionServiceClient is the client API for ModelDevAdmissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Only authenticated Governance may resolve a candidate after current actor
// authorization and an original-key miss. This service does not accept an
// execution, allocate command IDs or choose Governance's current Release.
type ModelDevAdmissionServiceClient interface {
	ResolveAdmission(ctx context.Context, in *ResolveAdmissionRequest, opts ...grpc.CallOption) (*ResolveAdmissionResponse, error)
}

type modelDevAdmissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelDevAdmissionServiceClient(cc grpc.ClientConnInterface) ModelDevAdmissionServiceClient {
	return &modelDevAdmissionServiceClient{cc}
}

func (c *modelDevAdmissionServiceClient) ResolveAdmission(ctx context.Context, in *ResolveAdmissionRequest, opts ...grpc.CallOption) (*ResolveAdmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAdmissionResponse)
	err := c.cc.Invoke(ctx, ModelDevAdmissionService_ResolveAdmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelDevAdmissionServiceServer is the server API for ModelDevAdmissionService service.
// All implementations must embed UnimplementedModelDevAdmissionServiceServer
// for forward compatibility.
//
// Only authenticated Governance may resolve a candidate after current actor
// authorization and an original-key miss. This service does not accept an
// execution, allocate command IDs or choose Governance's current Release.
type ModelDevAdmissionServiceServer interface {
	ResolveAdmission(context.Context, *ResolveAdmissionRequest) (*ResolveAdmissionResponse, error)
	mustEmbedUnimplementedModelDevAdmissionServiceServer()
}

// UnimplementedModelDevAdmissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelDevAdmissionServiceServer struct{}

func (UnimplementedModelDevAdmissionServiceServer) ResolveAdmission(context.Context, *ResolveAdmissionRequest) (*ResolveAdmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAdmission not implemented")
}
func (UnimplementedModelDevAdmissionServiceServer) mustEmbedUnimplementedModelDevAdmissionServiceServer() {
}
func (UnimplementedModelDevAdmissionServiceServer) testEmbeddedByValue() {}

// UnsafeModelDevAdmissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelDevAdmissionServiceServer will
// result in compilation errors.
type UnsafeModelDevAdmissionServiceServer interface {
	mustEmbedUnimplementedModelDevAdmissionServiceServer()
}

func RegisterModelDevAdmissionServiceServer(s grpc.ServiceRegistrar, srv ModelDevAdmissionServiceServer) {
	// If the following call panics, it indicates UnimplementedModelDevAdmissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelDevAdmissionService_ServiceDesc, srv)
}

func _ModelDevAdmissionService_ResolveAdmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAdmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevAdmissionServiceServer).ResolveAdmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevAdmissionService_ResolveAdmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevAdmissionServiceServer).ResolveAdmission(ctx, req.(*ResolveAdmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelDevAdmissionService_ServiceDesc is the grpc.ServiceDesc for ModelDevAdmissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelDevAdmissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ani.modeldev.v1.ModelDevAdmissionService",
	HandlerType: (*ModelDevAdmissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveAdmission",
			Handler:    _ModelDevAdmissionService_ResolveAdmission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ani/modeldev/v1/modeldev.proto",
}

const (
	ModelDevCommandService_AcceptExecution_FullMethodName  = "/ani.modeldev.v1.ModelDevCommandService/AcceptExecution"
	ModelDevCommandService_ApplyCloseIntent_FullMethodName = "/ani.modeldev.v1.ModelDevCommandService/ApplyCloseIntent"
)

// ModelDevCommandServiceClient is the client API for ModelDevCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Only the authenticated Governance delivery identity may call this service.
// ACK is emitted after the command or close tombstone is durably committed.
type ModelDevCommandServiceClient interface {
	AcceptExecution(ctx context.Context, in *AcceptExecutionRequest, opts ...grpc.CallOption) (*AcceptExecutionResponse, error)
	ApplyCloseIntent(ctx context.Context, in *ApplyCloseIntentRequest, opts ...grpc.CallOption) (*ApplyCloseIntentResponse, error)
}

type modelDevCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelDevCommandServiceClient(cc grpc.ClientConnInterface) ModelDevCommandServiceClient {
	return &modelDevCommandServiceClient{cc}
}

func (c *modelDevCommandServiceClient) AcceptExecution(ctx context.Context, in *AcceptExecutionRequest, opts ...grpc.CallOption) (*AcceptExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptExecutionResponse)
	err := c.cc.Invoke(ctx, ModelDevCommandService_AcceptExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevCommandServiceClient) ApplyCloseIntent(ctx context.Context, in *ApplyCloseIntentRequest, opts ...grpc.CallOption) (*ApplyCloseIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCloseIntentResponse)
	err := c.cc.Invoke(ctx, ModelDevCommandService_ApplyCloseIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelDevCommandServiceServer is the server API for ModelDevCommandService service.
// All implementations must embed UnimplementedModelDevCommandServiceServer
// for forward compatibility.
//
// Only the authenticated Governance delivery identity may call this service.
// ACK is emitted after the command or close tombstone is durably committed.
type ModelDevCommandServiceServer interface {
	AcceptExecution(context.Context, *AcceptExecutionRequest) (*AcceptExecutionResponse, error)
	ApplyCloseIntent(context.Context, *ApplyCloseIntentRequest) (*ApplyCloseIntentResponse, error)
	mustEmbedUnimplementedModelDevCommandServiceServer()
}

// UnimplementedModelDevCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelDevCommandServiceServer struct{}

func (UnimplementedModelDevCommandServiceServer) AcceptExecution(context.Context, *AcceptExecutionRequest) (*AcceptExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptExecution not implemented")
}
func (UnimplementedModelDevCommandServiceServer) ApplyCloseIntent(context.Context, *ApplyCloseIntentRequest) (*ApplyCloseIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCloseIntent not implemented")
}
func (UnimplementedModelDevCommandServiceServer) mustEmbedUnimplementedModelDevCommandServiceServer() {
}
func (UnimplementedModelDevCommandServiceServer) testEmbeddedByValue() {}

// UnsafeModelDevCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelDevCommandServiceServer will
// result in compilation errors.
type UnsafeModelDevCommandServiceServer interface {
	mustEmbedUnimplementedModelDevCommandServiceServer()
}

func RegisterModelDevCommandServiceServer(s grpc.ServiceRegistrar, srv ModelDevCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedModelDevCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelDevCommandService_ServiceDesc, srv)
}

func _ModelDevCommandService_AcceptExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevCommandServiceServer).AcceptExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevCommandService_AcceptExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevCommandServiceServer).AcceptExecution(ctx, req.(*AcceptExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevCommandService_ApplyCloseIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCloseIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevCommandServiceServer).ApplyCloseIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevCommandService_ApplyCloseIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevCommandServiceServer).ApplyCloseIntent(ctx, req.(*ApplyCloseIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelDevCommandService_ServiceDesc is the grpc.ServiceDesc for ModelDevCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelDevCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ani.modeldev.v1.ModelDevCommandService",
	HandlerType: (*ModelDevCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcceptExecution",
			Handler:    _ModelDevCommandService_AcceptExecution_Handler,
		},
		{
			MethodName: "ApplyCloseIntent",
			Handler:    _ModelDevCommandService_ApplyCloseIntent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ani/modeldev/v1/modeldev.proto",
}

const (
	ModelDevStepService_BeginExecution_FullMethodName            = "/ani.modeldev.v1.ModelDevStepService/BeginExecution"
	ModelDevStepService_GetExecutionConfiguration_FullMethodName = "/ani.modeldev.v1.ModelDevStepService/GetExecutionConfiguration"
	ModelDevStepService_EnsureTraining_FullMethodName            = "/ani.modeldev.v1.ModelDevStepService/EnsureTraining"
	ModelDevStepService_GetTrainingStatus_FullMethodName         = "/ani.modeldev.v1.ModelDevStepService/GetTrainingStatus"
	ModelDevStepService_ReportStepResult_FullMethodName          = "/ani.modeldev.v1.ModelDevStepService/ReportStepResult"
	ModelDevStepService_RequestExecutionClose_FullMethodName     = "/ani.modeldev.v1.ModelDevStepService/RequestExecutionClose"
)

// ModelDevStepServiceClient is the client API for ModelDevStepService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Only authenticated managed KFP steps may call these capabilities. Claimed
// associations in requests must be verified against actual Run/Workflow/Pod
// identity; labels or caller-supplied IDs alone never authorize a callback.
type ModelDevStepServiceClient interface {
	BeginExecution(ctx context.Context, in *BeginExecutionRequest, opts ...grpc.CallOption) (*BeginExecutionResponse, error)
	GetExecutionConfiguration(ctx context.Context, in *GetExecutionConfigurationRequest, opts ...grpc.CallOption) (*GetExecutionConfigurationResponse, error)
	EnsureTraining(ctx context.Context, in *EnsureTrainingRequest, opts ...grpc.CallOption) (*EnsureTrainingResponse, error)
	GetTrainingStatus(ctx context.Context, in *GetTrainingStatusRequest, opts ...grpc.CallOption) (*GetTrainingStatusResponse, error)
	ReportStepResult(ctx context.Context, in *ReportStepResultRequest, opts ...grpc.CallOption) (*ReportStepResultResponse, error)
	RequestExecutionClose(ctx context.Context, in *RequestExecutionCloseRequest, opts ...grpc.CallOption) (*RequestExecutionCloseResponse, error)
}

type modelDevStepServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelDevStepServiceClient(cc grpc.ClientConnInterface) ModelDevStepServiceClient {
	return &modelDevStepServiceClient{cc}
}

func (c *modelDevStepServiceClient) BeginExecution(ctx context.Context, in *BeginExecutionRequest, opts ...grpc.CallOption) (*BeginExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginExecutionResponse)
	err := c.cc.Invoke(ctx, ModelDevStepService_BeginExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevStepServiceClient) GetExecutionConfiguration(ctx context.Context, in *GetExecutionConfigurationRequest, opts ...grpc.CallOption) (*GetExecutionConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExecutionConfigurationResponse)
	err := c.cc.Invoke(ctx, ModelDevStepService_GetExecutionConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevStepServiceClient) EnsureTraining(ctx context.Context, in *EnsureTrainingRequest, opts ...grpc.CallOption) (*EnsureTrainingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureTrainingResponse)
	err := c.cc.Invoke(ctx, ModelDevStepService_EnsureTraining_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevStepServiceClient) GetTrainingStatus(ctx context.Context, in *GetTrainingStatusRequest, opts ...grpc.CallOption) (*GetTrainingStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrainingStatusResponse)
	err := c.cc.Invoke(ctx, ModelDevStepService_GetTrainingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevStepServiceClient) ReportStepResult(ctx context.Context, in *ReportStepResultRequest, opts ...grpc.CallOption) (*ReportStepResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStepResultResponse)
	err := c.cc.Invoke(ctx, ModelDevStepService_ReportStepResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevStepServiceClient) RequestExecutionClose(ctx context.Context, in *RequestExecutionCloseRequest, opts ...grpc.CallOption) (*RequestExecutionCloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestExecutionCloseResponse)
	err := c.cc.Invoke(ctx, ModelDevStepService_RequestExecutionClose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelDevStepServiceServer is the server API for ModelDevStepService service.
// All implementations must embed UnimplementedModelDevStepServiceServer
// for forward compatibility.
//
// Only authenticated managed KFP steps may call these capabilities. Claimed
// associations in requests must be verified against actual Run/Workflow/Pod
// identity; labels or caller-supplied IDs alone never authorize a callback.
type ModelDevStepServiceServer interface {
	BeginExecution(context.Context, *BeginExecutionRequest) (*BeginExecutionResponse, error)
	GetExecutionConfiguration(context.Context, *GetExecutionConfigurationRequest) (*GetExecutionConfigurationResponse, error)
	EnsureTraining(context.Context, *EnsureTrainingRequest) (*EnsureTrainingResponse, error)
	GetTrainingStatus(context.Context, *GetTrainingStatusRequest) (*GetTrainingStatusResponse, error)
	ReportStepResult(context.Context, *ReportStepResultRequest) (*ReportStepResultResponse, error)
	RequestExecutionClose(context.Context, *RequestExecutionCloseRequest) (*RequestExecutionCloseResponse, error)
	mustEmbedUnimplementedModelDevStepServiceServer()
}

// UnimplementedModelDevStepServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelDevStepServiceServer struct{}

func (UnimplementedModelDevStepServiceServer) BeginExecution(context.Context, *BeginExecutionRequest) (*BeginExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginExecution not implemented")
}
func (UnimplementedModelDevStepServiceServer) GetExecutionConfiguration(context.Context, *GetExecutionConfigurationRequest) (*GetExecutionConfigurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecutionConfiguration not implemented")
}
func (UnimplementedModelDevStepServiceServer) EnsureTraining(context.Context, *EnsureTrainingRequest) (*EnsureTrainingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureTraining not implemented")
}
func (UnimplementedModelDevStepServiceServer) GetTrainingStatus(context.Context, *GetTrainingStatusRequest) (*GetTrainingStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrainingStatus not implemented")
}
func (UnimplementedModelDevStepServiceServer) ReportStepResult(context.Context, *ReportStepResultRequest) (*ReportStepResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStepResult not implemented")
}
func (UnimplementedModelDevStepServiceServer) RequestExecutionClose(context.Context, *RequestExecutionCloseRequest) (*RequestExecutionCloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestExecutionClose not implemented")
}
func (UnimplementedModelDevStepServiceServer) mustEmbedUnimplementedModelDevStepServiceServer() {}
func (UnimplementedModelDevStepServiceServer) testEmbeddedByValue()                             {}

// UnsafeModelDevStepServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelDevStepServiceServer will
// result in compilation errors.
type UnsafeModelDevStepServiceServer interface {
	mustEmbedUnimplementedModelDevStepServiceServer()
}

func RegisterModelDevStepServiceServer(s grpc.ServiceRegistrar, srv ModelDevStepServiceServer) {
	// If the following call panics, it indicates UnimplementedModelDevStepServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelDevStepService_ServiceDesc, srv)
}

func _ModelDevStepService_BeginExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevStepServiceServer).BeginExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevStepService_BeginExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevStepServiceServer).BeginExecution(ctx, req.(*BeginExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevStepService_GetExecutionConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevStepServiceServer).GetExecutionConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevStepService_GetExecutionConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevStepServiceServer).GetExecutionConfiguration(ctx, req.(*GetExecutionConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevStepService_EnsureTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureTrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevStepServiceServer).EnsureTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevStepService_EnsureTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevStepServiceServer).EnsureTraining(ctx, req.(*EnsureTrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevStepService_GetTrainingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrainingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevStepServiceServer).GetTrainingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevStepService_GetTrainingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevStepServiceServer).GetTrainingStatus(ctx, req.(*GetTrainingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevStepService_ReportStepResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStepResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevStepServiceServer).ReportStepResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevStepService_ReportStepResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevStepServiceServer).ReportStepResult(ctx, req.(*ReportStepResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevStepService_RequestExecutionClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestExecutionCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevStepServiceServer).RequestExecutionClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevStepService_RequestExecutionClose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevStepServiceServer).RequestExecutionClose(ctx, req.(*RequestExecutionCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelDevStepService_ServiceDesc is the grpc.ServiceDesc for ModelDevStepService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelDevStepService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ani.modeldev.v1.ModelDevStepService",
	HandlerType: (*ModelDevStepServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginExecution",
			Handler:    _ModelDevStepService_BeginExecution_Handler,
		},
		{
			MethodName: "GetExecutionConfiguration",
			Handler:    _ModelDevStepService_GetExecutionConfiguration_Handler,
		},
		{
			MethodName: "EnsureTraining",
			Handler:    _ModelDevStepService_EnsureTraining_Handler,
		},
		{
			MethodName: "GetTrainingStatus",
			Handler:    _ModelDevStepService_GetTrainingStatus_Handler,
		},
		{
			MethodName: "ReportStepResult",
			Handler:    _ModelDevStepService_ReportStepResult_Handler,
		},
		{
			MethodName: "RequestExecutionClose",
			Handler:    _ModelDevStepService_RequestExecutionClose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ani/modeldev/v1/modeldev.proto",
}
