// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ani/modeldev/v1/operations.proto

package modeldevv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InspectExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectExecutionRequest) Reset() {
	*x = InspectExecutionRequest{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectExecutionRequest) ProtoMessage() {}

func (x *InspectExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectExecutionRequest.ProtoReflect.Descriptor instead.
func (*InspectExecutionRequest) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{0}
}

func (x *InspectExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ReconcileExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileExecutionRequest) Reset() {
	*x = ReconcileExecutionRequest{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileExecutionRequest) ProtoMessage() {}

func (x *ReconcileExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileExecutionRequest.ProtoReflect.Descriptor instead.
func (*ReconcileExecutionRequest) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{1}
}

func (x *ReconcileExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type PlanExecutionCleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanExecutionCleanupRequest) Reset() {
	*x = PlanExecutionCleanupRequest{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanExecutionCleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanExecutionCleanupRequest) ProtoMessage() {}

func (x *PlanExecutionCleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanExecutionCleanupRequest.ProtoReflect.Descriptor instead.
func (*PlanExecutionCleanupRequest) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{2}
}

func (x *PlanExecutionCleanupRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// The server reconstructs the original exact-UID plan and revalidates it;
// clients cannot choose a namespace, arbitrary resource, or desired state.
type ApplyExecutionCleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	PlanSha256    string                 `protobuf:"bytes,2,opt,name=plan_sha256,json=planSha256,proto3" json:"plan_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyExecutionCleanupRequest) Reset() {
	*x = ApplyExecutionCleanupRequest{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyExecutionCleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyExecutionCleanupRequest) ProtoMessage() {}

func (x *ApplyExecutionCleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyExecutionCleanupRequest.ProtoReflect.Descriptor instead.
func (*ApplyExecutionCleanupRequest) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyExecutionCleanupRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ApplyExecutionCleanupRequest) GetPlanSha256() string {
	if x != nil {
		return x.PlanSha256
	}
	return ""
}

type OperationResource struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion       string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind             string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace        string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Uid              string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	OwnerUid         string                 `protobuf:"bytes,6,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`
	ApiObjectPresent bool                   `protobuf:"varint,7,opt,name=api_object_present,json=apiObjectPresent,proto3" json:"api_object_present,omitempty"`
	CreationDisabled bool                   `protobuf:"varint,8,opt,name=creation_disabled,json=creationDisabled,proto3" json:"creation_disabled,omitempty"`
	Terminal         bool                   `protobuf:"varint,9,opt,name=terminal,proto3" json:"terminal,omitempty"`
	ExitCode         *int32                 `protobuf:"varint,10,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OperationResource) Reset() {
	*x = OperationResource{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResource) ProtoMessage() {}

func (x *OperationResource) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResource.ProtoReflect.Descriptor instead.
func (*OperationResource) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{4}
}

func (x *OperationResource) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OperationResource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OperationResource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OperationResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperationResource) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *OperationResource) GetOwnerUid() string {
	if x != nil {
		return x.OwnerUid
	}
	return ""
}

func (x *OperationResource) GetApiObjectPresent() bool {
	if x != nil {
		return x.ApiObjectPresent
	}
	return false
}

func (x *OperationResource) GetCreationDisabled() bool {
	if x != nil {
		return x.CreationDisabled
	}
	return false
}

func (x *OperationResource) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *OperationResource) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

type InspectExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inspection    *ExecutionInspection   `protobuf:"bytes,1,opt,name=inspection,proto3" json:"inspection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectExecutionResponse) Reset() {
	*x = InspectExecutionResponse{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectExecutionResponse) ProtoMessage() {}

func (x *InspectExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectExecutionResponse.ProtoReflect.Descriptor instead.
func (*InspectExecutionResponse) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{5}
}

func (x *InspectExecutionResponse) GetInspection() *ExecutionInspection {
	if x != nil {
		return x.Inspection
	}
	return nil
}

type ReconcileExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inspection    *ExecutionInspection   `protobuf:"bytes,1,opt,name=inspection,proto3" json:"inspection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileExecutionResponse) Reset() {
	*x = ReconcileExecutionResponse{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileExecutionResponse) ProtoMessage() {}

func (x *ReconcileExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileExecutionResponse.ProtoReflect.Descriptor instead.
func (*ReconcileExecutionResponse) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{6}
}

func (x *ReconcileExecutionResponse) GetInspection() *ExecutionInspection {
	if x != nil {
		return x.Inspection
	}
	return nil
}

type ExecutionInspection struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId            string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	OperationId            string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionSpecHash      string                 `protobuf:"bytes,3,opt,name=execution_spec_hash,json=executionSpecHash,proto3" json:"execution_spec_hash,omitempty"`
	OwnerRevision          uint64                 `protobuf:"varint,4,opt,name=owner_revision,json=ownerRevision,proto3" json:"owner_revision,omitempty"`
	Namespace              string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NamespaceUid           string                 `protobuf:"bytes,6,opt,name=namespace_uid,json=namespaceUid,proto3" json:"namespace_uid,omitempty"`
	RunId                  string                 `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowUid            string                 `protobuf:"bytes,8,opt,name=workflow_uid,json=workflowUid,proto3" json:"workflow_uid,omitempty"`
	PvcUid                 string                 `protobuf:"bytes,9,opt,name=pvc_uid,json=pvcUid,proto3" json:"pvc_uid,omitempty"`
	Resources              []*OperationResource   `protobuf:"bytes,10,rep,name=resources,proto3" json:"resources,omitempty"`
	ComputeState           string                 `protobuf:"bytes,11,opt,name=compute_state,json=computeState,proto3" json:"compute_state,omitempty"`
	DeliveryState          string                 `protobuf:"bytes,12,opt,name=delivery_state,json=deliveryState,proto3" json:"delivery_state,omitempty"`
	CloseState             string                 `protobuf:"bytes,13,opt,name=close_state,json=closeState,proto3" json:"close_state,omitempty"`
	DispatchState          string                 `protobuf:"bytes,14,opt,name=dispatch_state,json=dispatchState,proto3" json:"dispatch_state,omitempty"`
	RunCreateInFlight      bool                   `protobuf:"varint,15,opt,name=run_create_in_flight,json=runCreateInFlight,proto3" json:"run_create_in_flight,omitempty"`
	TrainingCreateInFlight bool                   `protobuf:"varint,16,opt,name=training_create_in_flight,json=trainingCreateInFlight,proto3" json:"training_create_in_flight,omitempty"`
	CloseGeneration        uint64                 `protobuf:"varint,17,opt,name=close_generation,json=closeGeneration,proto3" json:"close_generation,omitempty"`
	CloseReason            string                 `protobuf:"bytes,18,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"`
	CloseReviewReason      string                 `protobuf:"bytes,19,opt,name=close_review_reason,json=closeReviewReason,proto3" json:"close_review_reason,omitempty"`
	ClosedAt               *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	PublicationId          string                 `protobuf:"bytes,21,opt,name=publication_id,json=publicationId,proto3" json:"publication_id,omitempty"`
	ObservedAt             *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	RetrievedAt            *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=retrieved_at,json=retrievedAt,proto3" json:"retrieved_at,omitempty"`
	ObservationStale       bool                   `protobuf:"varint,24,opt,name=observation_stale,json=observationStale,proto3" json:"observation_stale,omitempty"`
	ComputeOutcome         string                 `protobuf:"bytes,25,opt,name=compute_outcome,json=computeOutcome,proto3" json:"compute_outcome,omitempty"`
	CleanupPhase           string                 `protobuf:"bytes,26,opt,name=cleanup_phase,json=cleanupPhase,proto3" json:"cleanup_phase,omitempty"`
	CleanupPlanSha256      string                 `protobuf:"bytes,27,opt,name=cleanup_plan_sha256,json=cleanupPlanSha256,proto3" json:"cleanup_plan_sha256,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExecutionInspection) Reset() {
	*x = ExecutionInspection{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionInspection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionInspection) ProtoMessage() {}

func (x *ExecutionInspection) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionInspection.ProtoReflect.Descriptor instead.
func (*ExecutionInspection) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionInspection) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionInspection) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ExecutionInspection) GetExecutionSpecHash() string {
	if x != nil {
		return x.ExecutionSpecHash
	}
	return ""
}

func (x *ExecutionInspection) GetOwnerRevision() uint64 {
	if x != nil {
		return x.OwnerRevision
	}
	return 0
}

func (x *ExecutionInspection) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExecutionInspection) GetNamespaceUid() string {
	if x != nil {
		return x.NamespaceUid
	}
	return ""
}

func (x *ExecutionInspection) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionInspection) GetWorkflowUid() string {
	if x != nil {
		return x.WorkflowUid
	}
	return ""
}

func (x *ExecutionInspection) GetPvcUid() string {
	if x != nil {
		return x.PvcUid
	}
	return ""
}

func (x *ExecutionInspection) GetResources() []*OperationResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ExecutionInspection) GetComputeState() string {
	if x != nil {
		return x.ComputeState
	}
	return ""
}

func (x *ExecutionInspection) GetDeliveryState() string {
	if x != nil {
		return x.DeliveryState
	}
	return ""
}

func (x *ExecutionInspection) GetCloseState() string {
	if x != nil {
		return x.CloseState
	}
	return ""
}

func (x *ExecutionInspection) GetDispatchState() string {
	if x != nil {
		return x.DispatchState
	}
	return ""
}

func (x *ExecutionInspection) GetRunCreateInFlight() bool {
	if x != nil {
		return x.RunCreateInFlight
	}
	return false
}

func (x *ExecutionInspection) GetTrainingCreateInFlight() bool {
	if x != nil {
		return x.TrainingCreateInFlight
	}
	return false
}

func (x *ExecutionInspection) GetCloseGeneration() uint64 {
	if x != nil {
		return x.CloseGeneration
	}
	return 0
}

func (x *ExecutionInspection) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *ExecutionInspection) GetCloseReviewReason() string {
	if x != nil {
		return x.CloseReviewReason
	}
	return ""
}

func (x *ExecutionInspection) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *ExecutionInspection) GetPublicationId() string {
	if x != nil {
		return x.PublicationId
	}
	return ""
}

func (x *ExecutionInspection) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *ExecutionInspection) GetRetrievedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RetrievedAt
	}
	return nil
}

func (x *ExecutionInspection) GetObservationStale() bool {
	if x != nil {
		return x.ObservationStale
	}
	return false
}

func (x *ExecutionInspection) GetComputeOutcome() string {
	if x != nil {
		return x.ComputeOutcome
	}
	return ""
}

func (x *ExecutionInspection) GetCleanupPhase() string {
	if x != nil {
		return x.CleanupPhase
	}
	return ""
}

func (x *ExecutionInspection) GetCleanupPlanSha256() string {
	if x != nil {
		return x.CleanupPlanSha256
	}
	return ""
}

type PlanExecutionCleanupResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId       string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	OperationId       string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionSpecHash string                 `protobuf:"bytes,3,opt,name=execution_spec_hash,json=executionSpecHash,proto3" json:"execution_spec_hash,omitempty"`
	OwnerRevision     uint64                 `protobuf:"varint,4,opt,name=owner_revision,json=ownerRevision,proto3" json:"owner_revision,omitempty"`
	CloseGeneration   uint64                 `protobuf:"varint,5,opt,name=close_generation,json=closeGeneration,proto3" json:"close_generation,omitempty"`
	NamespaceUid      string                 `protobuf:"bytes,6,opt,name=namespace_uid,json=namespaceUid,proto3" json:"namespace_uid,omitempty"`
	PublicationId     string                 `protobuf:"bytes,7,opt,name=publication_id,json=publicationId,proto3" json:"publication_id,omitempty"`
	Targets           []*OperationResource   `protobuf:"bytes,8,rep,name=targets,proto3" json:"targets,omitempty"`
	PlanSha256        string                 `protobuf:"bytes,9,opt,name=plan_sha256,json=planSha256,proto3" json:"plan_sha256,omitempty"`
	Retained          []string               `protobuf:"bytes,10,rep,name=retained,proto3" json:"retained,omitempty"`
	ObservedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanExecutionCleanupResponse) Reset() {
	*x = PlanExecutionCleanupResponse{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanExecutionCleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanExecutionCleanupResponse) ProtoMessage() {}

func (x *PlanExecutionCleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanExecutionCleanupResponse.ProtoReflect.Descriptor instead.
func (*PlanExecutionCleanupResponse) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{8}
}

func (x *PlanExecutionCleanupResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *PlanExecutionCleanupResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *PlanExecutionCleanupResponse) GetExecutionSpecHash() string {
	if x != nil {
		return x.ExecutionSpecHash
	}
	return ""
}

func (x *PlanExecutionCleanupResponse) GetOwnerRevision() uint64 {
	if x != nil {
		return x.OwnerRevision
	}
	return 0
}

func (x *PlanExecutionCleanupResponse) GetCloseGeneration() uint64 {
	if x != nil {
		return x.CloseGeneration
	}
	return 0
}

func (x *PlanExecutionCleanupResponse) GetNamespaceUid() string {
	if x != nil {
		return x.NamespaceUid
	}
	return ""
}

func (x *PlanExecutionCleanupResponse) GetPublicationId() string {
	if x != nil {
		return x.PublicationId
	}
	return ""
}

func (x *PlanExecutionCleanupResponse) GetTargets() []*OperationResource {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *PlanExecutionCleanupResponse) GetPlanSha256() string {
	if x != nil {
		return x.PlanSha256
	}
	return ""
}

func (x *PlanExecutionCleanupResponse) GetRetained() []string {
	if x != nil {
		return x.Retained
	}
	return nil
}

func (x *PlanExecutionCleanupResponse) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type ApplyExecutionCleanupResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId     string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	PlanSha256      string                 `protobuf:"bytes,2,opt,name=plan_sha256,json=planSha256,proto3" json:"plan_sha256,omitempty"`
	Phase           string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Requested       []*OperationResource   `protobuf:"bytes,4,rep,name=requested,proto3" json:"requested,omitempty"`
	ConfirmedAbsent []*OperationResource   `protobuf:"bytes,5,rep,name=confirmed_absent,json=confirmedAbsent,proto3" json:"confirmed_absent,omitempty"`
	Actor           string                 `protobuf:"bytes,6,opt,name=actor,proto3" json:"actor,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyExecutionCleanupResponse) Reset() {
	*x = ApplyExecutionCleanupResponse{}
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyExecutionCleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyExecutionCleanupResponse) ProtoMessage() {}

func (x *ApplyExecutionCleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ani_modeldev_v1_operations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyExecutionCleanupResponse.ProtoReflect.Descriptor instead.
func (*ApplyExecutionCleanupResponse) Descriptor() ([]byte, []int) {
	return file_ani_modeldev_v1_operations_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyExecutionCleanupResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ApplyExecutionCleanupResponse) GetPlanSha256() string {
	if x != nil {
		return x.PlanSha256
	}
	return ""
}

func (x *ApplyExecutionCleanupResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ApplyExecutionCleanupResponse) GetRequested() []*OperationResource {
	if x != nil {
		return x.Requested
	}
	return nil
}

func (x *ApplyExecutionCleanupResponse) GetConfirmedAbsent() []*OperationResource {
	if x != nil {
		return x.ConfirmedAbsent
	}
	return nil
}

func (x *ApplyExecutionCleanupResponse) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ApplyExecutionCleanupResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ApplyExecutionCleanupResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_ani_modeldev_v1_operations_proto protoreflect.FileDescriptor

const file_ani_modeldev_v1_operations_proto_rawDesc = "" +
	"\n" +
	" ani/modeldev/v1/operations.proto\x12\x0fani.modeldev.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x17InspectExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\">\n" +
	"\x19ReconcileExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"@\n" +
	"\x1bPlanExecutionCleanupRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"b\n" +
	"\x1cApplyExecutionCleanupRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1f\n" +
	"\vplan_sha256\x18\x02 \x01(\tR\n" +
	"planSha256\"\xd0\x02\n" +
	"\x11OperationResource\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12\x1b\n" +
	"\towner_uid\x18\x06 \x01(\tR\bownerUid\x12,\n" +
	"\x12api_object_present\x18\a \x01(\bR\x10apiObjectPresent\x12+\n" +
	"\x11creation_disabled\x18\b \x01(\bR\x10creationDisabled\x12\x1a\n" +
	"\bterminal\x18\t \x01(\bR\bterminal\x12 \n" +
	"\texit_code\x18\n" +
	" \x01(\x05H\x00R\bexitCode\x88\x01\x01B\f\n" +
	"\n" +
	"_exit_code\"`\n" +
	"\x18InspectExecutionResponse\x12D\n" +
	"\n" +
	"inspection\x18\x01 \x01(\v2$.ani.modeldev.v1.ExecutionInspectionR\n" +
	"inspection\"b\n" +
	"\x1aReconcileExecutionResponse\x12D\n" +
	"\n" +
	"inspection\x18\x01 \x01(\v2$.ani.modeldev.v1.ExecutionInspectionR\n" +
	"inspection\"\x8f\t\n" +
	"\x13ExecutionInspection\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12.\n" +
	"\x13execution_spec_hash\x18\x03 \x01(\tR\x11executionSpecHash\x12%\n" +
	"\x0eowner_revision\x18\x04 \x01(\x04R\rownerRevision\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12#\n" +
	"\rnamespace_uid\x18\x06 \x01(\tR\fnamespaceUid\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\x12!\n" +
	"\fworkflow_uid\x18\b \x01(\tR\vworkflowUid\x12\x17\n" +
	"\apvc_uid\x18\t \x01(\tR\x06pvcUid\x12@\n" +
	"\tresources\x18\n" +
	" \x03(\v2\".ani.modeldev.v1.OperationResourceR\tresources\x12#\n" +
	"\rcompute_state\x18\v \x01(\tR\fcomputeState\x12%\n" +
	"\x0edelivery_state\x18\f \x01(\tR\rdeliveryState\x12\x1f\n" +
	"\vclose_state\x18\r \x01(\tR\n" +
	"closeState\x12%\n" +
	"\x0edispatch_state\x18\x0e \x01(\tR\rdispatchState\x12/\n" +
	"\x14run_create_in_flight\x18\x0f \x01(\bR\x11runCreateInFlight\x129\n" +
	"\x19training_create_in_flight\x18\x10 \x01(\bR\x16trainingCreateInFlight\x12)\n" +
	"\x10close_generation\x18\x11 \x01(\x04R\x0fcloseGeneration\x12!\n" +
	"\fclose_reason\x18\x12 \x01(\tR\vcloseReason\x12.\n" +
	"\x13close_review_reason\x18\x13 \x01(\tR\x11closeReviewReason\x127\n" +
	"\tclosed_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x12%\n" +
	"\x0epublication_id\x18\x15 \x01(\tR\rpublicationId\x12;\n" +
	"\vobserved_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12=\n" +
	"\fretrieved_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\vretrievedAt\x12+\n" +
	"\x11observation_stale\x18\x18 \x01(\bR\x10observationStale\x12'\n" +
	"\x0fcompute_outcome\x18\x19 \x01(\tR\x0ecomputeOutcome\x12#\n" +
	"\rcleanup_phase\x18\x1a \x01(\tR\fcleanupPhase\x12.\n" +
	"\x13cleanup_plan_sha256\x18\x1b \x01(\tR\x11cleanupPlanSha256\"\xea\x03\n" +
	"\x1cPlanExecutionCleanupResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12.\n" +
	"\x13execution_spec_hash\x18\x03 \x01(\tR\x11executionSpecHash\x12%\n" +
	"\x0eowner_revision\x18\x04 \x01(\x04R\rownerRevision\x12)\n" +
	"\x10close_generation\x18\x05 \x01(\x04R\x0fcloseGeneration\x12#\n" +
	"\rnamespace_uid\x18\x06 \x01(\tR\fnamespaceUid\x12%\n" +
	"\x0epublication_id\x18\a \x01(\tR\rpublicationId\x12<\n" +
	"\atargets\x18\b \x03(\v2\".ani.modeldev.v1.OperationResourceR\atargets\x12\x1f\n" +
	"\vplan_sha256\x18\t \x01(\tR\n" +
	"planSha256\x12\x1a\n" +
	"\bretained\x18\n" +
	" \x03(\tR\bretained\x12;\n" +
	"\vobserved_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\x9a\x03\n" +
	"\x1dApplyExecutionCleanupResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1f\n" +
	"\vplan_sha256\x18\x02 \x01(\tR\n" +
	"planSha256\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12@\n" +
	"\trequested\x18\x04 \x03(\v2\".ani.modeldev.v1.OperationResourceR\trequested\x12M\n" +
	"\x10confirmed_absent\x18\x05 \x03(\v2\".ani.modeldev.v1.OperationResourceR\x0fconfirmedAbsent\x12\x14\n" +
	"\x05actor\x18\x06 \x01(\tR\x05actor\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt2\xe0\x03\n" +
	"\x19ModelDevOperationsService\x12g\n" +
	"\x10InspectExecution\x12(.ani.modeldev.v1.InspectExecutionRequest\x1a).ani.modeldev.v1.InspectExecutionResponse\x12m\n" +
	"\x12ReconcileExecution\x12*.ani.modeldev.v1.ReconcileExecutionRequest\x1a+.ani.modeldev.v1.ReconcileExecutionResponse\x12s\n" +
	"\x14PlanExecutionCleanup\x12,.ani.modeldev.v1.PlanExecutionCleanupRequest\x1a-.ani.modeldev.v1.PlanExecutionCleanupResponse\x12v\n" +
	"\x15ApplyExecutionCleanup\x12-.ani.modeldev.v1.ApplyExecutionCleanupRequest\x1a..ani.modeldev.v1.ApplyExecutionCleanupResponseBNZLgithub.com/zhangzhe-ctrl/ani-modeldev-service/api/ani/modeldev/v1;modeldevv1b\x06proto3"

var (
	file_ani_modeldev_v1_operations_proto_rawDescOnce sync.Once
	file_ani_modeldev_v1_operations_proto_rawDescData []byte
)

func file_ani_modeldev_v1_operations_proto_rawDescGZIP() []byte {
	file_ani_modeldev_v1_operations_proto_rawDescOnce.Do(func() {
		file_ani_modeldev_v1_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ani_modeldev_v1_operations_proto_rawDesc), len(file_ani_modeldev_v1_operations_proto_rawDesc)))
	})
	return file_ani_modeldev_v1_operations_proto_rawDescData
}

var file_ani_modeldev_v1_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ani_modeldev_v1_operations_proto_goTypes = []any{
	(*InspectExecutionRequest)(nil),       // 0: ani.modeldev.v1.InspectExecutionRequest
	(*ReconcileExecutionRequest)(nil),     // 1: ani.modeldev.v1.ReconcileExecutionRequest
	(*PlanExecutionCleanupRequest)(nil),   // 2: ani.modeldev.v1.PlanExecutionCleanupRequest
	(*ApplyExecutionCleanupRequest)(nil),  // 3: ani.modeldev.v1.ApplyExecutionCleanupRequest
	(*OperationResource)(nil),             // 4: ani.modeldev.v1.OperationResource
	(*InspectExecutionResponse)(nil),      // 5: ani.modeldev.v1.InspectExecutionResponse
	(*ReconcileExecutionResponse)(nil),    // 6: ani.modeldev.v1.ReconcileExecutionResponse
	(*ExecutionInspection)(nil),           // 7: ani.modeldev.v1.ExecutionInspection
	(*PlanExecutionCleanupResponse)(nil),  // 8: ani.modeldev.v1.PlanExecutionCleanupResponse
	(*ApplyExecutionCleanupResponse)(nil), // 9: ani.modeldev.v1.ApplyExecutionCleanupResponse
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
}
var file_ani_modeldev_v1_operations_proto_depIdxs = []int32{
	7,  // 0: ani.modeldev.v1.InspectExecutionResponse.inspection:type_name -> ani.modeldev.v1.ExecutionInspection
	7,  // 1: ani.modeldev.v1.ReconcileExecutionResponse.inspection:type_name -> ani.modeldev.v1.ExecutionInspection
	4,  // 2: ani.modeldev.v1.ExecutionInspection.resources:type_name -> ani.modeldev.v1.OperationResource
	10, // 3: ani.modeldev.v1.ExecutionInspection.closed_at:type_name -> google.protobuf.Timestamp
	10, // 4: ani.modeldev.v1.ExecutionInspection.observed_at:type_name -> google.protobuf.Timestamp
	10, // 5: ani.modeldev.v1.ExecutionInspection.retrieved_at:type_name -> google.protobuf.Timestamp
	4,  // 6: ani.modeldev.v1.PlanExecutionCleanupResponse.targets:type_name -> ani.modeldev.v1.OperationResource
	10, // 7: ani.modeldev.v1.PlanExecutionCleanupResponse.observed_at:type_name -> google.protobuf.Timestamp
	4,  // 8: ani.modeldev.v1.ApplyExecutionCleanupResponse.requested:type_name -> ani.modeldev.v1.OperationResource
	4,  // 9: ani.modeldev.v1.ApplyExecutionCleanupResponse.confirmed_absent:type_name -> ani.modeldev.v1.OperationResource
	10, // 10: ani.modeldev.v1.ApplyExecutionCleanupResponse.started_at:type_name -> google.protobuf.Timestamp
	10, // 11: ani.modeldev.v1.ApplyExecutionCleanupResponse.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 12: ani.modeldev.v1.ModelDevOperationsService.InspectExecution:input_type -> ani.modeldev.v1.InspectExecutionRequest
	1,  // 13: ani.modeldev.v1.ModelDevOperationsService.ReconcileExecution:input_type -> ani.modeldev.v1.ReconcileExecutionRequest
	2,  // 14: ani.modeldev.v1.ModelDevOperationsService.PlanExecutionCleanup:input_type -> ani.modeldev.v1.PlanExecutionCleanupRequest
	3,  // 15: ani.modeldev.v1.ModelDevOperationsService.ApplyExecutionCleanup:input_type -> ani.modeldev.v1.ApplyExecutionCleanupRequest
	5,  // 16: ani.modeldev.v1.ModelDevOperationsService.InspectExecution:output_type -> ani.modeldev.v1.InspectExecutionResponse
	6,  // 17: ani.modeldev.v1.ModelDevOperationsService.ReconcileExecution:output_type -> ani.modeldev.v1.ReconcileExecutionResponse
	8,  // 18: ani.modeldev.v1.ModelDevOperationsService.PlanExecutionCleanup:output_type -> ani.modeldev.v1.PlanExecutionCleanupResponse
	9,  // 19: ani.modeldev.v1.ModelDevOperationsService.ApplyExecutionCleanup:output_type -> ani.modeldev.v1.ApplyExecutionCleanupResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_ani_modeldev_v1_operations_proto_init() }
func file_ani_modeldev_v1_operations_proto_init() {
	if File_ani_modeldev_v1_operations_proto != nil {
		return
	}
	file_ani_modeldev_v1_operations_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ani_modeldev_v1_operations_proto_rawDesc), len(file_ani_modeldev_v1_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ani_modeldev_v1_operations_proto_goTypes,
		DependencyIndexes: file_ani_modeldev_v1_operations_proto_depIdxs,
		MessageInfos:      file_ani_modeldev_v1_operations_proto_msgTypes,
	}.Build()
	File_ani_modeldev_v1_operations_proto = out.File
	file_ani_modeldev_v1_operations_proto_goTypes = nil
	file_ani_modeldev_v1_operations_proto_depIdxs = nil
}
