// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ani/modeldev/v1/operations.proto

package modeldevv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelDevOperationsService_InspectExecution_FullMethodName      = "/ani.modeldev.v1.ModelDevOperationsService/InspectExecution"
	ModelDevOperationsService_ReconcileExecution_FullMethodName    = "/ani.modeldev.v1.ModelDevOperationsService/ReconcileExecution"
	ModelDevOperationsService_PlanExecutionCleanup_FullMethodName  = "/ani.modeldev.v1.ModelDevOperationsService/PlanExecutionCleanup"
	ModelDevOperationsService_ApplyExecutionCleanup_FullMethodName = "/ani.modeldev.v1.ModelDevOperationsService/ApplyExecutionCleanup"
)

// ModelDevOperationsServiceClient is the client API for ModelDevOperationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dedicated platform operations. The mTLS Governance caller must delegate
// current exact-method/tenant-wide authorization on every request.
type ModelDevOperationsServiceClient interface {
	InspectExecution(ctx context.Context, in *InspectExecutionRequest, opts ...grpc.CallOption) (*InspectExecutionResponse, error)
	ReconcileExecution(ctx context.Context, in *ReconcileExecutionRequest, opts ...grpc.CallOption) (*ReconcileExecutionResponse, error)
	PlanExecutionCleanup(ctx context.Context, in *PlanExecutionCleanupRequest, opts ...grpc.CallOption) (*PlanExecutionCleanupResponse, error)
	ApplyExecutionCleanup(ctx context.Context, in *ApplyExecutionCleanupRequest, opts ...grpc.CallOption) (*ApplyExecutionCleanupResponse, error)
}

type modelDevOperationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelDevOperationsServiceClient(cc grpc.ClientConnInterface) ModelDevOperationsServiceClient {
	return &modelDevOperationsServiceClient{cc}
}

func (c *modelDevOperationsServiceClient) InspectExecution(ctx context.Context, in *InspectExecutionRequest, opts ...grpc.CallOption) (*InspectExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectExecutionResponse)
	err := c.cc.Invoke(ctx, ModelDevOperationsService_InspectExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevOperationsServiceClient) ReconcileExecution(ctx context.Context, in *ReconcileExecutionRequest, opts ...grpc.CallOption) (*ReconcileExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileExecutionResponse)
	err := c.cc.Invoke(ctx, ModelDevOperationsService_ReconcileExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevOperationsServiceClient) PlanExecutionCleanup(ctx context.Context, in *PlanExecutionCleanupRequest, opts ...grpc.CallOption) (*PlanExecutionCleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanExecutionCleanupResponse)
	err := c.cc.Invoke(ctx, ModelDevOperationsService_PlanExecutionCleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDevOperationsServiceClient) ApplyExecutionCleanup(ctx context.Context, in *ApplyExecutionCleanupRequest, opts ...grpc.CallOption) (*ApplyExecutionCleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyExecutionCleanupResponse)
	err := c.cc.Invoke(ctx, ModelDevOperationsService_ApplyExecutionCleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelDevOperationsServiceServer is the server API for ModelDevOperationsService service.
// All implementations must embed UnimplementedModelDevOperationsServiceServer
// for forward compatibility.
//
// Dedicated platform operations. The mTLS Governance caller must delegate
// current exact-method/tenant-wide authorization on every request.
type ModelDevOperationsServiceServer interface {
	InspectExecution(context.Context, *InspectExecutionRequest) (*InspectExecutionResponse, error)
	ReconcileExecution(context.Context, *ReconcileExecutionRequest) (*ReconcileExecutionResponse, error)
	PlanExecutionCleanup(context.Context, *PlanExecutionCleanupRequest) (*PlanExecutionCleanupResponse, error)
	ApplyExecutionCleanup(context.Context, *ApplyExecutionCleanupRequest) (*ApplyExecutionCleanupResponse, error)
	mustEmbedUnimplementedModelDevOperationsServiceServer()
}

// UnimplementedModelDevOperationsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelDevOperationsServiceServer struct{}

func (UnimplementedModelDevOperationsServiceServer) InspectExecution(context.Context, *InspectExecutionRequest) (*InspectExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectExecution not implemented")
}
func (UnimplementedModelDevOperationsServiceServer) ReconcileExecution(context.Context, *ReconcileExecutionRequest) (*ReconcileExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileExecution not implemented")
}
func (UnimplementedModelDevOperationsServiceServer) PlanExecutionCleanup(context.Context, *PlanExecutionCleanupRequest) (*PlanExecutionCleanupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanExecutionCleanup not implemented")
}
func (UnimplementedModelDevOperationsServiceServer) ApplyExecutionCleanup(context.Context, *ApplyExecutionCleanupRequest) (*ApplyExecutionCleanupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyExecutionCleanup not implemented")
}
func (UnimplementedModelDevOperationsServiceServer) mustEmbedUnimplementedModelDevOperationsServiceServer() {
}
func (UnimplementedModelDevOperationsServiceServer) testEmbeddedByValue() {}

// UnsafeModelDevOperationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelDevOperationsServiceServer will
// result in compilation errors.
type UnsafeModelDevOperationsServiceServer interface {
	mustEmbedUnimplementedModelDevOperationsServiceServer()
}

func RegisterModelDevOperationsServiceServer(s grpc.ServiceRegistrar, srv ModelDevOperationsServiceServer) {
	// If the following call panics, it indicates UnimplementedModelDevOperationsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelDevOperationsService_ServiceDesc, srv)
}

func _ModelDevOperationsService_InspectExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevOperationsServiceServer).InspectExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevOperationsService_InspectExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevOperationsServiceServer).InspectExecution(ctx, req.(*InspectExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevOperationsService_ReconcileExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevOperationsServiceServer).ReconcileExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevOperationsService_ReconcileExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevOperationsServiceServer).ReconcileExecution(ctx, req.(*ReconcileExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevOperationsService_PlanExecutionCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanExecutionCleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevOperationsServiceServer).PlanExecutionCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevOperationsService_PlanExecutionCleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevOperationsServiceServer).PlanExecutionCleanup(ctx, req.(*PlanExecutionCleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelDevOperationsService_ApplyExecutionCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyExecutionCleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDevOperationsServiceServer).ApplyExecutionCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelDevOperationsService_ApplyExecutionCleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDevOperationsServiceServer).ApplyExecutionCleanup(ctx, req.(*ApplyExecutionCleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelDevOperationsService_ServiceDesc is the grpc.ServiceDesc for ModelDevOperationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelDevOperationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ani.modeldev.v1.ModelDevOperationsService",
	HandlerType: (*ModelDevOperationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InspectExecution",
			Handler:    _ModelDevOperationsService_InspectExecution_Handler,
		},
		{
			MethodName: "ReconcileExecution",
			Handler:    _ModelDevOperationsService_ReconcileExecution_Handler,
		},
		{
			MethodName: "PlanExecutionCleanup",
			Handler:    _ModelDevOperationsService_PlanExecutionCleanup_Handler,
		},
		{
			MethodName: "ApplyExecutionCleanup",
			Handler:    _ModelDevOperationsService_ApplyExecutionCleanup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ani/modeldev/v1/operations.proto",
}
