// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package submissionsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdmission = `-- name: GetAdmission :one
SELECT tenant_id, execution_id, operation_id, actor,
    intent_canonical, intent_hash, snapshot_canonical, spec_hash, accepted_at
FROM modeldev_executions
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
`

type GetAdmissionParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) GetAdmission(ctx context.Context, arg GetAdmissionParams) (ModeldevExecution, error) {
	row := q.db.QueryRow(ctx, getAdmission, arg.TenantID, arg.ExecutionID)
	var i ModeldevExecution
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.Actor,
		&i.IntentCanonical,
		&i.IntentHash,
		&i.SnapshotCanonical,
		&i.SpecHash,
		&i.AcceptedAt,
	)
	return i, err
}

const getPipelineDispatch = `-- name: GetPipelineDispatch :one
SELECT tenant_id, execution_id, operation_id, spec_hash, attempt_id,
    plan_canonical, plan_hash, state, reserved_at, uncertain_at, not_sent_at
FROM modeldev_pipeline_dispatches
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
`

type GetPipelineDispatchParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) GetPipelineDispatch(ctx context.Context, arg GetPipelineDispatchParams) (ModeldevPipelineDispatch, error) {
	row := q.db.QueryRow(ctx, getPipelineDispatch, arg.TenantID, arg.ExecutionID)
	var i ModeldevPipelineDispatch
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.AttemptID,
		&i.PlanCanonical,
		&i.PlanHash,
		&i.State,
		&i.ReservedAt,
		&i.UncertainAt,
		&i.NotSentAt,
	)
	return i, err
}

const getSubmissionObservationTime = `-- name: GetSubmissionObservationTime :one
SELECT attempt_id, plan_hash, reserved_at,
    clock_timestamp()::timestamptz AS observed_at
FROM modeldev_pipeline_dispatches
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
`

type GetSubmissionObservationTimeParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

type GetSubmissionObservationTimeRow struct {
	AttemptID  pgtype.UUID
	PlanHash   string
	ReservedAt pgtype.Timestamptz
	ObservedAt pgtype.Timestamptz
}

// Sample this database's clock after the outbound call. The adapter compares
// the returned immutable attempt/hash with the original permit and requires
// observed_at >= reserved_at. Keeping the tenant-scoped row distinguishes a
// missing reservation from a conflicting attempt without a second lookup.
// This read neither authorizes a send nor locks across network work.
func (q *Queries) GetSubmissionObservationTime(ctx context.Context, arg GetSubmissionObservationTimeParams) (GetSubmissionObservationTimeRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionObservationTime, arg.TenantID, arg.ExecutionID)
	var i GetSubmissionObservationTimeRow
	err := row.Scan(
		&i.AttemptID,
		&i.PlanHash,
		&i.ReservedAt,
		&i.ObservedAt,
	)
	return i, err
}

const insertConfirmedPipelineRun = `-- name: InsertConfirmedPipelineRun :execrows
INSERT INTO modeldev_pipeline_confirmed_runs (
    tenant_id, execution_id, attempt_id, plan_hash, run_id, first_observed_at
)
SELECT tenant_id, execution_id, attempt_id, plan_hash,
    $1::uuid, $2::timestamptz
FROM modeldev_pipeline_dispatches
WHERE tenant_id = $3::uuid
  AND execution_id = $4::uuid
  AND attempt_id = $5::uuid
  AND plan_hash = $6::text
  AND state IN ('SUBMITTING', 'SUBMISSION_NOT_SENT', 'SUBMISSION_UNCERTAIN', 'SUBMISSION_CONFIRMED')
  AND $2::timestamptz >= reserved_at
ON CONFLICT (tenant_id, execution_id, attempt_id, run_id) DO NOTHING
`

type InsertConfirmedPipelineRunParams struct {
	RunID       pgtype.UUID
	ObservedAt  pgtype.Timestamptz
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
	AttemptID   pgtype.UUID
	PlanHash    string
}

// The caller has matched the original permit and complete frozen plan under
// the identity lock. A late observation survives close/deadline. Replaying the
// same Run never refreshes its first time; another Run is retained separately.
func (q *Queries) InsertConfirmedPipelineRun(ctx context.Context, arg InsertConfirmedPipelineRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertConfirmedPipelineRun,
		arg.RunID,
		arg.ObservedAt,
		arg.TenantID,
		arg.ExecutionID,
		arg.AttemptID,
		arg.PlanHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPipelineDispatch = `-- name: InsertPipelineDispatch :one
INSERT INTO modeldev_pipeline_dispatches (
    tenant_id, execution_id, operation_id, spec_hash, attempt_id,
    plan_canonical, plan_hash, state, reserved_at
)
SELECT tenant_id, execution_id, operation_id, spec_hash,
    $1::uuid, $2::bytea,
    $3::text, 'SUBMITTING', clock_timestamp()
FROM modeldev_execution_identities
WHERE tenant_id = $4::uuid
  AND execution_id = $5::uuid
  AND operation_id = $6::uuid
  AND spec_hash = $7::text
  AND close_generation = 0
  AND clock_timestamp() < $8::timestamptz
RETURNING tenant_id, execution_id, operation_id, spec_hash, attempt_id,
    plan_canonical, plan_hash, state, reserved_at, uncertain_at, not_sent_at
`

type InsertPipelineDispatchParams struct {
	AttemptID     pgtype.UUID
	PlanCanonical []byte
	PlanHash      string
	TenantID      pgtype.UUID
	ExecutionID   pgtype.UUID
	OperationID   pgtype.UUID
	SpecHash      string
	DeadlineAt    pgtype.Timestamptz
}

// The caller holds this identity's row lock and has compared the complete
// admitted command. Check the current database clock after acquiring the lock;
// transaction-start time could predate a long wait behind a close transaction.
func (q *Queries) InsertPipelineDispatch(ctx context.Context, arg InsertPipelineDispatchParams) (ModeldevPipelineDispatch, error) {
	row := q.db.QueryRow(ctx, insertPipelineDispatch,
		arg.AttemptID,
		arg.PlanCanonical,
		arg.PlanHash,
		arg.TenantID,
		arg.ExecutionID,
		arg.OperationID,
		arg.SpecHash,
		arg.DeadlineAt,
	)
	var i ModeldevPipelineDispatch
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.AttemptID,
		&i.PlanCanonical,
		&i.PlanHash,
		&i.State,
		&i.ReservedAt,
		&i.UncertainAt,
		&i.NotSentAt,
	)
	return i, err
}

const listConfirmedPipelineRuns = `-- name: ListConfirmedPipelineRuns :many
SELECT tenant_id, execution_id, attempt_id, plan_hash, run_id, first_observed_at
FROM modeldev_pipeline_confirmed_runs
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
  AND attempt_id = $3::uuid
  AND plan_hash = $4::text
ORDER BY run_id
`

type ListConfirmedPipelineRunsParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
	AttemptID   pgtype.UUID
	PlanHash    string
}

// These immutable observations belong to one exact reservation, not to an
// authoritative Run binding. Ordering gives stable output, never priority.
// Readers combining this list with dispatch state must use one consistent
// snapshot; writers hold the shared execution identity lock.
func (q *Queries) ListConfirmedPipelineRuns(ctx context.Context, arg ListConfirmedPipelineRunsParams) ([]ModeldevPipelineConfirmedRun, error) {
	rows, err := q.db.Query(ctx, listConfirmedPipelineRuns,
		arg.TenantID,
		arg.ExecutionID,
		arg.AttemptID,
		arg.PlanHash,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModeldevPipelineConfirmedRun
	for rows.Next() {
		var i ModeldevPipelineConfirmedRun
		if err := rows.Scan(
			&i.TenantID,
			&i.ExecutionID,
			&i.AttemptID,
			&i.PlanHash,
			&i.RunID,
			&i.FirstObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExecutionIdentity = `-- name: LockExecutionIdentity :one
SELECT tenant_id, execution_id, operation_id, spec_hash,
    close_generation = 0 AS creation_open
FROM modeldev_execution_identities
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
FOR UPDATE
`

type LockExecutionIdentityParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

type LockExecutionIdentityRow struct {
	TenantID     pgtype.UUID
	ExecutionID  pgtype.UUID
	OperationID  pgtype.UUID
	SpecHash     string
	CreationOpen bool
}

func (q *Queries) LockExecutionIdentity(ctx context.Context, arg LockExecutionIdentityParams) (LockExecutionIdentityRow, error) {
	row := q.db.QueryRow(ctx, lockExecutionIdentity, arg.TenantID, arg.ExecutionID)
	var i LockExecutionIdentityRow
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.CreationOpen,
	)
	return i, err
}

const markSubmissionConfirmed = `-- name: MarkSubmissionConfirmed :one
UPDATE modeldev_pipeline_dispatches AS dispatch
SET state = 'SUBMISSION_CONFIRMED'
WHERE dispatch.tenant_id = $1::uuid
  AND dispatch.execution_id = $2::uuid
  AND dispatch.attempt_id = $3::uuid
  AND dispatch.plan_hash = $4::text
  AND dispatch.state IN ('SUBMITTING', 'SUBMISSION_NOT_SENT', 'SUBMISSION_UNCERTAIN')
  AND EXISTS (
      SELECT 1
      FROM modeldev_pipeline_confirmed_runs AS observed
      WHERE observed.tenant_id = dispatch.tenant_id
        AND observed.execution_id = dispatch.execution_id
        AND observed.attempt_id = dispatch.attempt_id
        AND observed.plan_hash = dispatch.plan_hash
  )
RETURNING dispatch.tenant_id, dispatch.execution_id, dispatch.operation_id,
    dispatch.spec_hash, dispatch.attempt_id, dispatch.plan_canonical,
    dispatch.plan_hash, dispatch.state, dispatch.reserved_at, dispatch.uncertain_at, dispatch.not_sent_at
`

type MarkSubmissionConfirmedParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
	AttemptID   pgtype.UUID
	PlanHash    string
}

// In the same transaction as the retained handle, mark the original attempt's
// first confirmation without erasing earlier no-send/uncertainty observations.
func (q *Queries) MarkSubmissionConfirmed(ctx context.Context, arg MarkSubmissionConfirmedParams) (ModeldevPipelineDispatch, error) {
	row := q.db.QueryRow(ctx, markSubmissionConfirmed,
		arg.TenantID,
		arg.ExecutionID,
		arg.AttemptID,
		arg.PlanHash,
	)
	var i ModeldevPipelineDispatch
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.AttemptID,
		&i.PlanCanonical,
		&i.PlanHash,
		&i.State,
		&i.ReservedAt,
		&i.UncertainAt,
		&i.NotSentAt,
	)
	return i, err
}

const markSubmissionNotSent = `-- name: MarkSubmissionNotSent :one
UPDATE modeldev_pipeline_dispatches
SET not_sent_at = $1::timestamptz,
    state = CASE WHEN state = 'SUBMITTING' THEN 'SUBMISSION_NOT_SENT' ELSE state END
WHERE tenant_id = $2::uuid
  AND execution_id = $3::uuid
  AND attempt_id = $4::uuid
  AND plan_hash = $5::text
  AND state IN ('SUBMITTING', 'SUBMISSION_NOT_SENT', 'SUBMISSION_UNCERTAIN', 'SUBMISSION_CONFIRMED')
  AND not_sent_at IS NULL
  AND $1::timestamptz >= reserved_at
RETURNING tenant_id, execution_id, operation_id, spec_hash, attempt_id,
    plan_canonical, plan_hash, state, reserved_at, uncertain_at, not_sent_at
`

type MarkSubmissionNotSentParams struct {
	ObservedAt  pgtype.Timestamptz
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
	AttemptID   pgtype.UUID
	PlanHash    string
}

// Keep the first local no-send observation even when a stronger observation
// arrived first. Existing uncertainty/confirmation and all Run handles remain.
// The caller holds the original identity lock and has matched the frozen plan.
func (q *Queries) MarkSubmissionNotSent(ctx context.Context, arg MarkSubmissionNotSentParams) (ModeldevPipelineDispatch, error) {
	row := q.db.QueryRow(ctx, markSubmissionNotSent,
		arg.ObservedAt,
		arg.TenantID,
		arg.ExecutionID,
		arg.AttemptID,
		arg.PlanHash,
	)
	var i ModeldevPipelineDispatch
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.AttemptID,
		&i.PlanCanonical,
		&i.PlanHash,
		&i.State,
		&i.ReservedAt,
		&i.UncertainAt,
		&i.NotSentAt,
	)
	return i, err
}

const markSubmissionUncertain = `-- name: MarkSubmissionUncertain :one
UPDATE modeldev_pipeline_dispatches
SET state = 'SUBMISSION_UNCERTAIN', uncertain_at = $1::timestamptz
WHERE tenant_id = $2::uuid
  AND execution_id = $3::uuid
  AND attempt_id = $4::uuid
  AND plan_hash = $5::text
  AND state IN ('SUBMITTING', 'SUBMISSION_NOT_SENT')
  AND uncertain_at IS NULL
  AND $1::timestamptz >= reserved_at
RETURNING tenant_id, execution_id, operation_id, spec_hash, attempt_id,
    plan_canonical, plan_hash, state, reserved_at, uncertain_at, not_sent_at
`

type MarkSubmissionUncertainParams struct {
	ObservedAt  pgtype.Timestamptz
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
	AttemptID   pgtype.UUID
	PlanHash    string
}

// The caller holds the shared identity lock and has matched the original
// attempt and frozen plan. Close/deadline do not discard late observations.
// An already uncertain row is read back unchanged rather than updated again.
func (q *Queries) MarkSubmissionUncertain(ctx context.Context, arg MarkSubmissionUncertainParams) (ModeldevPipelineDispatch, error) {
	row := q.db.QueryRow(ctx, markSubmissionUncertain,
		arg.ObservedAt,
		arg.TenantID,
		arg.ExecutionID,
		arg.AttemptID,
		arg.PlanHash,
	)
	var i ModeldevPipelineDispatch
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.AttemptID,
		&i.PlanCanonical,
		&i.PlanHash,
		&i.State,
		&i.ReservedAt,
		&i.UncertainAt,
		&i.NotSentAt,
	)
	return i, err
}
