// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package submissionsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdmission = `-- name: GetAdmission :one
SELECT tenant_id, execution_id, operation_id, actor,
    intent_canonical, intent_hash, snapshot_canonical, spec_hash, accepted_at
FROM modeldev_executions
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
`

type GetAdmissionParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) GetAdmission(ctx context.Context, arg GetAdmissionParams) (ModeldevExecution, error) {
	row := q.db.QueryRow(ctx, getAdmission, arg.TenantID, arg.ExecutionID)
	var i ModeldevExecution
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.Actor,
		&i.IntentCanonical,
		&i.IntentHash,
		&i.SnapshotCanonical,
		&i.SpecHash,
		&i.AcceptedAt,
	)
	return i, err
}

const getPipelineDispatch = `-- name: GetPipelineDispatch :one
SELECT tenant_id, execution_id, operation_id, spec_hash, attempt_id,
    plan_canonical, plan_hash, state, reserved_at
FROM modeldev_pipeline_dispatches
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
`

type GetPipelineDispatchParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

func (q *Queries) GetPipelineDispatch(ctx context.Context, arg GetPipelineDispatchParams) (ModeldevPipelineDispatch, error) {
	row := q.db.QueryRow(ctx, getPipelineDispatch, arg.TenantID, arg.ExecutionID)
	var i ModeldevPipelineDispatch
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.AttemptID,
		&i.PlanCanonical,
		&i.PlanHash,
		&i.State,
		&i.ReservedAt,
	)
	return i, err
}

const insertPipelineDispatch = `-- name: InsertPipelineDispatch :one
INSERT INTO modeldev_pipeline_dispatches (
    tenant_id, execution_id, operation_id, spec_hash, attempt_id,
    plan_canonical, plan_hash, state, reserved_at
)
SELECT tenant_id, execution_id, operation_id, spec_hash,
    $1::uuid, $2::bytea,
    $3::text, 'SUBMITTING', clock_timestamp()
FROM modeldev_execution_identities
WHERE tenant_id = $4::uuid
  AND execution_id = $5::uuid
  AND operation_id = $6::uuid
  AND spec_hash = $7::text
  AND close_generation = 0
  AND clock_timestamp() < $8::timestamptz
RETURNING tenant_id, execution_id, operation_id, spec_hash, attempt_id,
    plan_canonical, plan_hash, state, reserved_at
`

type InsertPipelineDispatchParams struct {
	AttemptID     pgtype.UUID
	PlanCanonical []byte
	PlanHash      string
	TenantID      pgtype.UUID
	ExecutionID   pgtype.UUID
	OperationID   pgtype.UUID
	SpecHash      string
	DeadlineAt    pgtype.Timestamptz
}

// The caller holds this identity's row lock and has compared the complete
// admitted command. Check the current database clock after acquiring the lock;
// transaction-start time could predate a long wait behind a close transaction.
func (q *Queries) InsertPipelineDispatch(ctx context.Context, arg InsertPipelineDispatchParams) (ModeldevPipelineDispatch, error) {
	row := q.db.QueryRow(ctx, insertPipelineDispatch,
		arg.AttemptID,
		arg.PlanCanonical,
		arg.PlanHash,
		arg.TenantID,
		arg.ExecutionID,
		arg.OperationID,
		arg.SpecHash,
		arg.DeadlineAt,
	)
	var i ModeldevPipelineDispatch
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.AttemptID,
		&i.PlanCanonical,
		&i.PlanHash,
		&i.State,
		&i.ReservedAt,
	)
	return i, err
}

const lockExecutionIdentity = `-- name: LockExecutionIdentity :one
SELECT tenant_id, execution_id, operation_id, spec_hash,
    close_generation = 0 AS creation_open
FROM modeldev_execution_identities
WHERE tenant_id = $1::uuid
  AND execution_id = $2::uuid
FOR UPDATE
`

type LockExecutionIdentityParams struct {
	TenantID    pgtype.UUID
	ExecutionID pgtype.UUID
}

type LockExecutionIdentityRow struct {
	TenantID     pgtype.UUID
	ExecutionID  pgtype.UUID
	OperationID  pgtype.UUID
	SpecHash     string
	CreationOpen bool
}

func (q *Queries) LockExecutionIdentity(ctx context.Context, arg LockExecutionIdentityParams) (LockExecutionIdentityRow, error) {
	row := q.db.QueryRow(ctx, lockExecutionIdentity, arg.TenantID, arg.ExecutionID)
	var i LockExecutionIdentityRow
	err := row.Scan(
		&i.TenantID,
		&i.ExecutionID,
		&i.OperationID,
		&i.SpecHash,
		&i.CreationOpen,
	)
	return i, err
}
